// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 209, boss 62498 (Champion Razjal the Quick), 38 anchors over 599yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute209_62498()
{
    DungeonClearRouteRegistry::Register(209, DUNGEON_DIFFICULTY_NORMAL, 62498,
        {
            { 1759.48f, 1437.21f, 0.43f },
            { 1742.76f, 1435.11f, -0.56f },
            { 1726.55f, 1433.30f, -0.64f },
            { 1710.75f, 1428.79f, -1.01f },
            { 1700.61f, 1415.83f, -0.94f },
            { 1688.83f, 1402.77f, -0.82f },
            { 1678.09f, 1389.45f, -0.82f },
            { 1667.43f, 1374.97f, -1.08f },
            { 1657.46f, 1361.18f, -0.59f },
            { 1638.68f, 1353.67f, -0.09f },
            { 1622.45f, 1350.61f, 0.28f },
            { 1614.16f, 1347.25f, 1.69f },
            { 1610.87f, 1339.03f, 4.35f },
            { 1614.39f, 1322.77f, 8.57f },
            { 1621.75f, 1305.55f, 9.36f },
            { 1633.12f, 1293.97f, 9.11f },
            { 1645.38f, 1279.04f, 9.57f },
            { 1656.02f, 1266.46f, 9.84f },
            { 1658.53f, 1258.35f, 10.25f },
            { 1652.70f, 1242.79f, 16.38f },
            { 1651.58f, 1224.55f, 10.13f },
            { 1651.67f, 1213.08f, 9.94f },
            { 1643.92f, 1211.05f, 9.73f },
            { 1638.15f, 1192.77f, 8.92f },
            { 1634.63f, 1175.63f, 8.90f },
            { 1631.87f, 1157.76f, 8.95f },
            { 1626.05f, 1141.02f, 8.88f },
            { 1613.95f, 1122.84f, 8.88f },
            { 1605.86f, 1121.70f, 8.88f },
            { 1592.73f, 1109.40f, 9.62f },
            { 1582.98f, 1096.27f, 9.23f },
            { 1575.55f, 1079.55f, 9.00f },
            { 1565.53f, 1065.46f, 8.88f },
            { 1556.64f, 1051.42f, 9.51f },
            { 1552.83f, 1035.64f, 12.15f },
            { 1535.97f, 1029.69f, 11.74f },
            { 1519.39f, 1023.78f, 11.46f },
            { 1501.96f, 1017.55f, 11.70f },
        });
}
