// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 70, boss 1325400066 (Altar of Archaedas), 39 anchors over 553yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute70_1325400066()
{
    DungeonClearRouteRegistry::Register(70, DUNGEON_DIFFICULTY_NORMAL, 1325400066,
        {
            { 42.86f, 438.19f, -40.49f },
            { 52.00f, 423.96f, -40.49f },
            { 59.62f, 409.01f, -37.50f },
            { 61.48f, 390.93f, -37.69f },
            { 55.23f, 372.78f, -38.76f },
            { 52.19f, 365.13f, -42.25f },
            { 51.33f, 346.22f, -39.60f },
            { 50.40f, 338.09f, -40.84f },
            { 45.21f, 331.47f, -42.71f },
            { 41.72f, 315.05f, -41.00f },
            { 27.28f, 305.07f, -38.69f },
            { 18.59f, 290.75f, -38.87f },
            { 9.31f, 273.67f, -35.34f },
            { 14.77f, 255.76f, -34.61f },
            { 18.36f, 247.99f, -33.34f },
            { 24.68f, 243.04f, -30.24f },
            { 32.77f, 245.44f, -26.93f },
            { 51.41f, 250.40f, -25.99f },
            { 67.56f, 254.93f, -25.99f },
            { 85.20f, 259.73f, -25.86f },
            { 95.28f, 261.73f, -25.82f },
            { 104.34f, 258.20f, -25.81f },
            { 110.50f, 251.49f, -25.70f },
            { 122.52f, 263.06f, -25.73f },
            { 131.99f, 276.72f, -25.99f },
            { 139.30f, 282.65f, -25.99f },
            { 149.80f, 281.50f, -25.99f },
            { 159.85f, 268.06f, -27.89f },
            { 165.31f, 251.08f, -28.79f },
            { 148.38f, 237.80f, -36.89f },
            { 141.69f, 232.28f, -39.92f },
            { 119.56f, 222.91f, -41.89f },
            { 103.81f, 216.99f, -45.50f },
            { 95.21f, 213.88f, -50.57f },
            { 87.08f, 211.06f, -54.11f },
            { 72.02f, 223.32f, -54.80f },
            { 70.68f, 233.68f, -51.12f },
            { 70.99f, 249.92f, -51.69f },
            { 85.51f, 261.21f, -51.60f },
        });
}
