#!/usr/bin/env bash
# Generate BotMenu's surname table (twow-repo#518) from OB-40's roster table.
#
# The bots keep one-word character names (whisper, /invite, links and the
# server's name lookup only work with those); the surname is display-only and
# lives in this addon table. Source: twow-repo deploy/roster/names-518/
# addon-surnames-810.tsv (columns first_name, surname, ordinal, race, class,
# gender). Each first name and each surname appears once.
#
#   tools/gen_botmenu_surnames.sh <addon-surnames.tsv> [expected-sha256] \
#       > addon/BotMenu-1.12/BotSurnames.lua
set -euo pipefail

tsv="$1"
want="${2:-}"
have="$(sha256sum "$tsv" | cut -c1-64)"
if [ -n "$want" ] && [ "$have" != "$want" ]; then
  echo "gen_botmenu_surnames: $tsv has sha256 $have, expected $want" >&2
  exit 1
fi

awk -F'\t' -v sha="$have" -v src="$(basename "$tsv")" '
NR == 1 {
  if ($1 != "first_name" || $2 != "surname") { print "unexpected header: " $0 > "/dev/stderr"; exit 1 }
  print "-- BotMenu surnames (twow-repo#518). GENERATED by tools/gen_botmenu_surnames.sh - do not edit."
  print "-- Source: " src " sha256 " sha
  print "-- Display only: the character name stays one word; the surname is never sent to the server."
  print "BOTMENU_SURNAMES = {"
  next
}
{
  if ($1 !~ /^[A-Z][a-z]+$/) { print "bad first name in line " NR ": " $1 > "/dev/stderr"; bad = 1 }
  if ($2 !~ /^[A-Za-z][A-Za-z '\''-]*$/) { print "bad surname in line " NR ": " $2 > "/dev/stderr"; bad = 1 }
  if (seen[$1]++) { print "duplicate first name: " $1 > "/dev/stderr"; bad = 1 }
  printf "\t[\"%s\"] = \"%s\",\n", $1, $2
  n++
}
END {
  if (bad) exit 1
  print "};"
  print "BOTMENU_SURNAMES_COUNT = " n ";"
}' "$tsv"
