# twow-repo#541 (audit A06, cards 45 and 6): behind AiPlayerbot.Perf.AttackersLazyChecks (default 0)
# AttackersValue::IsValid does less work for the same result.
# Level 1: the PvP-prohibited-zone area lookup (global TerrainManager lock + VMAP query) runs only where
# it is read (enemy players after the pvp strategy check, pets in the NPC branch).
# Level 2: the bot's own candidates (owner == player) that are not fighting it (not duel opponent, not
# InCombat, not rti) return false before the possible-target and faction checks. Group members and the
# master (owner != player) keep today's order (X3).
# Switch off: the eager lookup at the old spot and the original checks, unchanged.

if(NOT DEFINED PB_SOURCE_DIR)
  message(FATAL_ERROR "PB_SOURCE_DIR is required")
endif()

function(read_source path out_var)
  file(READ "${PB_SOURCE_DIR}/${path}" text)
  string(REPLACE "\r" "" text "${text}")
  set(${out_var} "${text}" PARENT_SCOPE)
endfunction()

function(require_text text needle description)
  string(FIND "${text}" "${needle}" offset)
  if(offset EQUAL -1)
    message(FATAL_ERROR "#541 A06: missing ${description}: ${needle}")
  endif()
endfunction()

function(forbid_text text needle description)
  string(FIND "${text}" "${needle}" offset)
  if(NOT offset EQUAL -1)
    message(FATAL_ERROR "#541 A06: forbidden ${description}: ${needle}")
  endif()
endfunction()

function(require_order text first second description)
  string(FIND "${text}" "${first}" a)
  string(FIND "${text}" "${second}" b)
  if(a EQUAL -1 OR b EQUAL -1 OR NOT a LESS b)
    message(FATAL_ERROR "#541 A06: order ${description}: '${first}' must come before '${second}'")
  endif()
endfunction()

function(function_body text signature out_var)
  string(FIND "${text}" "${signature}" start)
  if(start EQUAL -1)
    message(FATAL_ERROR "#541 A06: function not found: ${signature}")
  endif()
  string(SUBSTRING "${text}" ${start} -1 rest)
  string(FIND "${rest}" "\n}\n" end)
  if(end EQUAL -1)
    message(FATAL_ERROR "#541 A06: function end not found: ${signature}")
  endif()
  string(SUBSTRING "${rest}" 0 ${end} body)
  set(${out_var} "${body}" PARENT_SCOPE)
endfunction()

function(region text start_marker end_marker out)
  string(FIND "${text}" "${start_marker}" start)
  if(start EQUAL -1)
    message(FATAL_ERROR "#541 A06: missing region start: ${start_marker}")
  endif()
  string(SUBSTRING "${text}" ${start} -1 rest)
  string(FIND "${rest}" "${end_marker}" length)
  if(length EQUAL -1)
    message(FATAL_ERROR "#541 A06: missing region end: ${end_marker}")
  endif()
  string(SUBSTRING "${rest}" 0 ${length} body)
  set(${out} "${body}" PARENT_SCOPE)
endfunction()

function(count_text text needle expected description)
  set(n 0)
  set(rest "${text}")
  string(LENGTH "${needle}" len)
  while(TRUE)
    string(FIND "${rest}" "${needle}" at)
    if(at EQUAL -1)
      break()
    endif()
    math(EXPR n "${n} + 1")
    math(EXPR at "${at} + ${len}")
    string(SUBSTRING "${rest}" ${at} -1 rest)
  endwhile()
  if(NOT n EQUAL expected)
    message(FATAL_ERROR "#541 A06: ${description}: '${needle}' found ${n}x, expected ${expected}")
  endif()
endfunction()

read_source("strategy/values/AttackersValue.cpp" attackers)
read_source("strategy/values/AttackersValue.h" attackers_h)
read_source("PlayerbotAIConfig.h" config_h)
read_source("PlayerbotAIConfig.cpp" config_cpp)
read_source("aiplayerbot.conf.dist.in" conf_dist)

# Switch: level 0..2, default 0 (off), clamped, documented with value 0.
require_text("${config_h}" "uint32 perfAttackersLazyChecks = 0;" "member default off")
require_text("${config_cpp}" "perfAttackersLazyChecks = uint32(std::min<int32>(2, std::max<int32>(0, config.GetIntDefault(\"AiPlayerbot.Perf.AttackersLazyChecks\", 0))));" "config default 0, clamp 0..2")
require_text("${conf_dist}" "\nAiPlayerbot.Perf.AttackersLazyChecks = 0\n" "documented key with value 0")

function_body("${attackers}" "bool AttackersValue::IsValid(Unit* target, Player* player, Player* owner, bool checkInCombat, bool validatePossibleTarget)" valid_body)
function_body("${attackers}" "bool AttackersValue::IsRtiTargetOf(Unit* target, Player* player)" rti_body)
require_text("${attackers_h}" "static bool IsRtiTargetOf(Unit* target, Player* player);" "rti helper declaration")

set(read_switch "const uint32 lazyLevel = sPlayerbotAIConfig.perfAttackersLazyChecks;")
set(level1 "const bool lazyChecks = lazyLevel >= 1;")
set(l2_gate "if (lazyLevel >= 2 && checkInCombat && owner != nullptr && player == owner &&")
set(l2_guard "        target && target->IsInWorld() && target->GetMapId() == player->GetMapId() &&\n        !sServerFacade.UnitIsDead(target))\n    {")
set(l2_duel "const bool isDuelOpponent = dynamic_cast<Player*>(target) &&\n            player->m_duel && player->m_duel->opponent == target->GetObjectGuid();")
set(l2_exit "if (!isDuelOpponent && !InCombat(target, player, (player == owner)) && !IsRtiTargetOf(target, player))\n            return false;\n    }")
set(possible "if (validatePossibleTarget && !PossibleTargetsValue::IsValid(target, playerToCheckAgainst))")
set(lazy_area "sPlayerbotAIConfig.IsInPvpProhibitedZone(sServerFacade.GetAreaId(target))")
set(eager_off "const bool inPvPProhibitedZone = !lazyChecks && ${lazy_area};")
set(player_zone "if (lazyChecks ? ${lazy_area} : inPvPProhibitedZone)")
set(pet_zone "if (target->GetObjectGuid().IsPet() && (lazyChecks ? ${lazy_area} : inPvPProhibitedZone))")
set(orig_player_combat "if (checkInCombat && !isDuelOpponent && !InCombat(target, player, (player == owner)))")
set(orig_npc_combat "if (checkInCombat && !InCombat(target, player, (player == owner)))")

# Level 2 sits in front of everything, own bot only (owner == player), behind the cheap in-world guard,
# keeps the duel and rti exceptions and exits with 'return false'.
require_order("${valid_body}" "${read_switch}" "${level1}" "switch read once")
require_order("${valid_body}" "${level1}" "${l2_gate}" "level 1 before the level 2 gate")
require_order("${valid_body}" "${l2_gate}" "${l2_guard}" "in-world/same-map/alive guard in the gate")
require_order("${valid_body}" "${l2_guard}" "${l2_duel}" "duel opponent test inside the gate")
require_order("${valid_body}" "${l2_duel}" "${l2_exit}" "early reject after the duel test")
require_order("${valid_body}" "${l2_exit}" "${possible}" "early reject before the possible-target check")
count_text("${valid_body}" "sPlayerbotAIConfig.perfAttackersLazyChecks" 1 "switch read")
count_text("${valid_body}" "lazyLevel >= 2" 1 "level 2 gate")

# Level 1 and the original path kept verbatim (switch 0 identical).
require_order("${valid_body}" "${possible}" "${eager_off}" "eager lookup at the old spot when off")
require_order("${valid_body}" "${eager_off}" "Player* enemyPlayer = dynamic_cast<Player*>(target);" "eager lookup before the branch split")
require_order("${valid_body}" "!GetBotAI(playerToCheckAgainst)->HasStrategy(\"pvp\", BotState::BOT_STATE_COMBAT)" "${player_zone}" "lazy player lookup after the pvp strategy check")
require_order("${valid_body}" "${player_zone}" "const bool isDuelOpponent = player->m_duel && player->m_duel->opponent == target->GetObjectGuid();" "original duel test kept")
require_order("${valid_body}" "${player_zone}" "${orig_player_combat}" "original player combat check kept")
require_order("${valid_body}" "if (sServerFacade.IsFriendlyTo(playerToCheckAgainst, target))" "${orig_npc_combat}" "original NPC combat check kept")
require_order("${valid_body}" "${orig_npc_combat}" "${pet_zone}" "lazy pet lookup after the NPC combat check")
require_order("${valid_body}" "${pet_zone}" "if (creature->GetCombatManager().IsInEvadeMode())" "evade check kept")
count_text("${valid_body}" "sServerFacade.GetAreaId(target)" 3 "area lookups (one eager when off, two lazy)")
count_text("${valid_body}" "PAI_VALUE(Unit*, \"rti target\")" 2 "original rti blocks")
count_text("${valid_body}" "${orig_npc_combat}" 1 "original NPC combat check")
count_text("${valid_body}" "${orig_player_combat}" 1 "original player combat check")
forbid_text("${valid_body}" "const bool inPvPProhibitedZone = sPlayerbotAIConfig.IsInPvpProhibitedZone(" "old unconditional eager lookup")
forbid_text("${valid_body}" "target->GetAreaId()" "area from another source than the facade call")
forbid_text("${valid_body}" "static " "static state in IsValid")
forbid_text("${attackers}" "std::shared_mutex" "shared_mutex")

# The rti helper repeats the original rti exception, in the bot's own context only.
require_text("${rti_body}" "if (GetBotAI(player) && !GetBotAI(player)->HasActivePlayerMaster())" "rti guard")
require_text("${rti_body}" "Unit* rtiTarget = PAI_VALUE(Unit*, \"rti target\");" "rti read")
require_text("${rti_body}" "return target == rtiTarget;" "rti compare")
forbid_text("${rti_body}" "static " "static state in the rti helper")
forbid_text("${rti_body}" "owner" "owner context in the rti helper")

# The original rti blocks themselves are unchanged (same text in both branches).
region("${valid_body}" "${orig_player_combat}" "// If the target is a NPC" player_combat_block)
require_text("${player_combat_block}" "if (GetBotAI(player) && !GetBotAI(player)->HasActivePlayerMaster())" "player branch rti guard")
require_text("${player_combat_block}" "if (!isRtiTarget)\n                return false;" "player branch rti exit")
region("${valid_body}" "${orig_npc_combat}" "// If the target is a player's pet" npc_combat_block)
require_text("${npc_combat_block}" "if (GetBotAI(player) && !GetBotAI(player)->HasActivePlayerMaster())" "NPC branch rti guard")
require_text("${npc_combat_block}" "if(!isRtiTarget)\n                return false;" "NPC branch rti exit")

message(STATUS "attackers_lazy_checks source contract passed")
