function(require_text text needle description)
  string(FIND "${text}" "${needle}" offset)
  if(offset EQUAL -1)
    message(FATAL_ERROR "Missing ${description}: ${needle}")
  endif()
endfunction()

function(reject_text text needle description)
  string(FIND "${text}" "${needle}" offset)
  if(NOT offset EQUAL -1)
    message(FATAL_ERROR "Forbidden ${description}: ${needle}")
  endif()
endfunction()

file(READ "${PB_SOURCE_DIR}/strategy/values/ItemUsageValue.cpp" usage)
file(READ "${PB_SOURCE_DIR}/strategy/values/MaintenanceValues.h" maintenance)
file(READ "${PB_SOURCE_DIR}/PlayerbotAIConfig.cpp" config_source)
file(READ "${PB_SOURCE_DIR}/aiplayerbot.conf.dist.in" config_template)

# #308: with the auction house off, nothing is hoarded for it.
require_text("${config_source}" "\"AiPlayerbot.AuctionHouse.Enabled\", true" "switch with unchanged default")
require_text("${config_template}" "AiPlayerbot.AuctionHouse.Enabled = 1" "documented default")
require_text("${usage}" "if (!sPlayerbotAIConfig.auctionHouseEnabled)" "no AH usage while disabled")

# Only the AH values are gated, never vendor selling or buying. Each class is
# checked up to the end of its inline Calculate (the first "};").
function(class_window text name out)
  string(FIND "${text}" "class ${name} " start)
  if(start EQUAL -1)
    message(FATAL_ERROR "Missing class ${name}")
  endif()
  string(SUBSTRING "${text}" ${start} -1 rest)
  string(FIND "${rest}" "};" stop)
  string(SUBSTRING "${rest}" 0 ${stop} window)
  set(${out} "${window}" PARENT_SCOPE)
endfunction()
class_window("${maintenance}" "CanAHSellValue" ah_sell)
class_window("${maintenance}" "CanAHBuyValue" ah_buy)
class_window("${maintenance}" "CanSellValue" vendor_sell)
class_window("${maintenance}" "CanBuyValue" vendor_buy)
require_text("${ah_sell}" "sPlayerbotAIConfig.auctionHouseEnabled" "AH sell gated")
require_text("${ah_buy}" "sPlayerbotAIConfig.auctionHouseEnabled" "AH buy gated")
reject_text("${vendor_sell}" "auctionHouseEnabled" "vendor sell gated by the AH switch")
reject_text("${vendor_buy}" "auctionHouseEnabled" "vendor buy gated by the AH switch")
