# twow-repo#563 audit thread-safety items (owner OK 09.10.2026, CLI-541 audit #541 comment 6086496752):
# A28 eventCache, A29 chatCommands + PassiveMultiplier statics, A31 bot account lists, A51 botTexts + lazy
# emote/suggestion statics, A52 ShamanWeaponTrigger static.
# Lazy statics: std::call_once (no switch, same tables). botTexts: find() instead of operator[] (no switch,
# same results). chatCommands: own mutex like chatReplies, the command runs outside it. eventCache and the
# account lists: lock with AiPlayerbot.X3a.ContextLock (as A30), the DB query outside the lock.

function(read_source path out_var)
  file(READ "${PB_SOURCE_DIR}/${path}" text)
  string(REPLACE "\r" "" text "${text}")
  set(${out_var} "${text}" PARENT_SCOPE)
endfunction()

function(require_text text needle description)
  string(FIND "${text}" "${needle}" offset)
  if(offset EQUAL -1)
    message(FATAL_ERROR "#563 audit: missing ${description}: ${needle}")
  endif()
endfunction()

function(forbid_text text needle description)
  string(FIND "${text}" "${needle}" offset)
  if(NOT offset EQUAL -1)
    message(FATAL_ERROR "#563 audit: ${description}: ${needle}")
  endif()
endfunction()

function(require_order text first second description)
  string(FIND "${text}" "${first}" a)
  string(FIND "${text}" "${second}" b)
  if(a EQUAL -1 OR b EQUAL -1 OR NOT a LESS b)
    message(FATAL_ERROR "#563 audit: order ${description}: '${first}' must come before '${second}'")
  endif()
endfunction()

function(between text first second out_var)
  string(FIND "${text}" "${first}" a)
  if(a EQUAL -1)
    message(FATAL_ERROR "#563 audit: region not found: '${first}'")
  endif()
  string(SUBSTRING "${text}" ${a} -1 rest)
  string(FIND "${rest}" "${second}" b)
  if(b EQUAL -1)
    message(FATAL_ERROR "#563 audit: region end not found: '${second}'")
  endif()
  string(SUBSTRING "${rest}" 0 ${b} region)
  set(${out_var} "${region}" PARENT_SCOPE)
endfunction()

# A51 / A29 / A52: lazy statics filled once.
read_source("strategy/actions/SuggestWhatToDoAction.cpp" suggest)
require_text("${suggest}" "std::call_once(instancesOnce, []()" "instances filled once")
require_text("${suggest}" "std::call_once(factionsOnce, []()" "factions filled once")
forbid_text("${suggest}" "if (instances.empty())" "lazy unguarded fill")
forbid_text("${suggest}" "if (factions.empty())" "lazy unguarded fill")
read_source("strategy/actions/EmoteAction.cpp" emote)
require_text("${emote}" "std::call_once(emotesOnce, [this]() { InitEmotes(); });" "emotes filled once")
forbid_text("${emote}" "if (emotes.empty()) InitEmotes();" "lazy unguarded fill")
read_source("strategy/PassiveMultiplier.cpp" passive)
require_text("${passive}" "std::call_once(listsOnce, []()" "passive lists filled once")
forbid_text("${passive}" "if (allowedActions.empty())" "lazy unguarded fill")
forbid_text("${passive}" "if (allowedParts.empty())" "lazy unguarded fill")
read_source("strategy/shaman/ShamanTriggers.cpp" shaman)
read_source("strategy/shaman/ShamanTriggers.h" shaman_h)
forbid_text("${shaman}" "ShamanWeaponTrigger::spells" "static spell list")
forbid_text("${shaman_h}" "static std::list<std::string> spells;" "static spell list")
between("${shaman}" "bool ShamanWeaponTrigger::IsActive()" "bool ShockTrigger::IsActive()" weapon)
require_text("${weapon}" "uint32 spellId = AI_VALUE2(uint32, \"spell id\", spell);" "same spell as before")
require_text("${weapon}" "return AI_VALUE2(Item*, \"item for spell\", spellId) != nullptr;" "same item check as before")

# A51: botTexts read without inserting.
read_source("PlayerbotTextMgr.cpp" texts)
between("${texts}" "std::string PlayerbotTextMgr::GetBotText(std::string name)\n" "std::string PlayerbotTextMgr::GetBotText(std::string name, std::map" get_text)
between("${texts}" "std::string PlayerbotTextMgr::GetBotText(ChatReplyType replyType" "BotTextEntry textEntry = proper_list" get_reply)
foreach(region get_text get_reply)
  forbid_text("${${region}}" "botTexts[" "botTexts operator[] in a reader")
endforeach()
require_text("${get_text}" "auto const texts = botTexts.find(name);" "find by name")
require_text("${get_reply}" "auto const replies = botTexts.find(\"reply\");" "find replies")

# A29: chatCommands only under its mutex; the command runs outside it.
read_source("PlayerbotAI.cpp" ai_cpp)
read_source("PlayerbotAI.h" ai_h)
require_text("${ai_h}" "std::mutex chatCommandsMutex;" "chatCommands mutex")
string(REGEX MATCHALL "chatCommands\\.push\\([^)]*\\)" pushes "${ai_cpp}")
list(LENGTH pushes push_count)
if(NOT push_count EQUAL 2)
  message(FATAL_ERROR "#563 audit: chatCommands.push only in QueueChatCommand and the delayed re-push (found ${push_count})")
endif()
between("${ai_cpp}" "void PlayerbotAI::QueueChatCommand(ChatCommandHolder const& cmd)" "\n}\n" queue_fn)
require_order("${queue_fn}" "std::scoped_lock lock(chatCommandsMutex);" "chatCommands.push(cmd);" "push under the lock")
between("${ai_cpp}" "void PlayerbotAI::HandleCommands()" "void PlayerbotAI::QueueChatCommand(" handle)
between("${handle}" "std::scoped_lock lock(chatCommandsMutex);\n            if (chatCommands.empty())" "ChatCommandHolder& holder = *next;" take_block)
forbid_text("${take_block}" "ParseChatCommand" "command run under the lock")
require_order("${handle}" "ChatCommandHolder& holder = *next;" "helper.ParseChatCommand(command, owner)" "command after the lock block")
require_order("${handle}" "helper.ParseChatCommand(command, owner)" "std::scoped_lock lock(chatCommandsMutex);\n    for (std::list<ChatCommandHolder>::iterator i = delayed.begin()" "delayed re-push locked")
string(REGEX MATCHALL "chatCommands\\.(size|empty|front|pop)\\(" raw_uses "${ai_cpp}")
list(LENGTH raw_uses raw_count)
if(NOT raw_count EQUAL 4)
  message(FATAL_ERROR "#563 audit: unexpected chatCommands access outside the locked blocks (found ${raw_count})")
endif()
require_text("${ai_cpp}" "std::scoped_lock lock(chatCommandsMutex);   // audit A29; one lock at a time, never nested\n                queuedCommands = chatCommands.size();" "minute count locked")

# A28: eventCache - no inserting reader, DB query outside the lock, every write locked.
read_source("RandomPlayerbotMgr.cpp" mgr)
read_source("RandomPlayerbotMgr.h" mgr_h)
require_text("${mgr_h}" "mutable std::shared_mutex eventCacheMutex;" "eventCache mutex")
between("${mgr}" "uint32 RandomPlayerbotMgr::GetEventValue(uint32 bot, std::string event)" "int32 RandomPlayerbotMgr::GetValueValidTime(" get_event)
require_order("${get_event}" "auto results = CharacterDatabase.PQuery(" "ai::context_lock::Unique const lock(eventCacheMutex, ai::context_lock::On());" "query before the lock")
between("${get_event}" "auto results = CharacterDatabase.PQuery(" "ai::context_lock::Unique const lock(eventCacheMutex" load_block)
forbid_text("${load_block}" "eventCache[" "cache write during the query")
require_text("${get_event}" "cached.emplace(eventName, loadedEvent);" "merge without overwriting")
string(REGEX MATCHALL "eventCache\\[[^]]*\\]" mgr_writes "${mgr}")
list(LENGTH mgr_writes write_count)
if(NOT write_count EQUAL 4)
  message(FATAL_ERROR "#563 audit: eventCache operator[] only in the 4 locked writers (found ${write_count})")
endif()
foreach(write "e = eventCache[bot][event];" "eventCache[bot][event] = e;" "eventCache[owner].clear();" "std::map<std::string, CachedEvent>& cached = eventCache[bot];")
  string(FIND "${mgr}" "${write}" at)
  if(at EQUAL -1)
    message(FATAL_ERROR "#563 audit: writer not found: ${write}")
  endif()
  math(EXPR from "${at} - 160")
  if(from LESS 0)
    set(from 0)
  endif()
  string(SUBSTRING "${mgr}" ${from} 160 before)
  string(FIND "${before}" "ai::context_lock::Unique const lock(eventCacheMutex, ai::context_lock::On());" locked)
  if(locked EQUAL -1)
    message(FATAL_ERROR "#563 audit: eventCache write without the unique lock: ${write}")
  endif()
endforeach()
require_text("${mgr}" "ai::context_lock::Unique const lock(sRandomPlayerbotMgr.eventCacheMutex, ai::context_lock::On());   // audit A28\n        sRandomPlayerbotMgr.eventCache.clear();" "reset locked")
forbid_text("${mgr}" "!eventCache[bot].empty()" "inserting emptiness check")

# A31: the account lists only through PlayerbotAIConfig; the LoginDatabase query outside the lock.
read_source("PlayerbotAIConfig.cpp" config_cpp)
read_source("PlayerbotAIConfig.h" config_h)
require_text("${config_h}" "mutable std::shared_mutex randomBotAccountsMutex;" "account list mutex")
between("${config_cpp}" "bool PlayerbotAIConfig::IsInRandomAccountList(uint32 id)" "bool PlayerbotAIConfig::IsFreeAltBot(" in_list)
require_order("${in_list}" "ai::context_lock::Shared const lock(randomBotAccountsMutex, ai::context_lock::On());" "auto qr = LoginDatabase.PQuery(" "fast path locked before the query")
between("${in_list}" "// Slow path:" "if (!qr)" query_line)
forbid_text("${query_line}" "context_lock::" "query under the lock")
require_text("${in_list}" "if (randomBotAccountIndex.insert(id).second)\n            randomBotAccounts.push_back(id);" "no duplicate from a race")
require_text("${config_cpp}" "void PlayerbotAIConfig::AddRandomBotAccount(uint32 id)\n{" "append method")
file(GLOB_RECURSE module_sources "${PB_MODULE_DIR}/src/*.cpp" "${PB_MODULE_DIR}/src/*.h")
if(EXISTS "${PB_MODULE_DIR}/../mod-dungeon-clear/src")
  file(GLOB_RECURSE dc_sources "${PB_MODULE_DIR}/../mod-dungeon-clear/src/*.cpp")
  list(APPEND module_sources ${dc_sources})
endif()
foreach(source ${module_sources})
  if(source MATCHES "PlayerbotAIConfig\\.(cpp|h)$")
    continue()
  endif()
  file(READ "${source}" source_text)
  string(FIND "${source_text}" "sPlayerbotAIConfig.randomBotAccounts" direct)
  if(NOT direct EQUAL -1)
    message(FATAL_ERROR "#563 audit: direct randomBotAccounts access in ${source}; use AddRandomBotAccount / RandomBotAccountsSnapshot")
  endif()
endforeach()

message(STATUS "audit_statics source contract passed")
