if(NOT DEFINED PB_MODULE_DIR)
  message(FATAL_ERROR "PB_MODULE_DIR is required")
endif()

function(require_text text needle label)
  string(FIND "${text}" "${needle}" offset)
  if(offset EQUAL -1)
    message(FATAL_ERROR "Missing ${label}: ${needle}")
  endif()
endfunction()

function(require_absent text needle label)
  string(FIND "${text}" "${needle}" offset)
  if(NOT offset EQUAL -1)
    message(FATAL_ERROR "Unexpected ${label}: ${needle}")
  endif()
endfunction()

file(READ "${PB_MODULE_DIR}/src/playerbot/PlayerbotAIConfig.cpp" config)
file(READ "${PB_MODULE_DIR}/src/playerbot/strategy/values/TravelValues.cpp" travel_values)
file(READ "${PB_MODULE_DIR}/src/playerbot/strategy/values/QuestValues.cpp" quest_values)
file(READ "${PB_MODULE_DIR}/src/playerbot/strategy/actions/ChooseTravelTargetAction.cpp" quest_travel)
file(READ "${PB_MODULE_DIR}/src/playerbot/strategy/actions/FollowActions.cpp" follow_actions)
file(READ "${PB_MODULE_DIR}/src/playerbot/strategy/actions/SetHomeAction.cpp" set_home_action)
file(READ "${PB_MODULE_DIR}/src/playerbot/TravelMgr.cpp" travel_mgr)

foreach(required
  "AiPlayerbot.QuestFirstProgression.Enabled"
  "AiPlayerbot.QuestFirstProgression.AutonomousLogSoftLimit"
  "AiPlayerbot.QuestFirstProgression.RejectBelowLevelDelta"
  "AiPlayerbot.QuestFirstProgression.RetireBelowLevelDelta"
  "AiPlayerbot.QuestFirstProgression.MaxAboveLevelDelta"
  "AiPlayerbot.QuestFirstProgression.LocalHubRadius"
  "AiPlayerbot.QuestFirstProgression.TraceTravelDecisions"
  "AiPlayerbot.QuestFirstProgression.TurnInStallSeconds"
  "AiPlayerbot.QuestFirstProgression.TurnInRouteCooldownSeconds")
  require_text("${config}" "${required}" "configuration key")
endforeach()

require_text("${travel_values}" "TravelDestinationPurpose::Grind" "generic-grind hook")
require_text("${travel_values}" "UsesQuestFirstProgression(bot)" "roster-only grind gate")
require_text("${quest_values}" "ActiveQuestSlotCount(bot)" "soft-limit gate")
require_text("${quest_values}" "questFirstProgressionRejectBelowLevelDelta" "stale-offer boundary")
require_text("${quest_values}" "questFirstProgressionMaxAboveLevelDelta" "upper autonomous quest boundary")
require_text("${quest_values}" "(int32)level >= quest->GetQuestLevel()" "delta-four reject boundary")
require_text("${quest_values}" "quest->GetQuestLevel() >" "upper quest comparison")
require_text("${quest_travel}" "finished > 0" "turn-in-first ordering")
require_text("${quest_travel}" "TravelDestinationPurpose::QuestTaker) ? 1000000.0f" "unbounded completed-quest search")
require_text("${quest_travel}" "questFirstProgressionTraceTravelDecisions" "default-off travel provenance gate")
require_text("${quest_travel}" "[QuestFirstRoute]" "sanitized travel provenance record")
require_text("${quest_travel}" "state=selected" "selected-route provenance")
require_text("${quest_travel}" "state=rejected" "rejected-route provenance")
require_text("${quest_travel}" "cross_map_travelmgr" "transport provenance without a parallel navigator")
require_text("${quest_travel}" "travelmgr_route_validated" "route-validation provenance")
require_text("${quest_travel}" "no_active_route_candidate" "fail-closed route rejection")
require_text("${travel_mgr}" "IsProgressAwareTurnIn" "completed roster turn-in scope")
require_text("${travel_mgr}" "statusTime = IsProgressAwareTurnIn() ? 0" "no generic wall-clock expiry")
require_text("${travel_mgr}" "ObserveTurnInProgress" "progress-aware turn-in monitoring")
require_text("${travel_mgr}" "SuppressRouteAndCooldown" "bounded stale-route recovery")
require_text("${quest_travel}" "IsTurnInRouteSuppressed" "same-route temporary suppression")
require_text("${travel_mgr}" "bot->IsTaxiFlying()" "transport pause")
require_absent("${travel_mgr}" "TeleportTo(" "turn-in recovery teleport")
require_text("${set_home_action}" "state=homebind" "homebind transition provenance")
require_text("${set_home_action}" "old_map=%u old_zone=%u new_map=%u new_zone=%u" "homebind before-after location")
require_text("${quest_travel}" "preferLocalQuest" "local quest stickiness")
require_text("${quest_travel}" "hasActiveLocalQuestHub" "active local hub precedence")
require_text("${quest_travel}" "IsLocalActiveQuestHubDestination" "local quest hub predicate")
require_text("${quest_travel}" "QuestTravelDestination const*" "active quest destination type")
require_text("${quest_travel}" "questFirstProgressionLocalHubRadius" "bounded local hub radius")
require_text("${quest_travel}" "position->distance(WorldPosition(bot))" "local hub distance")
require_text("${quest_travel}" "destination->IsActive(bot, travelInfo)" "normal activation check for local precedence")
require_text("${quest_travel}" "RetireOneSafeStaleQuest" "safe retirement path")
require_text("${quest_travel}" "questFirstProgressionRetireBelowLevelDelta" "retire threshold")
require_text("${quest_travel}" "QUEST_TYPE_DUNGEON" "dungeon retirement protection")
require_text("${quest_travel}" "QUEST_TYPE_RAID" "raid retirement protection")
require_text("${quest_travel}" "ReqSourceId[objective]" "source item retirement protection")
require_text("${quest_travel}" "RemoveQuestAtSlot(slot)" "canonical safe quest removal")
require_text("${quest_travel}" "IsAutonomousRosterTravelBlocked" "master travel arbitration")
require_text("${quest_travel}" "IsAutonomousRosterTravelBlocked(ai, actionPurpose) && !event.getOwner()" "explicit master travel distinction")
require_text("${quest_travel}" "enforceGatherLeash" "gathering leash")
require_text("${quest_travel}" "> 25.0f" "25 yard gathering leash")
require_text("${quest_travel}" "!event.getOwner()" "manual travel owner distinction")
require_text("${follow_actions}" "QuestFirstRosterFollowingRealMaster" "follow arbitration")
require_text("${follow_actions}" "IsGatherTravelTarget" "moving-master gather arbitration")
require_text("${follow_actions}" "followTarget->IsMoving()" "moving-master gather cancellation")
require_text("${follow_actions}" "TravelDestinationPurpose::GatherSkinning" "skinning local-interaction preservation")
require_text("${follow_actions}" "LootObject loot" "existing loot follow gate")
message(STATUS "QUEST_FIRST_PROGRESSION_SOURCE_CONTRACT=PASS")
