# Hotfix 8.16a: ItemUsageValue must not copy "craft spells" or walk every recipe per item query.
file(READ "${PB_SOURCE_DIR}/strategy/values/ItemUsageValue.cpp" usage)
file(READ "${PB_SOURCE_DIR}/strategy/values/CraftValues.h" craft_h)
file(READ "${PB_SOURCE_DIR}/strategy/values/ValueContext.h" values)
string(FIND "${usage}" "AI_VALUE(std::vector<uint32>, \"craft spells\")" copy)
if (NOT copy EQUAL -1)
  message(FATAL_ERROR "craft reagent index: ItemUsageValue still copies craft spells")
endif()
foreach (needle
    "AI_VALUE(std::shared_ptr<const CraftReagentIndex>, \"craft reagent index\")"
    "index->find(proto->ItemId)")
  string(FIND "${usage}" "${needle}" at)
  if (at EQUAL -1)
    message(FATAL_ERROR "craft reagent index: missing ${needle}")
  endif()
endforeach()
string(FIND "${craft_h}" "CraftReagentIndexValue(PlayerbotAI* ai, std::string name = \"craft reagent index\", int checkInterval = 60)" value)
if (value EQUAL -1)
  message(FATAL_ERROR "craft reagent index: value must recalculate at most every 60 s")
endif()
string(FIND "${values}" "creators[\"craft reagent index\"]" reg)
if (reg EQUAL -1)
  message(FATAL_ERROR "craft reagent index: value not registered")
endif()
# Hotfix 8.16a: the rpg craft path ("craft random item") checks the bags under RealReagents.
file(READ "${PB_SOURCE_DIR}/strategy/actions/CastCustomSpellAction.cpp" cast)
foreach (needle
    "if (sPlayerbotAIConfig.professionUseRealReagents && IsRosterBotOnItsOwn(ai))"
    "uint32 const fromBags = HasCraftTools(pSpellInfo, bot) ? CraftableFromBags(pSpellInfo, bot) : 0;"
    "castCount = std::min(castCount, fromBags);")
  string(FIND "${cast}" "${needle}" at)
  if (at EQUAL -1)
    message(FATAL_ERROR "craft random item: missing ${needle}")
  endif()
endforeach()
string(FIND "${cast}" "if (sPlayerbotAIConfig.professionUseRealReagents && IsRosterBotOnItsOwn(ai))" guard)
string(FIND "${cast}" "cmd << \"castnc \";" queue)
if (guard GREATER queue)
  message(FATAL_ERROR "craft random item: the bag check must come before the castnc command")
endif()
message(STATUS "CRAFT_REAGENT_INDEX_CONTRACT=PASS")
