function(require_text text needle description)
  string(FIND "${text}" "${needle}" offset)
  if(offset EQUAL -1)
    message(FATAL_ERROR "Missing ${description}: ${needle}")
  endif()
endfunction()

file(READ "${PB_SOURCE_DIR}/strategy/values/ItemUsageValue.cpp" usage_source)
file(READ "${PB_SOURCE_DIR}/strategy/values/ItemUsageValue.h" usage_header)
file(READ "${PB_SOURCE_DIR}/strategy/actions/EquipAction.cpp" equip)
file(READ "${PB_SOURCE_DIR}/PlayerbotAIConfig.cpp" config_source)
file(READ "${PB_SOURCE_DIR}/aiplayerbot.conf.dist.in" config_template)

# #308: every equip decision returns through a reason code.
require_text("${usage_header}" "char const** reason = nullptr" "optional equip reason out-parameter")
string(FIND "${usage_source}" "ItemUsage ItemUsageValue::QueryItemUsageForEquip(" fn_start)
string(FIND "${usage_source}" "uint32 ItemUsageValue::GetSmallestBagSize(" fn_end)
if(fn_start EQUAL -1 OR fn_end EQUAL -1 OR fn_end LESS fn_start)
  message(FATAL_ERROR "Cannot locate QueryItemUsageForEquip body")
endif()
math(EXPR fn_len "${fn_end} - ${fn_start}")
string(SUBSTRING "${usage_source}" ${fn_start} ${fn_len} fn_body)
string(FIND "${fn_body}" "return ItemUsage::" bare_return)
if(NOT bare_return EQUAL -1)
  message(FATAL_ERROR "QueryItemUsageForEquip has a return without a reason code")
endif()
foreach(code "cannot_use" "cannot_equip_slot" "spec_rejects_weapon" "empty_slot" "upgrade" "not_better_than_equipped")
  require_text("${fn_body}" "\"${code}\"" "equip reason code")
endforeach()

require_text("${equip}" "sLog.outBasic(\"[ITEM EQUIP]" "visible equip decision line")
require_text("${equip}" "tracedDecisions.insert(key.str()).second" "once-per-decision throttle")
require_text("${equip}" "if (!sPlayerbotAIConfig.equipDiagnosticsTrace)" "diagnostics gated by config")
require_text("${config_source}" "\"AiPlayerbot.EquipDiagnostics.Trace\", false" "default-off diagnostics")
require_text("${config_template}" "AiPlayerbot.EquipDiagnostics.Trace = 0" "documented default")
