function(require_text text needle description)
  string(FIND "${text}" "${needle}" offset)
  if(offset EQUAL -1)
    message(FATAL_ERROR "Missing ${description}: ${needle}")
  endif()
endfunction()

file(READ "${PB_SOURCE_DIR}/PlayerbotAI.cpp" ai_source)
file(READ "${PB_SOURCE_DIR}/strategy/actions/ReleaseSpiritAction.h" release)
file(READ "${PB_SOURCE_DIR}/strategy/actions/ReviveFromCorpseAction.cpp" revive)
file(READ "${PB_SOURCE_DIR}/PlayerbotAIConfig.cpp" config_source)
file(READ "${PB_SOURCE_DIR}/aiplayerbot.conf.dist.in" config_template)

# #276 PR C: the wait for an active real-player master is bounded and configurable.
require_text("${ai_source}" "SET_AI_VALUE(time_t, \"death time\", time(nullptr));" "death time recorded on death")
require_text("${config_source}" "\"AiPlayerbot.DeadWaitForRealMasterSeconds\", 180" "configurable three-minute default")
require_text("${config_template}" "AiPlayerbot.DeadWaitForRealMasterSeconds = 180" "documented default")
require_text("${config_source}" "\"AiPlayerbot.DeadWaitForRealMasterInstanceSeconds\", 600" "configurable ten-minute dungeon/raid default")
require_text("${config_template}" "AiPlayerbot.DeadWaitForRealMasterInstanceSeconds = 600" "documented dungeon/raid default")
require_text("${release}" "master_wait::LimitFor(bot->GetMap()->IsDungeon()" "release uses the instance limit in dungeons and raids")
require_text("${revive}" "master_wait::LimitFor(corpseMap && corpseMap->IsDungeon()" "corpse run uses the corpse map's limit")
require_text("${release}" "action=release" "bounded release next to a master")
require_text("${revive}" "action=corpse_run" "bounded wait-for-resurrection gate")
require_text("${revive}" "action=spirit_healer reason=corpse_unreachable" "bounded unreachable-corpse fallback")
require_text("${revive}" "Say 'corpse run' to override." "unexpired wait keeps the existing gate")
