# twow-repo#524: one place for material reservations.
file(READ "${PB_SOURCE_DIR}/strategy/triggers/ProfessionUseTriggers.cpp" triggers)
file(READ "${PB_SOURCE_DIR}/strategy/values/ItemUsageValue.cpp" usage)
foreach (pair
    "triggers|material_reserve::UsableForRecipe(reagent, count, recipeSkill, mainNeed,"
    "triggers|TraceProfessionUse(botAi, \"reserve\", \"held\""
    "usage|material_reserve::MaySell(true, CurrentStacks(ai, proto), sPlayerbotAIConfig.professionUseReagentKeepStacks)")
  string(FIND "${pair}" "|" bar)
  string(SUBSTRING "${pair}" 0 ${bar} var)
  math(EXPR start "${bar} + 1")
  string(SUBSTRING "${pair}" ${start} -1 needle)
  string(FIND "${${var}}" "${needle}" at)
  if (at EQUAL -1)
    message(FATAL_ERROR "material reserve: missing ${needle}")
  endif()
endforeach()
# No second reserve rule outside the policy (core#307 TailoringClothReserve / ReserveApplies).
file(GLOB_RECURSE sources "${PB_SOURCE_DIR}/*.cpp" "${PB_SOURCE_DIR}/*.h")
foreach (source ${sources})
  if (source MATCHES "MaterialReservePolicy\\.h$")
    continue()
  endif()
  file(READ "${source}" text)
  foreach (forbidden "TailoringClothReserve" "ClothReserveApplies" "ReserveApplies(")
    string(FIND "${text}" "${forbidden}" at)
    if (NOT at EQUAL -1)
      message(FATAL_ERROR "material reserve: ${forbidden} outside MaterialReservePolicy.h (${source})")
    endif()
  endforeach()
endforeach()
# Hotfix 8.22a: the memory only keeps from sale, it never asks to buy (v34: 1637 buys an hour).
string(FIND "${usage}" "return stacks < 1 ? ItemUsage::ITEM_USAGE_SKILL : ItemUsage::ITEM_USAGE_KEEP;" buy_more)
if (NOT buy_more EQUAL -1)
  message(FATAL_ERROR "material reserve: the memory must not trigger buying")
endif()
string(FIND "${usage}" "return ItemUsage::ITEM_USAGE_KEEP;  // kept from sale, never \"buy more\"" keep_only)
if (keep_only EQUAL -1)
  message(FATAL_ERROR "material reserve: keep-from-sale branch missing")
endif()
string(FIND "${usage}" "if (keepCraft && !needItem)" after_walk)
string(FIND "${usage}" "needItem = (!ai->HasCheat(BotCheatMask::item) || keepCraft) && IsItemNeededForUsefullCraft(proto," walk)
if (after_walk LESS walk)
  message(FATAL_ERROR "material reserve: the memory check must come after the buying walk")
endif()
message(STATUS "MATERIAL_RESERVE_CONTRACT=PASS")
