# twow-repo#541 (audit A25, AiPlayerbot.Perf.PartyTargetMemo, default 0): the party-target values
# (PartyMemberValue and its 15 subclasses: to heal/protect/remove roots/dispel/resurrect/soulstone,
# ... without (my) aura, friendly unit without aura, tank without aura/lifebloom, with daybreak,
# without item/food/water) run with check interval 1, i.e. they recompute on every Get. With the
# switch on, a Get inside the bot's own Engine::DoNextAction window reuses the guid of the computation
# made earlier in the same window, re-checked against FindPartyMember's same-map guard (else it
# recomputes); Engine::ListenAndExecute advances the window after every Execute; outside the window
# and on any other thread Epoch() is 0 and the value recomputes as before. "party member to
# soulstone" (randomised D20 stagger) is never memoized. Switch off = the old Get, unchanged.
# Window semantics themselves: t/value_memo_window_tests.cpp.
# Every check returns "" when it holds, else the reason; the negative probes reuse the checks.

if(NOT DEFINED PB_SOURCE_DIR)
  message(FATAL_ERROR "PB_SOURCE_DIR is required (pass -DPB_SOURCE_DIR=<module>/src/playerbot)")
endif()

set(TAG "#541 A25 party-target memo")
set(GATE "sPlayerbotAIConfig.perfPartyTargetMemo")
set(SCOPE "ValueMemoWindowScope const valueMemoScope(${GATE} ? &aiObjectContext->GetValueMemoWindow() : nullptr);")
set(ADVANCE "if (${GATE})\n        aiObjectContext->GetValueMemoWindow().Advance();\n    return actionExecuted;")
set(OFF_PATH "if (!${GATE})\n        return UnitCalculatedValue::Get();")
set(NO_MEMO "if (!MemoAllowed())\n        return UnitCalculatedValue::Get();")
set(HIT "if (epoch && epoch == memoEpoch)")
set(RESOLVE "Unit* const unit = m_guid.IsEmpty() ? nullptr : ai->GetUnit(m_guid);")
set(SAME_MAP "if (m_guid.IsEmpty() || (unit && unit->IsInWorld() && unit->FindMap() && unit->FindMap() == bot->FindMap()))")
set(HIT_RETURN "value = unit;\n            return value;")
set(SOULSTONE_OPT_OUT "bool MemoAllowed() const override { return false; }")
set(NOT_OWNER "if (owner.load(std::memory_order_acquire) != std::this_thread::get_id())")

function(read_source path out_var)
  if(NOT EXISTS "${PB_SOURCE_DIR}/${path}")
    message(FATAL_ERROR "${TAG}: missing source ${path}")
  endif()
  file(READ "${PB_SOURCE_DIR}/${path}" text)
  string(REPLACE "\r" "" text "${text}")
  set(${out_var} "${text}" PARENT_SCOPE)
endfunction()

# Text from start_marker up to the first end_marker after it; "" when a marker is missing.
function(region text start_marker end_marker out_var)
  set(${out_var} "" PARENT_SCOPE)
  string(FIND "${text}" "${start_marker}" start)
  if(start EQUAL -1)
    return()
  endif()
  string(SUBSTRING "${text}" ${start} -1 rest)
  string(FIND "${rest}" "${end_marker}" length)
  if(length EQUAL -1)
    return()
  endif()
  string(SUBSTRING "${rest}" 0 ${length} body)
  set(${out_var} "${body}" PARENT_SCOPE)
endfunction()

# Function body from the signature up to the first column-0 closing brace.
function(function_body text signature out_var)
  region("${text}" "${signature}" "\n}\n" body)
  set(${out_var} "${body}" PARENT_SCOPE)
endfunction()

function(check_switch config_h config_cpp conf_dist out_var)
  set(err "")
  string(FIND "${config_h}" "uint32 aiDelayJitterPct = 0;" anchor)
  string(FIND "${config_h}" "bool perfPartyTargetMemo = false;" a)
  string(FIND "${config_cpp}" "perfPartyTargetMemo = config.GetBoolDefault(\"AiPlayerbot.Perf.PartyTargetMemo\", false);" b)
  string(FIND "${conf_dist}" "\nAiPlayerbot.Perf.PartyTargetMemo = 0\n" c)
  if(a EQUAL -1)
    set(err "member perfPartyTargetMemo default false missing")
  elseif(anchor EQUAL -1 OR NOT anchor LESS a)
    set(err "member must come after the #541 switch aiDelayJitterPct")
  elseif(b EQUAL -1)
    set(err "config read with default false missing")
  elseif(c EQUAL -1)
    set(err "documented key AiPlayerbot.Perf.PartyTargetMemo = 0 missing in aiplayerbot.conf.dist.in")
  endif()
  set(${out_var} "${err}" PARENT_SCOPE)
endfunction()

function(check_window window_h context_h out_var)
  set(err "")
  string(FIND "${window_h}" "class ValueMemoWindow\n" cls)
  region("${window_h}" "uint32_t Epoch() const" "\n        }\n" epoch_body)
  string(FIND "${epoch_body}" "${NOT_OWNER}" not_owner)
  string(FIND "${epoch_body}" "return 0;" ret0)
  region("${window_h}" "void Close()" "\n        }\n" close_body)
  string(FIND "${close_body}" "${NOT_OWNER}" close_owner)
  string(FIND "${close_body}" "Advance();" close_adv)
  region("${window_h}" "void Open()" "\n        }\n" open_body)
  string(FIND "${open_body}" "Advance();" open_adv)
  region("${window_h}" "explicit ValueMemoWindowScope(ValueMemoWindow* w)" "\n" ctor)
  region("${window_h}" "~ValueMemoWindowScope()" "\n" dtor)
  string(FIND "${ctor}" "window->Open();" ctor_open)
  string(FIND "${dtor}" "window->Close();" dtor_close)
  string(FIND "${window_h}" "static " st)
  string(FIND "${window_h}" "mutex" mx)
  string(FIND "${window_h}" "std::atomic<std::thread::id> owner" own)
  string(FIND "${context_h}" "#include \"ValueMemoWindow.h\"" inc)
  string(FIND "${context_h}" "ValueMemoWindow& GetValueMemoWindow() { return valueMemoWindow; }" acc)
  string(FIND "${context_h}" "ValueMemoWindow valueMemoWindow;" mem)
  if(cls EQUAL -1)
    set(err "class ValueMemoWindow missing")
  elseif(not_owner EQUAL -1 OR ret0 EQUAL -1 OR NOT not_owner LESS ret0)
    set(err "Epoch() must return 0 for a thread that does not own the window")
  elseif(own EQUAL -1)
    set(err "window owner must be an atomic thread id")
  elseif(close_owner EQUAL -1 OR close_adv EQUAL -1 OR open_adv EQUAL -1)
    set(err "Open and Close (owner only) must advance the epoch")
  elseif(ctor_open EQUAL -1 OR dtor_close EQUAL -1)
    set(err "ValueMemoWindowScope must Open in its constructor and Close in its destructor")
  elseif(NOT st EQUAL -1)
    set(err "no static state allowed in ValueMemoWindow.h")
  elseif(NOT mx EQUAL -1)
    set(err "no mutex in ValueMemoWindow.h (per-bot, owner-thread only)")
  elseif(inc EQUAL -1 OR acc EQUAL -1 OR mem EQUAL -1)
    set(err "AiObjectContext must own one ValueMemoWindow per bot with an accessor")
  endif()
  set(${out_var} "${err}" PARENT_SCOPE)
endfunction()

function(check_engine engine_cpp reaction_cpp out_var)
  set(err "")
  function_body("${engine_cpp}" "bool Engine::DoNextAction(Unit* unit, int depth, bool minimal, bool isStunned)" dna)
  function_body("${engine_cpp}" "bool Engine::ListenAndExecute(Action* action, Event& event)" lae)
  string(FIND "${dna}" "${SCOPE}" scope)
  string(FIND "${dna}" "ProcessTriggers(minimal);" trig)
  string(FIND "${lae}" "action->Execute(event)" exec)
  string(FIND "${lae}" "${ADVANCE}" adv)
  string(FIND "${engine_cpp}" "ValueMemoWindowScope" scope_all)
  string(FIND "${engine_cpp}" "ValueMemoWindowScope" scope_last REVERSE)
  string(FIND "${reaction_cpp}" "ValueMemoWindow" reaction)
  if(dna STREQUAL "" OR lae STREQUAL "")
    set(err "Engine::DoNextAction or Engine::ListenAndExecute not found")
  elseif(scope EQUAL -1)
    set(err "DoNextAction must open the window through the switch-gated scope")
  elseif(trig EQUAL -1 OR NOT scope LESS trig)
    set(err "the window must be open before ProcessTriggers")
  elseif(NOT scope_all EQUAL scope_last)
    set(err "only DoNextAction may open a window")
  elseif(NOT reaction EQUAL -1)
    set(err "the reaction engine runs outside any window and must not open or advance one")
  elseif(exec EQUAL -1 OR adv EQUAL -1 OR NOT exec LESS adv)
    set(err "ListenAndExecute must advance the window (gated) after Execute, right before its return")
  endif()
  set(${out_var} "${err}" PARENT_SCOPE)
endfunction()

function(check_value pm_cpp pm_h soulstone_h out_var)
  set(err "")
  function_body("${pm_cpp}" "Unit* PartyMemberValue::Get()" get)
  function_body("${pm_cpp}" "void PartyMemberValue::Set(Unit* unit)" set_body)
  function_body("${pm_cpp}" "void PartyMemberValue::Reset()" reset)
  string(FIND "${get}" "${OFF_PATH}" off)
  string(FIND "${get}" "${NO_MEMO}" no_memo)
  string(FIND "${get}" "GetValueMemoWindow().Epoch()" ep)
  string(FIND "${get}" "${HIT}" hit)
  string(FIND "${get}" "${RESOLVE}" res)
  string(FIND "${get}" "${SAME_MAP}" same_map)
  string(FIND "${get}" "${HIT_RETURN}" hit_ret)
  string(FIND "${get}" "GetBotAI(" foreign)
  string(FIND "${get}" "memoEpoch = epoch;" store)
  string(FIND "${set_body}" "memoEpoch = 0;" s0)
  string(FIND "${set_body}" "UnitCalculatedValue::Set(unit);" s1)
  string(FIND "${reset}" "memoEpoch = 0;" r0)
  string(FIND "${reset}" "UnitCalculatedValue::Reset();" r1)
  string(FIND "${pm_h}" "Unit* Get() override;" h1)
  string(FIND "${pm_h}" "void Set(Unit* unit) override;" h2)
  string(FIND "${pm_h}" "void Reset() override;" h3)
  string(FIND "${pm_h}" "uint32 memoEpoch = 0;" h4)
  string(FIND "${pm_h}" "virtual bool MemoAllowed() const { return true; }" h5)
  string(FIND "${soulstone_h}" "${SOULSTONE_OPT_OUT}" stone)
  if(get STREQUAL "" OR set_body STREQUAL "" OR reset STREQUAL "")
    set(err "PartyMemberValue::Get/Set/Reset definitions missing")
  elseif(h1 EQUAL -1 OR h2 EQUAL -1 OR h3 EQUAL -1 OR h4 EQUAL -1 OR h5 EQUAL -1)
    set(err "PartyMemberValue.h must declare Get/Set/Reset overrides, MemoAllowed and memoEpoch = 0")
  elseif(off EQUAL -1 OR ep EQUAL -1 OR NOT off LESS ep)
    set(err "switch off must return the old UnitCalculatedValue::Get() before any window read")
  elseif(no_memo EQUAL -1 OR NOT no_memo LESS ep)
    set(err "a value with MemoAllowed() == false must recompute before any window read")
  elseif(stone EQUAL -1)
    set(err "party member to soulstone (randomised D20 stagger) must opt out of the memo")
  elseif(hit EQUAL -1)
    set(err "memo hit must require a non-zero epoch equal to the stored one")
  elseif(res EQUAL -1 OR NOT hit LESS res)
    set(err "a memo hit must resolve the unit again through ai->GetUnit(m_guid)")
  elseif(same_map EQUAL -1 OR NOT res LESS same_map)
    set(err "a memo hit must re-check the unit is in world on the bot's map (FindPartyMember guard)")
  elseif(hit_ret EQUAL -1 OR NOT same_map LESS hit_ret)
    set(err "only a memo hit that passed the same-map re-check may return the kept unit")
  elseif(store EQUAL -1 OR NOT hit_ret LESS store)
    set(err "Get must remember the epoch of its computation (after the hit block)")
  elseif(NOT foreign EQUAL -1)
    set(err "PartyMemberValue::Get must not read another bot's values")
  elseif(s0 EQUAL -1 OR s1 EQUAL -1 OR NOT s0 LESS s1)
    set(err "Set must drop the memo before storing")
  elseif(r0 EQUAL -1 OR r1 EQUAL -1 OR NOT r0 LESS r1)
    set(err "Reset must drop the memo")
  endif()
  set(${out_var} "${err}" PARENT_SCOPE)
endfunction()

read_source("PlayerbotAIConfig.h" config_h)
read_source("PlayerbotAIConfig.cpp" config_cpp)
read_source("aiplayerbot.conf.dist.in" conf_dist)
read_source("strategy/ValueMemoWindow.h" window_h)
read_source("strategy/AiObjectContext.h" context_h)
read_source("strategy/Engine.cpp" engine_cpp)
read_source("strategy/ReactionEngine.cpp" reaction_cpp)
read_source("strategy/values/PartyMemberValue.cpp" pm_cpp)
read_source("strategy/values/PartyMemberValue.h" pm_h)
read_source("strategy/values/PartyMemberToSoulstone.h" soulstone_h)

# Positive pass.
check_switch("${config_h}" "${config_cpp}" "${conf_dist}" e)
if(e)
  message(FATAL_ERROR "${TAG}: ${e}")
endif()
check_window("${window_h}" "${context_h}" e)
if(e)
  message(FATAL_ERROR "${TAG}: ${e}")
endif()
check_engine("${engine_cpp}" "${reaction_cpp}" e)
if(e)
  message(FATAL_ERROR "${TAG}: ${e}")
endif()
check_value("${pm_cpp}" "${pm_h}" "${soulstone_h}" e)
if(e)
  message(FATAL_ERROR "${TAG}: ${e}")
endif()

# Negative probes: each mutation must change the text and be caught, otherwise the scan is broken.
set(caught 0)
macro(expect_caught original_var what)
  if(probe STREQUAL "${${original_var}}")
    message(FATAL_ERROR "${TAG}: negative probe did not apply: ${what}")
  endif()
  if(NOT e)
    message(FATAL_ERROR "${TAG}: negative probe not caught: ${what} - the scan is broken")
  endif()
  math(EXPR caught "${caught} + 1")
endmacro()

# 1-3: switch must default to off in code, config read and documentation.
string(REPLACE "bool perfPartyTargetMemo = false;" "bool perfPartyTargetMemo = true;" probe "${config_h}")
check_switch("${probe}" "${config_cpp}" "${conf_dist}" e)
expect_caught(config_h "member default true")
string(REPLACE "\"AiPlayerbot.Perf.PartyTargetMemo\", false)" "\"AiPlayerbot.Perf.PartyTargetMemo\", true)" probe "${config_cpp}")
check_switch("${config_h}" "${probe}" "${conf_dist}" e)
expect_caught(config_cpp "GetBoolDefault true")
string(REPLACE "\nAiPlayerbot.Perf.PartyTargetMemo = 0\n" "\nAiPlayerbot.Perf.PartyTargetMemo = 1\n" probe "${conf_dist}")
check_switch("${config_h}" "${config_cpp}" "${probe}" e)
expect_caught(conf_dist "documented 1")

# 4: Execute no longer advances the window (stale target after a cast).
string(REPLACE "${ADVANCE}" "return actionExecuted;" probe "${engine_cpp}")
check_engine("${probe}" "${reaction_cpp}" e)
expect_caught(engine_cpp "no Advance after Execute")

# 5: window opened regardless of the switch.
string(REPLACE "${SCOPE}" "ValueMemoWindowScope const valueMemoScope(&aiObjectContext->GetValueMemoWindow());" probe "${engine_cpp}")
check_engine("${probe}" "${reaction_cpp}" e)
expect_caught(engine_cpp "ungated window")

# 6: window opened after the triggers ran (trigger computations not shared).
string(REPLACE "    ${SCOPE}\n" "" tmp "${engine_cpp}")
string(REPLACE "    ProcessTriggers(minimal);\n" "    ProcessTriggers(minimal);\n    ${SCOPE}\n" probe "${tmp}")
check_engine("${probe}" "${reaction_cpp}" e)
expect_caught(engine_cpp "scope after ProcessTriggers")

# 7: the reaction engine opens a window (reactions must stay outside).
string(REPLACE "bool ReactionEngine::ListenAndExecute(Action* action, Event& event)\n{\n"
  "bool ReactionEngine::ListenAndExecute(Action* action, Event& event)\n{\n    ValueMemoWindowScope const s(&aiObjectContext->GetValueMemoWindow());\n" probe "${reaction_cpp}")
check_engine("${engine_cpp}" "${probe}" e)
expect_caught(reaction_cpp "reaction engine opens a window")

# 8: switch-off path removed (off would no longer be the old code).
string(REPLACE "${OFF_PATH}" "" probe "${pm_cpp}")
check_value("${probe}" "${pm_h}" "${soulstone_h}" e)
expect_caught(pm_cpp "no switch-off fast path")

# 9: memo hit without the epoch-zero guard (outside the window every read would hit).
string(REPLACE "${HIT}" "if (epoch == memoEpoch)" probe "${pm_cpp}")
check_value("${probe}" "${pm_h}" "${soulstone_h}" e)
expect_caught(pm_cpp "hit without non-zero epoch")

# 10: memo hit returns the stored raw pointer instead of resolving the guid.
string(REPLACE "${RESOLVE}" "Unit* const unit = value;" probe "${pm_cpp}")
check_value("${probe}" "${pm_h}" "${soulstone_h}" e)
expect_caught(pm_cpp "raw pointer on hit")

# 11: memo hit without the same-map re-check (a member on another map thread reaches IsTank/IsHeal).
string(REPLACE "${SAME_MAP}" "if (true)" probe "${pm_cpp}")
check_value("${probe}" "${pm_h}" "${soulstone_h}" e)
expect_caught(pm_cpp "same-map re-check on memo hit removed")

# 12: the randomised soulstone value is memoized (no opt-out override).
string(REPLACE "        ${SOULSTONE_OPT_OUT}\n" "" probe "${soulstone_h}")
check_value("${pm_cpp}" "${pm_h}" "${probe}" e)
expect_caught(soulstone_h "soulstone opt-out removed")

# 13: Get ignores MemoAllowed().
string(REPLACE "${NO_MEMO}" "" probe "${pm_cpp}")
check_value("${probe}" "${pm_h}" "${soulstone_h}" e)
expect_caught(pm_cpp "MemoAllowed gate removed")

# 14: Set keeps the memo.
string(REPLACE "    memoEpoch = 0;\n    UnitCalculatedValue::Set(unit);" "    UnitCalculatedValue::Set(unit);" probe "${pm_cpp}")
check_value("${probe}" "${pm_h}" "${soulstone_h}" e)
expect_caught(pm_cpp "Set keeps memo")

# 15: Reset keeps the memo.
string(REPLACE "    memoEpoch = 0;\n    UnitCalculatedValue::Reset();" "    UnitCalculatedValue::Reset();" probe "${pm_cpp}")
check_value("${probe}" "${pm_h}" "${soulstone_h}" e)
expect_caught(pm_cpp "Reset keeps memo")

# 16: foreign threads would see the owner's epoch.
string(REPLACE "${NOT_OWNER}\n                return 0;\n" "" probe "${window_h}")
check_window("${probe}" "${context_h}" e)
expect_caught(window_h "no owner-thread check in Epoch()")

# 17: a static (process-wide) epoch instead of per-bot state.
string(REPLACE "std::atomic<uint32_t> epoch{ 0 };" "static inline std::atomic<uint32_t> epoch{ 0 };" probe "${window_h}")
check_window("${probe}" "${context_h}" e)
expect_caught(window_h "static epoch")

# 18: the scope no longer closes the window when DoNextAction returns.
string(REPLACE "~ValueMemoWindowScope() { if (window) window->Close(); }" "~ValueMemoWindowScope() {}" probe "${window_h}")
check_window("${probe}" "${context_h}" e)
expect_caught(window_h "scope destructor without Close")

# 19: Close no longer advances the epoch.
region("${window_h}" "void Close()" "\n        }\n" close_body)
string(REPLACE "Advance();" "" close_mut "${close_body}")
string(REPLACE "${close_body}" "${close_mut}" probe "${window_h}")
check_window("${probe}" "${context_h}" e)
expect_caught(window_h "Close without Advance")

message(STATUS "${TAG}: source contract OK (${caught} negative probes caught)")
