function(require_text text needle description)
  string(FIND "${text}" "${needle}" offset)
  if(offset EQUAL -1)
    message(FATAL_ERROR "Missing ${description}: ${needle}")
  endif()
endfunction()

function(reject_text text needle description)
  string(FIND "${text}" "${needle}" offset)
  if(NOT offset EQUAL -1)
    message(FATAL_ERROR "Forbidden ${description}: ${needle}")
  endif()
endfunction()

file(READ "${PB_SOURCE_DIR}/PersistentRosterProfessionTrainingPolicy.h" policy)
file(READ "${PB_SOURCE_DIR}/PlayerbotAIConfig.h" config_header)
file(READ "${PB_SOURCE_DIR}/PlayerbotAIConfig.cpp" config_source)
file(READ "${PB_SOURCE_DIR}/aiplayerbot.conf.dist.in" config_template)
file(READ "${PB_SOURCE_DIR}/strategy/actions/TrainerAction.h" trainer_header)
file(READ "${PB_SOURCE_DIR}/strategy/actions/TrainerAction.cpp" trainer)
file(READ "${PB_SOURCE_DIR}/strategy/actions/RosterProfessionTrainerAction.cpp" roster_trainer)
file(READ "${PB_SOURCE_DIR}/strategy/actions/RpgSubActions.h" rpg)
file(READ "${PB_SOURCE_DIR}/strategy/actions/ActionContext.h" actions)
file(READ "${PB_SOURCE_DIR}/strategy/values/TrainerValues.cpp" trainer_values)
file(READ "${PB_SOURCE_DIR}/strategy/values/TravelValues.cpp" travel_values)
file(READ "${PB_SOURCE_DIR}/strategy/triggers/RpgTriggers.cpp" rpg_triggers)

require_text("${policy}" "constexpr std::uint32_t kSurvival = 142;" "Turtle Survival skill identity")
require_text("${policy}" "profession::Contains(pair, skill) || IsSecondarySkill(skill)" "pair allowlist")
require_text("${policy}" "IsEligibleProfessionTraining" "profession policy")
require_text("${policy}" "MayRequestRemoteTrainerTravel" "remote profession-travel policy")
require_text("${policy}" "return !(persistentRosterMember && tradeTrainer);" "remote profession-travel denial")

require_text("${config_header}" "professionTrainingFreeForPersistentRoster" "free profile config member")
require_text("${config_header}" "professionTrainingLocalTrainerRadius" "local trainer-radius configuration member")
require_text("${config_header}" "professionTrainingTraceCooldownSeconds" "trace cooldown configuration member")
require_text("${config_source}" "std::max<uint32>(1, config.GetIntDefault(\"AiPlayerbot.ProfessionTraining.StartLevel\", 1))" "level-one start configuration")
require_text("${config_template}" "AiPlayerbot.ProfessionTraining.FreeForPersistentRoster = 0" "disabled default")
require_text("${config_template}" "AiPlayerbot.ProfessionTraining.Trace = 0" "disabled trace default")
require_text("${config_template}" "AiPlayerbot.ProfessionTraining.LocalTrainerRadius = 120" "local trainer-radius default")
require_text("${config_template}" "AiPlayerbot.ProfessionTraining.TraceCooldownSeconds = 300" "trace cooldown default")

require_text("${trainer_header}" "virtual bool AllowsTradeSkillTrainer" "generic tradeskill opt-in hook")
require_text("${trainer_header}" "virtual bool AllowsTrainerSpell" "per-spell allowlist hook")
require_text("${trainer}" "TRAINER_TYPE_TRADESKILLS && !AllowsTradeSkillTrainer(creature)" "generic tradeskill refusal retained")
require_text("${trainer}" "if (!AllowsTrainerSpell(creature, tSpell))" "trainer spell filtering")
require_text("${trainer}" "!UsesFreeTraining()" "scoped no-charge path")

require_text("${roster_trainer}" "IsPersistentRosterMember(bot->GetGUIDLow())" "persistent roster gate")
require_text("${roster_trainer}" "GetProfessionPair(bot->GetGUIDLow())" "persisted pair lookup")
require_text("${roster_trainer}" "GetTrainerSpellState" "normal trainer state is retained")
require_text("${roster_trainer}" "EffectMiscValue[1]" "initial profession skill resolution")
require_text("${roster_trainer}" "IsWithinLocalTrainerRadius" "local trainer-radius gate")
require_text("${roster_trainer}" "TraceDecision" "throttled trainer decision diagnostics")
require_text("${roster_trainer}" "sLog.outBasic(\"[PersistentRosterProfessionTraining]" "trace visible at LogLevel 1")
require_text("${roster_trainer}" "ShouldEmitTrace" "trace cooldown gate")
reject_text("${roster_trainer}" "outDebug" "trace hidden at live LogLevel 1")
reject_text("${roster_trainer}" "SetSkill(" "direct skill grant")
reject_text("${roster_trainer}" "learnSpell(" "direct spell grant")
reject_text("${roster_trainer}" "SetProfessionPair(" "plan overwrite")
reject_text("${roster_trainer}" "CharacterDatabase" "SQL path")

require_text("${trainer_values}" "isInitialProfession" "initial profession classification")
require_text("${trainer_values}" "IsEligibleProfessionTraining" "roster profession allowlist")
require_text("${trainer_values}" "IsPersistentRosterMember(bot->GetGUIDLow())" "roster trainable-spell gate")
require_text("${trainer_values}" "persistentRosterBot && !allowedRosterProfession" "all-level roster trade fail-closed gate")
require_text("${travel_values}" "UsesFreePersistentRosterProfessionTraining" "scoped free training travel policy")
require_text("${travel_values}" "!freePersistentRosterProfessionTraining" "generic budget guard remains")
require_text("${travel_values}" "if (ai->HasRealPlayerMaster())" "master-led autonomous travel block")
require_text("${travel_values}" "MayRequestRemoteTrainerTravel" "roster remote trainer-travel block")
require_text("${rpg}" "return \"roster profession trainer\";" "dedicated roster action route")
require_text("${actions}" "creators[\"roster profession trainer\"]" "dedicated action registration")

require_text("${rpg_triggers}" "RosterProfessionTrainerAction::PlannedPairFor(bot)" "plan-aware RPG trainer trigger")
require_text("${rpg_triggers}" "RosterProfessionTrainerAction::GetTrainerSpellSkill(tSpell)" "trigger uses the action's skill identity")
require_text("${rpg_triggers}" "!rosterFreeTraining && cost >" "trigger honours the free-training switch")
require_text("${rpg_triggers}" "\"no_planned_trainable_spell\"" "trigger rejection diagnostics")
require_text("${config_template}" "AiPlayerbot.RpgDistance" "locality documented against the generic RPG reach")

file(READ "${PB_SOURCE_DIR}/strategy/values/PossibleRpgTargetsValue.cpp" rpg_targets)
file(READ "${PB_SOURCE_DIR}/strategy/actions/ChooseRpgTargetAction.cpp" choose_rpg)
require_text("${rpg_targets}" "info->TrainerType == TRAINER_TYPE_TRADESKILLS" "local reach lists tradeskill trainers only")
require_text("${choose_rpg}" "RosterProfessionTrainerAction::PlannedPairFor(bot)" "wider reach only for planned roster bots")
require_text("${choose_rpg}" "AI_VALUE(std::list<ObjectGuid>, \"roster profession trainers\")" "local trainer candidates")
require_text("${choose_rpg}" "!rosterProfessionTrainers.count(guid)" "trainers survive the per-pass check cap")
