# twow-repo#541 (audit A32, behaviour-changing, owner A/B 09.10.2026): behind
# AiPlayerbot.PossibleTargetsSharedSearch (default 0) the unqualified "possible targets" variants of a bot
# WITHOUT a group filter the bot's OWN unfiltered snapshot "possible targets::{<sight>:1}" (read by
# AttackersValue::AddTargetsOf) instead of searching the grid again. Every snapshot unit passes the grid
# search's own check (AnyUnfriendlyUnitInObjectRangeCheck: CanSeeInWorld, alive, same map instance, in
# range, not friendly) and AcceptUnit again. Grouped bots, the snapshot itself and other ranges keep the
# old search. Switch 0 = old path verbatim.
# Inputs: PB_SOURCE_DIR (src/playerbot), CORE_SOURCE_DIR (core root, for the grid check it reuses).

function(read_source path out_var)
  file(READ "${PB_SOURCE_DIR}/${path}" text)
  string(REPLACE "\r" "" text "${text}")
  set(${out_var} "${text}" PARENT_SCOPE)
endfunction()

function(require_text text needle description)
  string(FIND "${text}" "${needle}" offset)
  if(offset EQUAL -1)
    message(FATAL_ERROR "#541 A32: missing ${description}: ${needle}")
  endif()
endfunction()

function(require_order text first second description)
  string(FIND "${text}" "${first}" a)
  string(FIND "${text}" "${second}" b)
  if(a EQUAL -1 OR b EQUAL -1 OR NOT a LESS b)
    message(FATAL_ERROR "#541 A32: order ${description}: '${first}' must come before '${second}'")
  endif()
endfunction()

function(function_body text signature out_var)
  string(FIND "${text}" "${signature}" start)
  if(start EQUAL -1)
    message(FATAL_ERROR "#541 A32: function not found: ${signature}")
  endif()
  string(SUBSTRING "${text}" ${start} -1 rest)
  string(FIND "${rest}" "\n}\n" end)
  if(end EQUAL -1)
    message(FATAL_ERROR "#541 A32: end of function not found: ${signature}")
  endif()
  string(SUBSTRING "${rest}" 0 ${end} body)
  set(${out_var} "${body}" PARENT_SCOPE)
endfunction()

function(a32_need block needle errors_var)
  string(FIND "${block}" "${needle}" o)
  if(o EQUAL -1)
    set(${errors_var} "${${errors_var}} | missing: ${needle}" PARENT_SCOPE)
  endif()
endfunction()

function(a32_forbid block needle errors_var)
  string(FIND "${block}" "${needle}" o)
  if(NOT o EQUAL -1)
    set(${errors_var} "${${errors_var}} | forbidden: ${needle}" PARENT_SCOPE)
  endif()
endfunction()

# "" when <body> is a valid A32 Calculate body, otherwise the reasons.
function(check_shared_search body out_var)
  set(err "")
  set(gate "if (sPlayerbotAIConfig.possibleTargetsSharedSearch && qualifier.empty() && !bot->GetGroup())")
  set(legacy "std::list<Unit*> targets;")
  string(FIND "${body}" "${gate}" g)
  string(FIND "${body}" "${legacy}" l)
  if(g EQUAL -1 OR l EQUAL -1 OR NOT g LESS l)
    set(${out_var} "gate missing or not before the legacy search" PARENT_SCOPE)
    return()
  endif()
  # The qualifier block must stay first (the snapshot reads its range/ignore-validate there).
  string(FIND "${body}" "shouldIgnoreValidate = Qualified::getMultiQualifierInt(qualifier, 1, \":\");" q)
  if(q EQUAL -1 OR NOT q LESS g)
    set(err "${err} | qualifier block missing or after the gate")
  endif()
  math(EXPR len "${l} - ${g}")
  string(SUBSTRING "${body}" ${g} ${len} block)
  a32_need("${block}" "int32 const sharedRange = (int32)sPlayerbotAIConfig.sightDistance;" err)
  a32_need("${block}" "if (sharedRange > 0 && range == (float)sharedRange)" err)
  a32_need("${block}" "const std::vector<std::string> sharedQualifiers = { std::to_string(sharedRange), std::to_string(true) };" err)
  a32_need("${block}" "context->GetValue<std::list<ObjectGuid>>(\"possible targets\", Qualified::MultiQualify(sharedQualifiers, \":\"))" err)
  a32_need("${block}" "if (shared)" err)
  a32_need("${block}" "const std::list<ObjectGuid> sharedGuids = shared->Get();" err)
  a32_need("${block}" "MaNGOS::AnyUnfriendlyUnitInObjectRangeCheck inRange(bot, range);" err)
  a32_need("${block}" "Unit* unit = ai->GetUnit(guid);" err)
  a32_need("${block}" "if (unit && inRange(unit) && AcceptUnit(unit))" err)
  a32_need("${block}" "return results;" err)
  # no second search, no other bot's values, no static cache, no locks, no filtered/other key
  a32_forbid("${block}" "FindPossibleTargets" err)
  a32_forbid("${block}" "Cell::Visit" err)
  a32_forbid("${block}" "GetBotAI(" err)
  a32_forbid("${block}" "PAI_VALUE" err)
  a32_forbid("${block}" "static " err)
  a32_forbid("${block}" "thread_local" err)
  a32_forbid("${block}" "mutex" err)
  a32_forbid("${block}" "std::to_string(false)" err)
  a32_forbid("${block}" "LazyGet" err)
  # legacy path (snapshot itself, grouped bots, switch off) unchanged
  a32_need("${body}" "FindPossibleTargets(bot, targets, rangeCheck);" err)
  a32_need("${body}" "if (unit && (shouldIgnoreValidate || AcceptUnit(unit)))" err)
  a32_need("${body}" "results.push_back(unit->GetObjectGuid());" err)
  set(${out_var} "${err}" PARENT_SCOPE)
endfunction()

read_source("strategy/values/PossibleTargetsValue.cpp" ptv)
read_source("strategy/values/AttackersValue.cpp" att_cpp)
read_source("strategy/values/AttackersValue.h" att_h)
read_source("strategy/values/ValueContext.h" vctx)
read_source("strategy/values/NearestUnitsValue.h" nuv)
read_source("strategy/Value.h" value_h)
read_source("PlayerbotAIConfig.h" config_h)
read_source("PlayerbotAIConfig.cpp" config_cpp)
read_source("aiplayerbot.conf.dist.in" conf_dist)

if(NOT DEFINED CORE_SOURCE_DIR OR CORE_SOURCE_DIR STREQUAL "")
  get_filename_component(CORE_SOURCE_DIR "${PB_SOURCE_DIR}/../../../.." ABSOLUTE)
endif()
file(READ "${CORE_SOURCE_DIR}/src/game/Maps/GridNotifiers.h" grid_h)
string(REPLACE "\r" "" grid_h "${grid_h}")

# 1. Switch: default off in code, documented 0, appended after the #541 block.
require_text("${config_h}" "bool possibleTargetsSharedSearch = false;  // twow-repo#541 (audit A32)" "switch member default off")
require_order("${config_h}" "uint32 aiDelayJitterPct = 0;" "bool possibleTargetsSharedSearch = false;" "after the #541 switches")
require_text("${config_cpp}" "possibleTargetsSharedSearch = config.GetBoolDefault(\"AiPlayerbot.PossibleTargetsSharedSearch\", false);" "switch read default 0")
require_order("${config_cpp}" "aiDelayJitterPct = std::min<uint32>(" "possibleTargetsSharedSearch = config.GetBoolDefault(" "read next to the #541 switches")
require_text("${conf_dist}" "\nAiPlayerbot.PossibleTargetsSharedSearch = 0\n" "documented key = 0")
require_text("${conf_dist}" "# twow-repo#541 (audit A32, BEHAVIOUR CHANGE" "behaviour-change note")
require_order("${conf_dist}" "AiPlayerbot.AiDelayJitterPct = 0" "AiPlayerbot.PossibleTargetsSharedSearch = 0" "documented near the #541 switches")

# 2. Calculate body.
function_body("${ptv}" "std::list<ObjectGuid> PossibleTargetsValue::Calculate()" calc)
check_shared_search("${calc}" real_err)
if(NOT real_err STREQUAL "")
  message(FATAL_ERROR "#541 A32: Calculate does not match the contract:${real_err}")
endif()
# The switch is read only in this file's gate (one use), FindUnits/AcceptUnit unchanged.
require_text("${ptv}" "void PossibleTargetsValue::FindUnits(std::list<Unit*> &targets)\n{\n    FindPossibleTargets(bot, targets, range);\n}" "FindUnits unchanged")
require_text("${ptv}" "bool PossibleTargetsValue::AcceptUnit(Unit* unit)\n{\n    return IsValid(unit, bot, ignoreLos);\n}" "AcceptUnit unchanged")
require_text("${ptv}" "MaNGOS::AnyUnfriendlyUnitInObjectRangeCheck u_check(player, range);" "legacy search check")

# 3. Same snapshot key as AttackersValue::AddTargetsOf, sight range, 1-s cache bound.
require_text("${att_cpp}" "const std::string ignoreValidate = std::to_string(true);" "attackers ignore-validate qualifier")
require_text("${att_cpp}" "const std::string range = std::to_string((int32)GetRange());" "attackers range qualifier")
require_text("${att_cpp}" "const std::vector<std::string> qualifiers = { range, ignoreValidate };" "attackers qualifier order")
require_text("${att_cpp}" "PAI_VALUE2(std::list<ObjectGuid>, \"possible targets\", Qualified::MultiQualify(qualifiers, \":\"))" "attackers snapshot key")
require_text("${att_h}" "static float GetRange() { return sPlayerbotAIConfig.sightDistance; }" "attackers range = sight distance")
require_text("${vctx}" "creators[\"possible targets\"] = [](PlayerbotAI* ai) { return new PossibleTargetsValue(ai); };" "possible targets variant")
require_text("${vctx}" "creators[\"possible targets no los\"] = [](PlayerbotAI* ai) { return new PossibleTargetsValue(ai, \"possible targets\", sPlayerbotAIConfig.sightDistance, true); };" "no-los variant")
require_text("${vctx}" "creators[\"all targets\"] = [](PlayerbotAI* ai) { return new AllTargetsValue(ai); };" "all-targets variant")
require_text("${nuv}" "ObjectGuidListCalculatedValue(ai, name, 2), range(range), ignoreLos(ignoreLos) {}" "interval 2")
require_text("${value_h}" "now - lastCheckTime >= checkInterval / 2" "whole-second cache bound")

# 4. The reused grid check still is the ring check of the legacy search (core).
require_text("${grid_h}" "AnyUnfriendlyUnitInObjectRangeCheck(WorldObject const* obj, float range)" "2-arg grid check ctor")
require_text("${grid_h}" "if(!i_funit->CanSeeInWorld(u))" "grid check CanSeeInWorld")
require_text("${grid_h}" "return u->IsAlive() && i_obj->IsWithinDistInMap(u, i_range) && !i_funit->IsFriendlyTo(u);" "grid check alive/in-map range/unfriendly")

# 5. Negative probes: each broken variant MUST be rejected by check_shared_search.
function(expect_rejected probe_text label)
  check_shared_search("${probe_text}" probe_err)
  if(probe_err STREQUAL "")
    message(FATAL_ERROR "#541 A32: negative probe not caught (${label}) - the scan is broken")
  endif()
endfunction()
function(make_probe from to out_var)
  string(REPLACE "${from}" "${to}" probe "${calc}")
  if(probe STREQUAL calc)
    message(FATAL_ERROR "#541 A32: probe '${from}' did not apply - pattern drifted")
  endif()
  set(${out_var} "${probe}" PARENT_SCOPE)
endfunction()

make_probe("sPlayerbotAIConfig.possibleTargetsSharedSearch && qualifier.empty()" "qualifier.empty()" p1)
expect_rejected("${p1}" "ungated: switch removed")
make_probe("possibleTargetsSharedSearch && qualifier.empty() && !bot->GetGroup()" "possibleTargetsSharedSearch && !bot->GetGroup()" p2)
expect_rejected("${p2}" "qualifier gate dropped (snapshot would read itself)")
make_probe("qualifier.empty() && !bot->GetGroup())" "qualifier.empty())" p3)
expect_rejected("${p3}" "group gate dropped (cross-thread snapshot reads)")
make_probe("const std::list<ObjectGuid> sharedGuids = shared->Get();" "const std::list<ObjectGuid> sharedGuids = shared->Get(); std::list<Unit*> extra; FindPossibleTargets(bot, extra, range);" p4)
expect_rejected("${p4}" "second grid search inside the shared path")
make_probe("context->GetValue<std::list<ObjectGuid>>(" "GetBotAI(bot)->GetAiObjectContext()->GetValue<std::list<ObjectGuid>>(" p5)
expect_rejected("${p5}" "value read through another AI")
make_probe("std::to_string(true) }" "std::to_string(false) }" p6)
expect_rejected("${p6}" "filtered/other snapshot key")
make_probe("if (unit && inRange(unit) && AcceptUnit(unit))" "if (unit && inRange(unit))" p7)
expect_rejected("${p7}" "AcceptUnit filter dropped")
make_probe("if (unit && inRange(unit) && AcceptUnit(unit))" "if (unit && AcceptUnit(unit))" p8)
expect_rejected("${p8}" "ring/instance check dropped")
make_probe("if (sharedRange > 0 && range == (float)sharedRange)" "if (sharedRange > 0)" p9)
expect_rejected("${p9}" "range guard dropped (nearest adds would get the sight list)")
make_probe("if (shared)" "if (true)" p10)
expect_rejected("${p10}" "null fallback dropped")
make_probe("const std::list<ObjectGuid> sharedGuids = shared->Get();" "static std::list<ObjectGuid> sharedGuids; sharedGuids = shared->Get();" p11)
expect_rejected("${p11}" "static cache")
make_probe("if (unit && (shouldIgnoreValidate || AcceptUnit(unit)))" "if (unit && AcceptUnit(unit))" p12)
expect_rejected("${p12}" "legacy snapshot path changed")
make_probe("std::list<Unit*> targets;" "std::list<Unit*> targets_moved;" p13)
expect_rejected("${p13}" "legacy search anchor drifted")

message(STATUS "possible_targets_shared_search source contract passed (13 negative probes)")
