# twow-repo#541 (audit A27, design A27x + reviews; owner approval 09.10.2026 relayed by OB-00; BEHAVIOUR CHANGE,
# default 0): CastSpellAction reads its spell id and range once, when the action is first created, and actions live
# for the whole session, so spells learned while online stayed impossible on other targets until a relog. With
# AiPlayerbot.CastSpell.RefreshOnLearn = 1 the action re-reads id and range once per change of a per-bot known-spell
# stamp (spell map size, level, free talent points; pet number only for pet spell actions). No per-cast spell name
# lookup. Off = old path (one bool test). Pure part: t/spell_refresh_on_learn_policy_tests.cpp.
#
# Inputs: -DPB_SOURCE_DIR=<module>/src/playerbot -DCORE_SOURCE_DIR=<module>/../..

function(read_source path out_var)
  file(READ "${path}" text)
  string(REPLACE "\r" "" text "${text}")
  set(${out_var} "${text}" PARENT_SCOPE)
endfunction()

function(require_text text needle description)
  string(FIND "${text}" "${needle}" offset)
  if(offset EQUAL -1)
    message(FATAL_ERROR "#541 A27: missing ${description}: ${needle}")
  endif()
endfunction()

function(forbid_text text needle description)
  string(FIND "${text}" "${needle}" offset)
  if(NOT offset EQUAL -1)
    message(FATAL_ERROR "#541 A27: forbidden ${description}: ${needle}")
  endif()
endfunction()

function(require_order text first second description)
  string(FIND "${text}" "${first}" a)
  string(FIND "${text}" "${second}" b)
  if(a EQUAL -1 OR b EQUAL -1 OR NOT a LESS b)
    message(FATAL_ERROR "#541 A27: order ${description}: '${first}' must come before '${second}'")
  endif()
endfunction()

function(require_count text needle expected description)
  set(count 0)
  set(rest "${text}")
  string(LENGTH "${needle}" needle_len)
  while(TRUE)
    string(FIND "${rest}" "${needle}" offset)
    if(offset EQUAL -1)
      break()
    endif()
    math(EXPR count "${count} + 1")
    math(EXPR next "${offset} + ${needle_len}")
    string(SUBSTRING "${rest}" ${next} -1 rest)
  endwhile()
  if(NOT count EQUAL expected)
    message(FATAL_ERROR "#541 A27: ${description}: '${needle}' found ${count}x, expected ${expected}x")
  endif()
endfunction()

# Body of a function: from its signature up to the first line that is exactly "}". The opening brace is the first
# "\n{" after the signature, so a constructor initializer list between signature and brace is part of the body
# (review A27x-1: the old "${signature}\n{" search never found the CastSpellAction ctor). Sets out_var to "" when
# the signature or its braces are missing.
function(function_body text signature out_var)
  set(${out_var} "" PARENT_SCOPE)
  string(FIND "${text}" "${signature}" start)
  if(start EQUAL -1)
    return()
  endif()
  string(SUBSTRING "${text}" ${start} -1 rest)
  string(FIND "${rest}" "\n{" open)
  string(FIND "${rest}" "\n}\n" end)
  if(open EQUAL -1 OR end EQUAL -1 OR NOT open LESS end)
    return()
  endif()
  string(SUBSTRING "${rest}" 0 ${end} body)
  set(${out_var} "${body}" PARENT_SCOPE)
endfunction()

function(require_body text signature out_var)
  function_body("${text}" "${signature}" body)
  if("${body}" STREQUAL "")
    message(FATAL_ERROR "#541 A27: function not found: ${signature}")
  endif()
  set(${out_var} "${body}" PARENT_SCOPE)
endfunction()

# Checks return an error string ("" = ok), so the probes at the end can feed them known-bad text.
function(check_first_statement body signature out_var)
  string(FIND "${body}" "${signature}\n{\n    RefreshSpellIdOnLearn();\n" pos)
  if(pos EQUAL 0)
    set(${out_var} "" PARENT_SCOPE)
  else()
    set(${out_var} "RefreshSpellIdOnLearn() is not the first statement of ${signature}" PARENT_SCOPE)
  endif()
endfunction()

# Switch first (off path = one bool test); pet deferral and the unchanged-stamp return before any lookup.
function(check_gates body out_var)
  string(FIND "${body}" "void CastSpellAction::RefreshSpellIdOnLearn()\n{\n    if (!sPlayerbotAIConfig.castSpellRefreshOnLearn)\n        return;\n" sw)
  string(FIND "${body}" "if (ai::spellstamp::DeferWithoutPet(tracksPet, petNumber))\n        return;" defer)
  string(FIND "${body}" "if (stamp == knownSpellStamp)\n        return;" same)
  string(FIND "${body}" "GetValue<uint32>(\"spell id\", spellName)" lookup)
  string(FIND "${body}" "GetSpellRange(" range)
  string(FIND "${body}" "sLog." log)
  if(NOT sw EQUAL 0 OR defer EQUAL -1 OR same EQUAL -1 OR lookup EQUAL -1 OR range EQUAL -1 OR log EQUAL -1
     OR NOT defer LESS same OR NOT same LESS lookup OR NOT same LESS range OR NOT same LESS log)
    set(${out_var} "switch must be the first statement; pet deferral and the unchanged-stamp return must precede the spell id lookup, GetSpellRange and the log" PARENT_SCOPE)
  else()
    set(${out_var} "" PARENT_SCOPE)
  endif()
endfunction()

function(check_fresh_read body out_var)
  string(FIND "${body}" "idValue->Reset();" reset)
  string(FIND "${body}" "spellId = idValue->Get();" get)
  if(reset EQUAL -1 OR get EQUAL -1 OR NOT reset LESS get)
    set(${out_var} "the 'spell id' value must be Reset() before the refreshed Get() (5 s cache may predate the learn)" PARENT_SCOPE)
  else()
    set(${out_var} "" PARENT_SCOPE)
  endif()
endfunction()

function(check_range_kept body out_var)
  string(FIND "${body}" "SetSpellName(" clobber)
  string(FIND "${body}" "ai::spellstamp::RangeFollowsSpell(range, rangeFromSpell, ATTACK_DISTANCE) && ai->GetSpellRange(spellName, &spellRange)" guarded)
  if(NOT clobber EQUAL -1 OR guarded EQUAL -1)
    set(${out_var} "refresh must guard the range with RangeFollowsSpell(..., ATTACK_DISTANCE) and must not call SetSpellName (melee range clobber)" PARENT_SCOPE)
  else()
    set(${out_var} "" PARENT_SCOPE)
  endif()
endfunction()

function(check_stamp_inputs body out_var)
  string(FIND "${body}" "->GetPet(" getpet)
  string(FIND "${body}" "const uint32 petNumber = tracksPet ? bot->GetPetGuid().GetEntry() : 0;" petnum)
  string(FIND "${body}" "ai::spellstamp::Make(bot->GetSpellMap().size(), bot->GetLevel(), bot->GetFreeTalentPoints(), petNumber)" make)
  if(NOT getpet EQUAL -1 OR petnum EQUAL -1 OR make EQUAL -1)
    set(${out_var} "stamp must use spell map size, level, free talent points and (pet actions only) the pet guid entry, never Unit::GetPet() (clears the pet guid)" PARENT_SCOPE)
  else()
    set(${out_var} "" PARENT_SCOPE)
  endif()
endfunction()

function(check_default_off cpp out_var)
  string(FIND "${cpp}" "    castSpellRefreshOnLearn = config.GetBoolDefault(\"AiPlayerbot.CastSpell.RefreshOnLearn\", false);\n" pos)
  if(pos EQUAL -1)
    set(${out_var} "switch must be read with GetBoolDefault(\"AiPlayerbot.CastSpell.RefreshOnLearn\", false)" PARENT_SCOPE)
  else()
    set(${out_var} "" PARENT_SCOPE)
  endif()
endfunction()

# The ctor only records which range came from the spell; no stamp, no Reset, no switch read there (the first
# isPossible refreshes once because knownSpellStamp starts at 0).
function(check_ctor body out_var)
  string(FIND "${body}" "SetSpellName(spell);" set_name)
  string(FIND "${body}" "if (ai->GetSpellRange(spell, &spellRange))" ctor_range)
  string(FIND "${body}" "rangeFromSpell = range;" from_spell)
  string(FIND "${body}" "castSpellRefreshOnLearn" sw)
  string(FIND "${body}" "Reset()" reset)
  if(set_name EQUAL -1 OR ctor_range EQUAL -1 OR from_spell EQUAL -1 OR NOT set_name LESS from_spell
     OR NOT ctor_range LESS from_spell OR NOT sw EQUAL -1 OR NOT reset EQUAL -1)
    set(${out_var} "ctor must store rangeFromSpell after SetSpellName and its own spell range, and must not stamp or Reset" PARENT_SCOPE)
  else()
    set(${out_var} "" PARENT_SCOPE)
  endif()
endfunction()

macro(expect_ok err)
  if(NOT "${err}" STREQUAL "")
    message(FATAL_ERROR "#541 A27: ${err}")
  endif()
endmacro()

macro(expect_caught probe what)
  if("${probe}" STREQUAL "")
    message(FATAL_ERROR "#541 A27: negative probe not caught: ${what}")
  endif()
endmacro()

read_source("${PB_SOURCE_DIR}/PlayerbotAIConfig.h" config_h)
read_source("${PB_SOURCE_DIR}/PlayerbotAIConfig.cpp" config_cpp)
read_source("${PB_SOURCE_DIR}/aiplayerbot.conf.dist.in" conf_dist)
read_source("${PB_SOURCE_DIR}/SpellStampPolicy.h" policy_h)
read_source("${PB_SOURCE_DIR}/strategy/actions/GenericSpellActions.h" spell_h)
read_source("${PB_SOURCE_DIR}/strategy/actions/GenericSpellActions.cpp" spell_cpp)
read_source("${PB_SOURCE_DIR}/RandomPlayerbotMgr.cpp" rnd_mgr)
read_source("${CORE_SOURCE_DIR}/src/game/Objects/Player.h" player_h)
read_source("${CORE_SOURCE_DIR}/src/game/Objects/Unit.h" unit_h)
read_source("${CORE_SOURCE_DIR}/src/game/Objects/Object.h" object_h)
read_source("${CORE_SOURCE_DIR}/src/game/ObjectGuid.h" guid_h)

# 1. Switch: default off in code and in the shipped conf.
require_text("${config_h}" "    bool castSpellRefreshOnLearn = false;  // twow-repo#541 (audit A27)" "member default off")
check_default_off("${config_cpp}" err)
expect_ok("${err}")
require_text("${conf_dist}" "\nAiPlayerbot.CastSpell.RefreshOnLearn = 0\n" "documented key = 0")
forbid_text("${conf_dist}" "AiPlayerbot.CastSpell.RefreshOnLearn = 1" "shipped as on")
require_order("${conf_dist}" "AiPlayerbot.CanCastSpell.CheckPower = 0" "AiPlayerbot.CastSpell.RefreshOnLearn = 0" "key documented with the #541 switches")
# The A27 alternative (per-isPossible id-0 lookup) is not implemented next to this one.
forbid_text("${config_h}" "castSpellResolveLearned" "superseded A27 switch")
forbid_text("${spell_cpp}" "ResolveLearnedSpellId" "superseded A27 helper")

# 2. Policy: stamp never 0, all four inputs in separate fields, pet deferral, exact range follow.
require_text("${policy_h}" "(std::uint64_t(1) << 63)" "non-zero stamp marker")
require_text("${policy_h}" "(std::uint64_t(petNumber & 0xFFFFFFu) << 39)" "pet number field")
require_text("${policy_h}" "(std::uint64_t(freeTalentPoints & 0xFFFu) << 27)" "talent point field")
require_text("${policy_h}" "(std::uint64_t(level & 0xFFu) << 19)" "level field (ABA guard)")
require_text("${policy_h}" "(std::uint64_t(spellCount) & 0x7FFFFu)" "spell count field")
require_text("${policy_h}" "return tracksPet && petNumber == 0u;" "pet spell actions wait for a pet")
require_text("${policy_h}" "return range == rangeFromSpell && range != meleeRange;" "range follows only an untouched, non-melee spell range")
forbid_text("${policy_h}" "static " "static state in the policy")

# 3. Header.
require_text("${spell_h}" "        void RefreshSpellIdOnLearn();\n" "helper declaration")
require_text("${spell_h}" "        virtual bool SpellStampTracksPet() const { return false; }\n" "base actions leave the pet out")
require_text("${spell_h}" "        bool SpellStampTracksPet() const override { return true; }  // twow-repo#541 (audit A27)" "pet spell actions track the pet")
require_order("${spell_h}" "class CastPetSpellAction : public CastSpellAction" "bool SpellStampTracksPet() const override { return true; }" "override in CastPetSpellAction")
require_order("${spell_h}" "bool SpellStampTracksPet() const override { return true; }" "class CastAuraSpellAction" "override only in CastPetSpellAction")
require_count("${spell_h}" "SpellStampTracksPet() const override" 1 "exactly one pet-tracking override")
require_text("${spell_h}" "        float rangeFromSpell = 0.0f;" "range-from-spell member")
require_text("${spell_h}" "        uint64 knownSpellStamp = 0;" "stamp member, 0 = not stamped")
require_text("${spell_cpp}" "#include \"playerbot/SpellStampPolicy.h\"" "policy include")

# 4. Ctor (with its initializer list).
require_body("${spell_cpp}" "CastSpellAction::CastSpellAction(PlayerbotAI* ai, std::string spell)" ctor_body)
require_text("${ctor_body}" ": Action(ai, spell)\n, range(ai->GetRange(\"spell\"))\n{" "ctor initializer list inside the extracted body")
check_ctor("${ctor_body}" err)
expect_ok("${err}")

# 5. SetSpellName keeps its logic and only tracks the spell-owned range.
require_body("${spell_cpp}" "void CastSpellAction::SetSpellName(const std::string& name, std::string spellIDContextName /*= \"spell id\"*/, bool force)" set_body)
require_text("${set_body}" "if (force || spellName != name)" "unchanged name/force gate")
require_text("${set_body}" "spellId = ai->GetAiObjectContext()->GetValue<uint32>(spellIDContextName, name)->Get();" "unchanged id read")
require_order("${set_body}" "range = spellRange;" "rangeFromSpell = range;" "range tracked after assignment")
forbid_text("${set_body}" "Reset()" "refresh in SetSpellName (blessing/shoot name switches would recalculate every tick)")

# 6. Refresh helper.
require_body("${spell_cpp}" "void CastSpellAction::RefreshSpellIdOnLearn()" helper_body)
check_gates("${helper_body}" err)
expect_ok("${err}")
check_stamp_inputs("${helper_body}" err)
expect_ok("${err}")
check_fresh_read("${helper_body}" err)
expect_ok("${err}")
check_range_kept("${helper_body}" err)
expect_ok("${err}")
require_order("${helper_body}" "if (stamp == knownSpellStamp)" "knownSpellStamp = stamp;" "stamp stored after compare")
require_order("${helper_body}" "knownSpellStamp = stamp;" "idValue->Reset();" "stamp stored before the recalculation (no retry loop)")
require_text("${helper_body}" "if (spellId != oldId)\n    {\n        sLog.outBasic(\"[SpellIdRefresh] " "id-change line only when the id changed")
require_text("${helper_body}" "else if (range != oldRange)\n    {\n        sLog.outBasic(\"[SpellRangeRefresh] " "range-only line kept apart")
forbid_text("${helper_body}" "static " "static cache")
forbid_text("${spell_cpp}" "std::shared_mutex" "shared_mutex")
forbid_text("${spell_cpp}" "std::mutex" "lock in spell actions")

# 7. Hooks: first statement of the two id-reading isPossible bodies; nowhere else; never in the vehicle path.
require_body("${spell_cpp}" "bool CastSpellAction::isPossible()" base_possible)
check_first_statement("${base_possible}" "bool CastSpellAction::isPossible()" err)
expect_ok("${err}")
require_text("${base_possible}" "            if (!spellId)\n                return false;" "unchanged id-0 refusal")
require_body("${spell_cpp}" "bool CastPetSpellAction::isPossible()" pet_possible)
check_first_statement("${pet_possible}" "bool CastPetSpellAction::isPossible()" err)
expect_ok("${err}")
require_body("${spell_cpp}" "bool CastVehicleSpellAction::isPossible()" vehicle_possible)
forbid_text("${vehicle_possible}" "RefreshSpellIdOnLearn" "refresh in the 'vehicle spell id' path")
require_count("${spell_cpp}" "    RefreshSpellIdOnLearn();\n" 2 "refresh call sites")
forbid_text("${rnd_mgr}" "castSpellRefreshOnLearn" "switch read in RandomPlayerbotMgr (no new return before PerfMon Init)")

# 8. Core premises the stamp relies on.
require_text("${player_h}" "typedef std::unordered_map<uint32, PlayerSpell> PlayerSpellMap;" "spell map size() is O(1)")
require_text("${player_h}" "PlayerSpellMap      & GetSpellMap() { return m_spells; }" "Player::GetSpellMap")
require_text("${player_h}" "uint32 GetFreeTalentPoints() const { return GetUInt32Value(PLAYER_CHARACTER_POINTS1); }" "free talent points field")
require_text("${unit_h}" "ObjectGuid const& GetPetGuid() const { return GetGuidValue(UNIT_FIELD_SUMMON); }" "side-effect-free pet guid")
require_text("${unit_h}" "uint32 GetLevel() const final { return GetUInt32Value(UNIT_FIELD_LEVEL); }" "level field")
require_text("${guid_h}" "uint32   GetEntry() const { return HasEntry() ? uint32((m_guid >> 24) & UI64LIT(0x0000000000FFFFFF)) : 0; }" "24-bit guid entry (pet number)")
require_text("${object_h}" "#define ATTACK_DISTANCE 5.0f" "melee range marker")

# 9. Negative probes: every check must reject a known-bad text, otherwise the scan is broken.
check_first_statement("bool CastSpellAction::isPossible()\n{\n    if (spellName == \"mount\")\n    {\n    }\n    RefreshSpellIdOnLearn();\n" "bool CastSpellAction::isPossible()" probe)
expect_caught("${probe}" "hook after the mount block passed as first statement")
check_gates("void CastSpellAction::RefreshSpellIdOnLearn()\n{\n    Value<uint32>* idValue = ai->GetAiObjectContext()->GetValue<uint32>(\"spell id\", spellName);\n    if (!sPlayerbotAIConfig.castSpellRefreshOnLearn)\n        return;\n    if (ai::spellstamp::DeferWithoutPet(tracksPet, petNumber))\n        return;\n    if (stamp == knownSpellStamp)\n        return;\n    ai->GetSpellRange(spellName, &spellRange);\n    sLog.outBasic(\"\");\n" probe)
expect_caught("${probe}" "lookup before the switch gate passed (per-cast name lookup)")
check_gates("void CastSpellAction::RefreshSpellIdOnLearn()\n{\n    if (!sPlayerbotAIConfig.castSpellRefreshOnLearn)\n        return;\n    ai->GetSpellRange(spellName, &spellRange);\n    if (ai::spellstamp::DeferWithoutPet(tracksPet, petNumber))\n        return;\n    if (stamp == knownSpellStamp)\n        return;\n    GetValue<uint32>(\"spell id\", spellName);\n    sLog.outBasic(\"\");\n" probe)
expect_caught("${probe}" "GetSpellRange (itself a 'spell id' lookup) before the unchanged-stamp return passed")
check_gates("void CastSpellAction::RefreshSpellIdOnLearn()\n{\n    if (!sPlayerbotAIConfig.castSpellRefreshOnLearn)\n        return;\n    if (ai::spellstamp::DeferWithoutPet(tracksPet, petNumber))\n        return;\n    GetValue<uint32>(\"spell id\", spellName);\n    if (stamp == knownSpellStamp)\n        return;\n    ai->GetSpellRange(spellName, &spellRange);\n    sLog.outBasic(\"\");\n" probe)
expect_caught("${probe}" "lookup before the unchanged-stamp return passed")
check_fresh_read("    spellId = idValue->Get();\n" probe)
expect_caught("${probe}" "refresh without Reset() (stale 5 s cache) passed")
check_range_kept("void CastSpellAction::RefreshSpellIdOnLearn()\n{\n    SetSpellName(spellName, \"spell id\", true);\n" probe)
expect_caught("${probe}" "SetSpellName(..., true) (melee range clobber) passed")
check_range_kept("    if (ai::spellstamp::RangeFollowsSpell(range, rangeFromSpell) && ai->GetSpellRange(spellName, &spellRange))\n" probe)
expect_caught("${probe}" "range follow without the ATTACK_DISTANCE marker passed")
check_stamp_inputs("    Pet* pet = bot->GetPet();\n    const uint32 petNumber = tracksPet ? bot->GetPetGuid().GetEntry() : 0;\n    ai::spellstamp::Make(bot->GetSpellMap().size(), bot->GetLevel(), bot->GetFreeTalentPoints(), petNumber)\n" probe)
expect_caught("${probe}" "Unit::GetPet() in the stamp passed")
check_stamp_inputs("    const uint32 petNumber = tracksPet ? bot->GetPetGuid().GetEntry() : 0;\n    ai::spellstamp::Make(bot->GetSpellMap().size(), 0, bot->GetFreeTalentPoints(), petNumber)\n" probe)
expect_caught("${probe}" "stamp without the level (ABA) passed")
check_default_off("    castSpellRefreshOnLearn = config.GetBoolDefault(\"AiPlayerbot.CastSpell.RefreshOnLearn\", true);\n" probe)
expect_caught("${probe}" "default true passed as default off")
check_ctor("CastSpellAction::CastSpellAction(PlayerbotAI* ai, std::string spell)\n: Action(ai, spell)\n{\n    if (sPlayerbotAIConfig.castSpellRefreshOnLearn)\n        ai->GetAiObjectContext()->GetValue<uint32>(\"spell id\", spell)->Reset();\n    SetSpellName(spell);\n    if (ai->GetSpellRange(spell, &spellRange))\n    rangeFromSpell = range;\n" probe)
expect_caught("${probe}" "switch-gated Reset in the ctor passed")
# Body extraction across an initializer list, and no bleed into the next function.
function_body("A::A(int x)\n: B(x)\n, c(1)\n{\n    SetSpellName(spell);\n}\n\nvoid A::F()\n{\n    rangeFromSpell = range;\n}\n" "A::A(int x)" probe_body)
require_text("${probe_body}" ": B(x)\n, c(1)\n{\n    SetSpellName(spell);" "probe: body extraction across an initializer list")
check_ctor("${probe_body}" probe)
expect_caught("${probe}" "ctor check took rangeFromSpell from the next function (body bleed)")
function_body("void A::Missing()\n" "void A::Missing()" probe_body)
if(NOT "${probe_body}" STREQUAL "")
  message(FATAL_ERROR "#541 A27: negative probe not caught: body without braces was extracted")
endif()

message(STATUS "spell_refresh_on_learn source contract passed")
