# twow-repo#541 (audit A16, AiPlayerbot.Perf.StaticSpellLists, default 0, behaviour-neutral): the
# castability checks in PlayerbotAI.cpp (CheckSpellTargetAlignment, CanCastSpell for unit, game object and
# position) take the neutral and out-of-control spell ids from constant arrays in SpellListPolicy.h instead
# of building a 20/24-node std::list<uint32> on every call. Switch off = the legacy literal lists and their
# std::find, unchanged. The arrays and the legacy literals must hold the same ids in the same order (drift
# guard below). Membership itself: t/static_spell_lists_policy_tests.cpp.
# Every check returns "" when it holds, else the reason, so the built-in negative probes reuse it.
if(NOT DEFINED PB_SOURCE_DIR)
  message(FATAL_ERROR "PB_SOURCE_DIR is required")
endif()

set(TAG "#541 A16 static spell lists")
set(NEUTRAL_IDS "1499, 5384, 13795, 13809, 13813, 14302, 14303, 14304, 14305, 14310, 14311, 14316, 14317, 27023, 27025, 34600, 49055, 49056, 49066, 49067")
set(OOC_IDS "642, 1020, 1499, 1953, 7744, 11958, 13795, 13809, 13813, 14302, 14303, 14304, 14305, 14310, 14311, 14316, 14317, 27023, 27025, 34600, 49055, 49056, 49066, 49067")
set(LEGACY_NEUTRAL "const std::list<uint32> neutralSpells = { ${NEUTRAL_IDS} }")
set(LEGACY_OOC "const std::list<uint32> ignoreOutOfControllSpells = { ${OOC_IDS} }")
set(GATE "if (sPlayerbotAIConfig.perfStaticSpellLists)")

# Full legacy lookups of the switch-off path, including the comparison against end().
set(NF_ALIGN "neutralSpell = std::find(neutralSpells.begin(), neutralSpells.end(), spellInfo->Id) != neutralSpells.end();")
set(NF_UNIT "neutralSpell = std::find(neutralSpells.begin(), neutralSpells.end(), spellid) != neutralSpells.end();")
set(OF "castableOutOfControl = std::find(ignoreOutOfControllSpells.begin(), ignoreOutOfControllSpells.end(), spellid) != ignoreOutOfControllSpells.end();")
set(FAST_NEUTRAL_ALIGN "neutralSpell = ai::spelllists::IsNeutralSpell(spellInfo->Id);")
set(FAST_NEUTRAL_UNIT "neutralSpell = ai::spelllists::IsNeutralSpell(spellid);")
set(FAST_OOC "castableOutOfControl = ai::spelllists::IsCastableOutOfControl(spellid);")
set(USE_OOC "if (!castableOutOfControl)")
set(USE_NEUTRAL_ALIGN "if (neutralSpell)")
set(USE_NEUTRAL_UNIT "if(!neutralSpell)")

set(SIG_ALIGN "SpellCastResult PlayerbotAI::CheckSpellTargetAlignment(SpellEntry const* spellInfo, Unit* target)")
set(SIG_UNIT "bool PlayerbotAI::CanCastSpell(uint32 spellid, Unit* target, uint8 effectMask, bool checkHasSpell,")
set(SIG_GO "bool PlayerbotAI::CanCastSpell(uint32 spellid, GameObject* goTarget,")
set(SIG_POS "bool PlayerbotAI::CanCastSpell(uint32 spellid, float x, float y, float z,")

function(read_source path out_var)
  file(READ "${PB_SOURCE_DIR}/${path}" text)
  string(REPLACE "\r" "" text "${text}")
  set(${out_var} "${text}" PARENT_SCOPE)
endfunction()

function(count_text text needle out_var)
  string(LENGTH "${text}" full)
  string(REPLACE "${needle}" "" stripped "${text}")
  string(LENGTH "${stripped}" rest)
  string(LENGTH "${needle}" n)
  math(EXPR c "(${full} - ${rest}) / ${n}")
  set(${out_var} ${c} PARENT_SCOPE)
endfunction()

# Function body from its signature up to the first column-0 closing brace.
function(function_body text signature out_var)
  string(FIND "${text}" "${signature}" start)
  if(start EQUAL -1)
    set(${out_var} "" PARENT_SCOPE)
    return()
  endif()
  string(SUBSTRING "${text}" ${start} -1 rest)
  string(FIND "${rest}" "\n}\n" end)
  string(SUBSTRING "${rest}" 0 ${end} body)
  set(${out_var} "${body}" PARENT_SCOPE)
endfunction()

function(check_switch config_h config_cpp conf_dist out_var)
  set(err "")
  string(FIND "${config_h}" "    bool perfStaticSpellLists = false;  // twow-repo#541 (audit A16):" a)
  string(FIND "${config_cpp}" "    perfStaticSpellLists = config.GetBoolDefault(\"AiPlayerbot.Perf.StaticSpellLists\", false);" b)
  string(FIND "${conf_dist}" "\nAiPlayerbot.Perf.StaticSpellLists = 0\n" c)
  # Next to the other #541 performance switches.
  string(FIND "${config_cpp}" "perfGiveItemGroupOnlyScan = config.GetBoolDefault(" b_prev)
  string(FIND "${conf_dist}" "\nAiPlayerbot.Perf.GiveItemGroupOnlyScan = 0\n" c_prev)
  if(a EQUAL -1)
    set(err "member bool perfStaticSpellLists = false (twow-repo#541 audit A16) missing")
  elseif(b EQUAL -1)
    set(err "config read with default false missing")
  elseif(c EQUAL -1)
    set(err "documented key = 0 missing in aiplayerbot.conf.dist.in")
  elseif(b_prev EQUAL -1 OR NOT b_prev LESS b OR c_prev EQUAL -1 OR NOT c_prev LESS c)
    set(err "switch not placed after the earlier #541 audit switches")
  endif()
  set(${out_var} "${err}" PARENT_SCOPE)
endfunction()

function(check_header header out_var)
  set(err "")
  string(FIND "${header}" "constexpr std::array<std::uint32_t, 20> NeutralSpellIds = {{ ${NEUTRAL_IDS} }};" a)
  string(FIND "${header}" "constexpr std::array<std::uint32_t, 24> OutOfControlSpellIds = {{ ${OOC_IDS} }};" b)
  string(FIND "${header}" "constexpr bool IsNeutralSpell(std::uint32_t spellId) { return Contains(NeutralSpellIds, spellId); }" c)
  string(FIND "${header}" "constexpr bool IsCastableOutOfControl(std::uint32_t spellId) { return Contains(OutOfControlSpellIds, spellId); }" d)
  string(FIND "${header}" "        if (ids[i] == id)\n            return true;" e)
  string(FIND "${header}" "static " s)
  string(FIND "${header}" "mutable" m)
  if(a EQUAL -1)
    set(err "NeutralSpellIds differs from the legacy neutralSpells literal")
  elseif(b EQUAL -1)
    set(err "OutOfControlSpellIds differs from the legacy ignoreOutOfControllSpells literal")
  elseif(c EQUAL -1 OR d EQUAL -1 OR e EQUAL -1)
    set(err "membership helpers changed")
  elseif(NOT s EQUAL -1 OR NOT m EQUAL -1)
    set(err "no static or mutable state in the policy header")
  endif()
  set(${out_var} "${err}" PARENT_SCOPE)
endfunction()

# One site: gate -> fast path -> untouched legacy literal -> its full std::find -> the unchanged use.
function(check_site body fast legacy legacy_find use out_var)
  set(err "")
  string(FIND "${body}" "${GATE}" g)
  string(FIND "${body}" "${fast}" f)
  string(FIND "${body}" "${legacy}" l)
  string(FIND "${body}" "${legacy_find}" lf)
  string(FIND "${body}" "${use}" u)
  if(body STREQUAL "")
    set(err "function not found")
  elseif(g EQUAL -1)
    set(err "switch gate missing")
  elseif(f EQUAL -1)
    set(err "fast path missing: ${fast}")
  elseif(l EQUAL -1 OR lf EQUAL -1)
    set(err "legacy list or its full std::find missing (switch-off path must stay as today)")
  elseif(u EQUAL -1)
    set(err "use of the result missing or inverted: ${use}")
  elseif(NOT g LESS f OR NOT f LESS l OR NOT l LESS lf OR NOT lf LESS u)
    set(err "order gate -> fast path -> legacy list -> legacy find -> use broken")
  endif()
  set(${out_var} "${err}" PARENT_SCOPE)
endfunction()

function(check_ai ai_cpp out_var)
  set(err "")
  count_text("${ai_cpp}" "${LEGACY_NEUTRAL}" n_neutral)
  count_text("${ai_cpp}" "${LEGACY_OOC}" n_ooc)
  count_text("${ai_cpp}" "${GATE}" n_gate)
  count_text("${ai_cpp}" "${USE_OOC}" n_use_ooc)
  count_text("${ai_cpp}" "!= neutralSpells.end();" n_nf)
  count_text("${ai_cpp}" "== neutralSpells.end()" n_nf_flip)
  count_text("${ai_cpp}" "== ignoreOutOfControllSpells.end()" n_of_flip)
  count_text("${ai_cpp}" "const bool neutralSpell = std::find(" n_old_neutral)
  count_text("${ai_cpp}" "if (std::find(ignoreOutOfControllSpells.begin()" n_old_ooc)
  string(FIND "${ai_cpp}" "#include \"playerbot/SpellListPolicy.h\"" inc)
  function_body("${ai_cpp}" "${SIG_ALIGN}" b_align)
  function_body("${ai_cpp}" "${SIG_UNIT}" b_unit)
  function_body("${ai_cpp}" "${SIG_GO}" b_go)
  function_body("${ai_cpp}" "${SIG_POS}" b_pos)
  check_site("${b_align}" "${FAST_NEUTRAL_ALIGN}" "${LEGACY_NEUTRAL}" "${NF_ALIGN}" "${USE_NEUTRAL_ALIGN}" e1)
  check_site("${b_unit}" "${FAST_OOC}" "${LEGACY_OOC}" "${OF}" "${USE_OOC}" e2)
  check_site("${b_go}" "${FAST_OOC}" "${LEGACY_OOC}" "${OF}" "${USE_OOC}" e3)
  check_site("${b_pos}" "${FAST_OOC}" "${LEGACY_OOC}" "${OF}" "${USE_OOC}" e4)
  # The unit variant also carries the neutral list (inside if (!itemTarget)), after the out-of-control site:
  # its own gate -> fast path -> legacy literal -> full legacy find -> if(!neutralSpell).
  string(FIND "${b_unit}" "${USE_OOC}" u_ooc_use)
  set(e5 "")
  if(u_ooc_use EQUAL -1)
    set(e5 "out-of-control use missing")
  else()
    string(SUBSTRING "${b_unit}" ${u_ooc_use} -1 unit_tail)
    check_site("${unit_tail}" "${FAST_NEUTRAL_UNIT}" "${LEGACY_NEUTRAL}" "${NF_UNIT}" "${USE_NEUTRAL_UNIT}" e5)
  endif()
  if(inc EQUAL -1)
    set(err "SpellListPolicy.h include missing")
  elseif(NOT n_neutral EQUAL 2)
    set(err "legacy neutralSpells literal must appear exactly twice (found ${n_neutral}): ids drifted from the arrays")
  elseif(NOT n_ooc EQUAL 3)
    set(err "legacy ignoreOutOfControllSpells literal must appear exactly three times (found ${n_ooc}): ids drifted from the arrays")
  elseif(NOT n_gate EQUAL 5)
    set(err "exactly five switch gates expected (found ${n_gate})")
  elseif(NOT n_use_ooc EQUAL 3)
    set(err "exactly three '${USE_OOC}' expected (found ${n_use_ooc})")
  elseif(NOT n_nf EQUAL 2 OR NOT n_nf_flip EQUAL 0 OR NOT n_of_flip EQUAL 0)
    set(err "legacy membership comparisons changed (neutral '!= end' ${n_nf}/2, '== end' flips ${n_nf_flip}+${n_of_flip}/0)")
  elseif(NOT n_old_neutral EQUAL 0 OR NOT n_old_ooc EQUAL 0)
    set(err "an ungated legacy lookup is left")
  elseif(NOT e1 STREQUAL "")
    set(err "CheckSpellTargetAlignment: ${e1}")
  elseif(NOT e2 STREQUAL "")
    set(err "CanCastSpell(unit) out of control: ${e2}")
  elseif(NOT e3 STREQUAL "")
    set(err "CanCastSpell(game object): ${e3}")
  elseif(NOT e4 STREQUAL "")
    set(err "CanCastSpell(position): ${e4}")
  elseif(NOT e5 STREQUAL "")
    set(err "CanCastSpell(unit) neutral site: ${e5}")
  endif()
  set(${out_var} "${err}" PARENT_SCOPE)
endfunction()

read_source("PlayerbotAI.cpp" ai_cpp)
read_source("SpellListPolicy.h" policy_h)
read_source("PlayerbotAIConfig.h" config_h)
read_source("PlayerbotAIConfig.cpp" config_cpp)
read_source("aiplayerbot.conf.dist.in" conf_dist)

# Positive checks on the real sources.
check_switch("${config_h}" "${config_cpp}" "${conf_dist}" e)
if(NOT e STREQUAL "")
  message(FATAL_ERROR "${TAG}: switch: ${e}")
endif()
check_header("${policy_h}" e)
if(NOT e STREQUAL "")
  message(FATAL_ERROR "${TAG}: SpellListPolicy.h: ${e}")
endif()
check_ai("${ai_cpp}" e)
if(NOT e STREQUAL "")
  message(FATAL_ERROR "${TAG}: PlayerbotAI.cpp: ${e}")
endif()

# Negative probes: each mutation must be caught, otherwise the scan itself is broken.
macro(expect_caught result what)
  if("${result}" STREQUAL "")
    message(FATAL_ERROR "${TAG}: negative probe not caught: ${what} - the scan is broken")
  endif()
endmacro()

# 1) One id dropped from an array (drift between array and legacy list).
string(REPLACE "49066, 49067 }};" "49067 }};" probe "${policy_h}")
check_header("${probe}" e)
expect_caught("${e}" "NeutralSpellIds/OutOfControlSpellIds lost an id")

# 2) One id changed in a legacy literal only (the arrays now differ from the switch-off path).
string(REPLACE "{ 642, 1020," "{ 643, 1020," probe "${ai_cpp}")
check_ai("${probe}" e)
expect_caught("${e}" "a legacy ignoreOutOfControllSpells literal changed")

# 3) Switch default flipped to on.
string(REPLACE "bool perfStaticSpellLists = false;" "bool perfStaticSpellLists = true;" probe "${config_h}")
check_switch("${probe}" "${config_cpp}" "${conf_dist}" e)
expect_caught("${e}" "member default true")

# 4) Config read defaulting to true.
string(REPLACE "\"AiPlayerbot.Perf.StaticSpellLists\", false)" "\"AiPlayerbot.Perf.StaticSpellLists\", true)" probe "${config_cpp}")
check_switch("${config_h}" "${probe}" "${conf_dist}" e)
expect_caught("${e}" "GetBoolDefault(..., true)")

# 5) Documented as on.
string(REPLACE "\nAiPlayerbot.Perf.StaticSpellLists = 0\n" "\nAiPlayerbot.Perf.StaticSpellLists = 1\n" probe "${conf_dist}")
check_switch("${config_h}" "${config_cpp}" "${probe}" e)
expect_caught("${e}" "conf.dist = 1")

# 6) One gate removed (fast path taken unconditionally in one site).
function_body("${ai_cpp}" "${SIG_GO}" go_body)
string(REPLACE "${GATE}" "if (true)" go_probe "${go_body}")
string(REPLACE "${go_body}" "${go_probe}" probe "${ai_cpp}")
check_ai("${probe}" e)
expect_caught("${e}" "switch gate removed in CanCastSpell(game object)")

# 7) Legacy path deleted (switch off no longer equals today's code).
string(REPLACE "${LEGACY_NEUTRAL};" "" probe "${ai_cpp}")
check_ai("${probe}" e)
expect_caught("${e}" "legacy neutralSpells list removed")

# 8) A static cache sneaking into the policy header.
string(REPLACE "constexpr bool IsNeutralSpell" "static bool cache; constexpr bool IsNeutralSpell" probe "${policy_h}")
check_header("${probe}" e)
expect_caught("${e}" "static state in SpellListPolicy.h")

# 9) Out-of-control use inverted in one site (review: if (castableOutOfControl)).
function_body("${ai_cpp}" "${SIG_POS}" pos_body)
string(REPLACE "${USE_OOC}" "if (castableOutOfControl)" pos_probe "${pos_body}")
string(REPLACE "${pos_body}" "${pos_probe}" probe "${ai_cpp}")
check_ai("${probe}" e)
expect_caught("${e}" "inverted if (castableOutOfControl) in CanCastSpell(position)")

# 10) Switch-off neutral lookup flipped to == end() (review).
string(REPLACE "${NF_UNIT}" "neutralSpell = std::find(neutralSpells.begin(), neutralSpells.end(), spellid) == neutralSpells.end();" probe "${ai_cpp}")
check_ai("${probe}" e)
expect_caught("${e}" "legacy neutral find flipped to == end()")

# 11) Neutral use in CheckSpellTargetAlignment inverted (review: if (neutralSpell) after the find).
function_body("${ai_cpp}" "${SIG_ALIGN}" align_body)
string(REPLACE "${USE_NEUTRAL_ALIGN}" "if (!neutralSpell)" align_probe "${align_body}")
string(REPLACE "${align_body}" "${align_probe}" probe "${ai_cpp}")
check_ai("${probe}" e)
expect_caught("${e}" "inverted if (!neutralSpell) in CheckSpellTargetAlignment")

message(STATUS "${TAG}: source contract OK (11 negative probes caught)")
