function(require_text text needle description)
  string(FIND "${text}" "${needle}" offset)
  if(offset EQUAL -1)
    message(FATAL_ERROR "Missing ${description}: ${needle}")
  endif()
endfunction()

file(READ "${PB_SOURCE_DIR}/AiFactory.cpp" factory)
file(READ "${PB_SOURCE_DIR}/aiplayerbot.conf.dist.in" config_template)
file(READ "${PB_SOURCE_DIR}/strategy/shaman/TankShamanStrategy.cpp" shaman)
file(READ "${PB_SOURCE_DIR}/strategy/shaman/TankShamanStrategy.h" shaman_h)
file(READ "${PB_SOURCE_DIR}/strategy/shaman/ShamanAiObjectContext.cpp" shaman_ctx)
file(READ "${PB_SOURCE_DIR}/strategy/shaman/ShamanActions.h" shaman_actions)
file(READ "${PB_SOURCE_DIR}/strategy/rogue/TankRogueStrategy.cpp" rogue)
file(READ "${PB_SOURCE_DIR}/strategy/rogue/TankRogueStrategy.h" rogue_h)
file(READ "${PB_SOURCE_DIR}/strategy/rogue/RogueAiObjectContext.cpp" rogue_ctx)
file(READ "${PB_SOURCE_DIR}/strategy/rogue/RogueActions.h" rogue_actions)
file(READ "${PB_MODULE_DIR}/tools/build_premade_specs.py" generator)
file(READ "${PB_MODULE_DIR}/data/stat-weights/stat-priorities-v2.tsv" stats)

# Role: decided by the premade path, like the bear (#308).
require_text("${factory}" "#include \"playerbot/TankPathPolicy.h\"" "tank path policy")
require_text("${factory}" "char const* TankPathStrategy(Player const* player)" "tank path helper")
require_text("${factory}" "// #357 / #367: a shaman or rogue on its tank path tanks, whatever the tree." "tank role for the tank paths")
require_text("${factory}" "combatEngine->addStrategies(tank, \"tank assist\", \"pull\", NULL);" "shaman tank combat strategies")
require_text("${factory}" "combatEngine->addStrategies(tank, \"tank assist\", NULL);" "rogue tank combat strategies")
require_text("${factory}" "combatEngine->removeStrategy(\"behind\");" "rogue tank faces its target")

# Strategies and actions (#357 / #367 phase 1 skeleton).
require_text("${shaman_h}" "STRATEGY_TYPE_TANK | STRATEGY_TYPE_MELEE" "shaman tank strategy is a tank strategy")
require_text("${shaman}" "new NextAction(\"earthshaker slam\", ACTION_HIGH + 5)" "shaman taunt on lost aggro")
require_text("${shaman}" "new NextAction(\"rockbiter weapon\", ACTION_HIGH + 1)" "Rockbiter for threat")
require_text("${shaman}" "name == \"windfury weapon\"" "no Windfury on the tank")
require_text("${shaman}" "ai::tank_path::AllowTankStormstrike(holdsAggro, charges)" "Stormstrike gate (owner 2026-09-27)")
require_text("${shaman_ctx}" "creators[\"tank shaman\"]" "shaman tank strategy registered")
require_text("${shaman_ctx}" "creators[\"earthshaker slam\"]" "shaman taunt action registered")
require_text("${shaman_actions}" "\"earthshaker slam\"" "shaman taunt spell")
require_text("${rogue_h}" "STRATEGY_TYPE_TANK | STRATEGY_TYPE_MELEE" "rogue tank strategy is a tank strategy")
require_text("${rogue}" "new NextAction(\"rogue taunt\", ACTION_HIGH + 5)" "rogue taunt on lost aggro")
require_text("${rogue}" "name == \"feint\" || name == \"vanish\"" "no threat dumps on the tank")
require_text("${rogue}" "new NextAction(\"riposte\", ACTION_HIGH + 4)" "Riposte after a parry (owner 2026-09-27)")
require_text("${rogue}" "new NextAction(\"ghostly strike\", ACTION_HIGH + 2)" "Ghostly Strike uptime (owner 2026-09-27)")
require_text("${rogue_ctx}" "return new GhostlyStrikeTrigger(ai);" "Ghostly Strike trigger registered")
require_text("${rogue_ctx}" "creators[\"tank rogue\"]" "rogue tank strategy registered")
require_text("${rogue_ctx}" "creators[\"rogue taunt\"]" "rogue taunt action registered")
require_text("${rogue_actions}" "CastSpellAction(ai, \"spit\")" "rogue taunt spell (design D-2)")

# Premade paths share the builds and ship OFF (weight 0).
require_text("${generator}" "('shaman tank',   '550331300202012-5005303105023151')" "shaman tank build = enhancement")
require_text("${generator}" "('rogue tank',    '0053231052330012-500350200050122231')" "rogue tank build = combat")
require_text("${generator}" "(7, 'shaman tank'): 0," "shaman tank weight 0")
require_text("${generator}" "(4, 'rogue tank'): 0," "rogue tank weight 0")
require_text("${config_template}" "AiPlayerbot.PremadeSpecName.7.3 = shaman tank" "shaman tank premade path")
require_text("${config_template}" "AiPlayerbot.PremadeSpecProb.7.3 = 0" "shaman tank off")
require_text("${config_template}" "AiPlayerbot.PremadeSpecName.4.3 = rogue tank" "rogue tank premade path")
require_text("${config_template}" "AiPlayerbot.PremadeSpecProb.4.3 = 0" "rogue tank off")
require_text("${config_template}" "AiPlayerbot.PremadeSpecLink.7.3.60 = " "shaman tank level-60 link")
require_text("${config_template}" "AiPlayerbot.PremadeSpecLink.4.3.60 = " "rogue tank level-60 link")

# Stat rows (#308).
require_text("${stats}" "7\tshaman\t3\tshaman tank\ttank\tdefense" "shaman tank stats")
require_text("${stats}" "4\trogue\t3\trogue tank\ttank\tsta\tagi\tdodge_pct\tparry_pct" "rogue tank stats (owner 2026-09-27: stamina, agility, dodge, parry)")
