# twow-repo#563 X3b variant 2 (published snapshot, OB-00 go 10.10.2026), site 1: AttackersValue::AddTargetsOf.
# With AiPlayerbot.X3b.PublishedTargets (default 0) a bot never computes "possible targets" or reads
# "current/old target" on another bot's context: it reads that bot's published snapshot. Each bot publishes
# its own targets right after reading them on its own context. Off: the old code path, unchanged.

# cmake 3.x script mode (Debian trixie builder / CI): without a policy version, TRUE in while()/if() (CMP0012)
# and empty list elements (CMP0007) behave as in cmake 2.x; the host cmake 4.x has them NEW already.
cmake_policy(VERSION 3.16)

function(read_source path out_var)
  file(READ "${PB_SOURCE_DIR}/${path}" text)
  string(REPLACE "\r" "" text "${text}")
  set(${out_var} "${text}" PARENT_SCOPE)
endfunction()

function(require_text text needle description)
  string(FIND "${text}" "${needle}" offset)
  if(offset EQUAL -1)
    message(FATAL_ERROR "#563 X3b: missing ${description}: ${needle}")
  endif()
endfunction()

function(forbid_text text needle description)
  string(FIND "${text}" "${needle}" offset)
  if(NOT offset EQUAL -1)
    message(FATAL_ERROR "#563 X3b: ${description}: ${needle}")
  endif()
endfunction()

function(require_order text first second description)
  string(FIND "${text}" "${first}" a)
  string(FIND "${text}" "${second}" b)
  if(a EQUAL -1 OR b EQUAL -1 OR NOT a LESS b)
    message(FATAL_ERROR "#563 X3b: order ${description}: '${first}' must come before '${second}'")
  endif()
endfunction()

function(between text first second out_var)
  string(FIND "${text}" "${first}" a)
  if(a EQUAL -1)
    message(FATAL_ERROR "#563 X3b: region not found: '${first}'")
  endif()
  string(SUBSTRING "${text}" ${a} -1 rest)
  string(FIND "${rest}" "${second}" b)
  if(b EQUAL -1)
    message(FATAL_ERROR "#563 X3b: region end not found: '${second}'")
  endif()
  string(SUBSTRING "${rest}" 0 ${b} region)
  set(${out_var} "${region}" PARENT_SCOPE)
endfunction()

read_source("PlayerbotAIConfig.h" config_h)
read_source("PlayerbotAIConfig.cpp" config_cpp)
read_source("aiplayerbot.conf.dist.in" conf_dist)
read_source("PlayerbotAI.h" ai_h)
read_source("PlayerbotAI.cpp" ai_cpp)
read_source("RandomPlayerbotMgr.cpp" mgr)
read_source("X3bSnapshotPolicy.h" policy)
read_source("strategy/values/AttackersValue.cpp" attackers)

# Switch default off, documented.
require_text("${config_h}" "bool x3bPublishedTargets = false;" "member default off")
require_text("${config_cpp}" "x3bPublishedTargets = config.GetBoolDefault(\"AiPlayerbot.X3b.PublishedTargets\", false);" "config default 0")
require_text("${conf_dist}" "AiPlayerbot.X3b.PublishedTargets = 0" "documented")

# The snapshot is immutable and swapped under a mutex; the old one is released outside it.
require_text("${ai_h}" "std::shared_ptr<PublishedTargets const> publishedTargets;" "const snapshot pointer")
require_text("${ai_h}" "mutable std::mutex publishedTargetsMutex;" "pointer mutex")
between("${ai_cpp}" "void PlayerbotAI::PublishTargets(" "std::shared_ptr<PlayerbotAI::PublishedTargets const> PlayerbotAI::GetPublishedTargets() const" publish)
require_order("${publish}" "std::scoped_lock lock(publishedTargetsMutex);" "previous.swap(publishedTargets);" "swap under the lock")
require_order("${publish}" "publishedTargets = std::move(snapshot);\n    }" "// previous is released here" "old snapshot released after the lock")
between("${ai_cpp}" "std::shared_ptr<PlayerbotAI::PublishedTargets const> PlayerbotAI::GetPublishedTargets() const" "\n}\n" get_snapshot)
require_order("${get_snapshot}" "std::scoped_lock lock(publishedTargetsMutex);" "return publishedTargets;" "copy under the lock")
require_text("${policy}" "return uint32_t(nowMs - publishedMs) <= MaxAgeMs;" "wrap-safe age check")

# AddTargetsOf(Player*): another bot's targets only from its snapshot.
between("${attackers}" "void AttackersValue::AddTargetsOf(Player* player," "// Get the current attackers of the player" add_targets)
require_text("${add_targets}" "bool const otherBot = playerBot && playerBot != ai;" "other bot detection")
between("${add_targets}" "if (otherBot && sPlayerbotAIConfig.x3bPublishedTargets)" "else if (playerBot)" read_branch)
require_text("${read_branch}" "playerBot->GetPublishedTargets();" "snapshot read")
foreach(forbidden "PAI_VALUE" "GetAiObjectContext" "AI_VALUE")
  forbid_text("${read_branch}" "${forbidden}" "the snapshot branch must not touch a value context")
endforeach()
require_order("${read_branch}" "if (!snapshot)" "x3b::SnapshotCount(x3b::SnapshotMissing)" "missing counted")
require_order("${read_branch}" "!x3b::Fresh(WorldTimer::getMSTime(), snapshot->publishedMs)" "x3b::SnapshotCount(x3b::SnapshotStale)" "stale counted")
require_order("${add_targets}" "if (otherBot && sPlayerbotAIConfig.x3bPublishedTargets)" "PAI_VALUE2(std::list<ObjectGuid>, \"possible targets\"" "snapshot branch before the old path")
between("${add_targets}" "else if (playerBot)" "// Add the pull and attack targets" old_branch)
require_order("${old_branch}" "PAI_VALUE2(std::list<ObjectGuid>, \"possible targets\"" "if (!otherBot && sPlayerbotAIConfig.x3bPublishedTargets)" "publish after the own read")
require_order("${old_branch}" "if (!otherBot && sPlayerbotAIConfig.x3bPublishedTargets)" "ai->PublishTargets(std::move(snapshot));" "publish only our own targets")

# Site 2: GroupBool AND/OR/COUNT ask the member's board instead of evaluating on its context.
read_source("strategy/values/GroupValues.cpp" group)
require_text("${config_h}" "bool x3bPublishedConditions = false;" "site 2 member default off")
require_text("${config_cpp}" "x3bPublishedConditions = config.GetBoolDefault(\"AiPlayerbot.X3b.PublishedConditions\", false);" "site 2 config default 0")
require_text("${conf_dist}" "AiPlayerbot.X3b.PublishedConditions = 0" "site 2 documented")
between("${group}" "int MemberCondition(PlayerbotAI* ai, PlayerbotAI* memberAi, std::string const& condition)" "std::list<ObjectGuid> GroupMembersValue::Calculate()" member_condition)
require_order("${member_condition}" "if (memberAi != ai && sPlayerbotAIConfig.x3bPublishedConditions)" "memberAi->GetConditionBoard().Read(condition, WorldTimer::getMSTime());" "board read behind the switch")
require_order("${member_condition}" "memberAi->GetConditionBoard().Read(" "return memberAi->GetAiObjectContext()->GetValue<bool>(\"and\", condition)->Get() ? 1 : 0;" "old evaluation only after the board branch")
between("${member_condition}" "if (memberAi != ai && sPlayerbotAIConfig.x3bPublishedConditions)" "return memberAi->GetAiObjectContext()" board_branch)
forbid_text("${board_branch}" "GetAiObjectContext" "the board branch must not touch the member's context")
string(REGEX MATCHALL "PAI_VALUE2\\(bool, *\"and\"" direct_and "${group}")
list(LENGTH direct_and direct_count)
if(NOT direct_count EQUAL 0)
  message(FATAL_ERROR "#563 X3b: GroupBool values must go through MemberCondition (found ${direct_count} direct PAI_VALUE2 \"and\")")
endif()
set(skip_count 0)
set(skip_rest "${group}")
while(TRUE)
  string(FIND "${skip_rest}" "MemberCondition(ai, GetBotAI(player), getQualifier());\n        if (condition < 0)\n            continue;" skip_at)
  if(skip_at EQUAL -1)
    break()
  endif()
  math(EXPR skip_count "${skip_count} + 1")
  math(EXPR skip_at "${skip_at} + 1")
  string(SUBSTRING "${skip_rest}" ${skip_at} -1 skip_rest)
endwhile()
if(NOT skip_count EQUAL 3)
  message(FATAL_ERROR "#563 X3b: AND/OR/COUNT must each skip a member without an answer (found ${skip_count})")
endif()
between("${ai_cpp}" "void PlayerbotAI::HandleQueuedBotPackets()" "void PlayerbotAI::QueueContextWrite(" drain)
require_order("${drain}" "if (sPlayerbotAIConfig.x3bPublishedConditions && conditionBoard.HasRequests())" "conditionBoard.Refresh(WorldTimer::getMSTime()," "owner answers behind the switch")
# The board evaluates outside its lock, so no thread holds two board locks.
between("${policy}" "void Refresh(uint32_t nowMs, Evaluate evaluate)" "private:" refresh)
between("${refresh}" "if (due.empty())" "for (auto const& [condition, value] : computed)" evaluate_block)
require_text("${evaluate_block}" "computed.emplace_back(condition, bool(evaluate(condition)));" "evaluation")
string(REGEX MATCHALL "std::scoped_lock lock\\(mutex\\)" eval_locks "${evaluate_block}")
list(LENGTH eval_locks eval_lock_count)
if(NOT eval_lock_count EQUAL 1)
  message(FATAL_ERROR "#563 X3b: the evaluation must run between the two lock blocks (locks in region: ${eval_lock_count})")
endif()
require_order("${evaluate_block}" "computed.emplace_back(condition, bool(evaluate(condition)));" "std::scoped_lock lock(mutex);" "lock taken only after the evaluation")
require_text("${policy}" "else if (requests.size() < MaxConditionRequests)" "bounded registrations")

# Site 3: GroupReadyValue reads another bot's follow/wander from its published flag, not its engine.
require_text("${ai_h}" "std::atomic<bool> publishedFollowing{ true };" "published follow flag, waits until the first publish")
require_order("${drain}" "if (sPlayerbotAIConfig.x3bPublishedConditions)\n        publishedFollowing.store(HasStrategy(\"follow\", BotState::BOT_STATE_NON_COMBAT) ||" "HasStrategy(\"wander\", BotState::BOT_STATE_NON_COMBAT), std::memory_order_relaxed);" "owner publishes behind the switch")
between("${group}" "bool GroupReadyValue::Calculate()" "if (!member->IsAlive() && isFollowing)" group_ready)
require_order("${group_ready}" "? ((memberAi != ai && sPlayerbotAIConfig.x3bPublishedConditions)\n                    ? memberAi->PublishedFollowing()" ": (memberAi->HasStrategy(\"follow\", BotState::BOT_STATE_NON_COMBAT) ||" "flag for other bots, own engine only for itself or off")

# Minute line, only with a switch.
require_order("${mgr}" "if (sPlayerbotAIConfig.x3bPublishedTargets || sPlayerbotAIConfig.x3bPublishedConditions)" "[X3bSnapshot] hit=%llu stale=%llu missing=%llu max_age_ms=%u cond_hit=%llu cond_miss=%llu cond_dropped=%llu cond_evaluated=%llu" "minute line behind the switches")

message(STATUS "x3b_published_targets source contract passed")
