function(require_text text needle description)
  string(FIND "${text}" "${needle}" offset)
  if(offset EQUAL -1)
    message(FATAL_ERROR "Missing ${description}: ${needle}")
  endif()
endfunction()

file(READ "${PB_SOURCE_DIR}/strategy/triggers/ZoneEscapeTriggers.cpp" triggers)
file(READ "${PB_SOURCE_DIR}/strategy/actions/ZoneEscapeActions.cpp" actions)
file(READ "${PB_SOURCE_DIR}/strategy/generic/TravelStrategy.cpp" travel)
file(READ "${PB_SOURCE_DIR}/strategy/triggers/TriggerContext.h" trigger_context)
file(READ "${PB_SOURCE_DIR}/strategy/actions/ActionContext.h" action_context)
file(READ "${PB_SOURCE_DIR}/PlayerbotAIConfig.cpp" config_source)
file(READ "${PB_SOURCE_DIR}/aiplayerbot.conf.dist.in" config_template)

# #307 zone escape: roster bots on their own, real area level, #129 hearth rule.
require_text("${triggers}" "IsPersistentRosterMember(bot->GetGUIDLow()) && !ai->HasRealPlayerMaster()" "roster bots on their own")
require_text("${triggers}" "WorldPosition(bot).getAreaLevel()" "real area level")
require_text("${triggers}" "AI_VALUE2(bool, \"action useful\", \"hearthstone\")" "hearthstone only when useful (#129 bind check)")
require_text("${triggers}" "zoneEscapeCooldownSeconds" "cooldown")
require_text("${triggers}" "PLAYER_FLAGS_RESTING" "cities and inns exempt")
# Only the hearthstone teleports; otherwise a new target under the normal rules.
require_text("${actions}" "DoSpecificAction(\"hearthstone\"" "hearthstone")
require_text("${actions}" "SetStatus(TravelStatus::TRAVEL_STATUS_EXPIRED)" "new travel target")
require_text("${actions}" "SET_AI_VALUE2(time_t, \"manual time\", \"zone escape\"" "cooldown starts on every attempt")
require_text("${actions}" "[ZoneEscape] state=%s reason=%s" "visible diagnostics")
require_text("${travel}" "\"zone escape\", 7.0f" "ahead of other travel decisions")
require_text("${trigger_context}" "creators[\"zone escape\"]" "trigger registered")
require_text("${action_context}" "creators[\"zone escape\"]" "action registered")
require_text("${config_source}" "\"AiPlayerbot.ZoneEscape.Enabled\", false" "default off")
require_text("${config_template}" "AiPlayerbot.ZoneEscape.Enabled = 0" "documented switch")
