// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 33, boss 4278 (Commander Springvale), 10 anchors over 160yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute33_4278()
{
    DungeonClearRouteRegistry::Register(33, DUNGEON_DIFFICULTY_NORMAL, 4278,
        {
            { -236.06f, 2373.39f, 97.41f },
            { -240.28f, 2354.87f, 96.93f },
            { -248.02f, 2337.11f, 96.91f },
            { -251.91f, 2328.28f, 96.97f },
            { -268.50f, 2322.95f, 96.10f },
            { -285.79f, 2314.84f, 93.40f },
            { -293.35f, 2298.12f, 91.91f },
            { -283.49f, 2278.09f, 96.03f },
            { -268.00f, 2271.52f, 97.15f },
            { -252.54f, 2261.35f, 100.22f },
        });
}
