// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 816, boss 62070 (Overlord Blackheart), 30 anchors over 478yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute816_62070()
{
    DungeonClearRouteRegistry::Register(816, DUNGEON_DIFFICULTY_NORMAL, 62070,
        {
            { -6594.77f, -3993.72f, 216.96f },
            { -6592.61f, -4010.29f, 216.78f },
            { -6594.00f, -4027.07f, 217.81f },
            { -6589.91f, -4043.19f, 219.88f },
            { -6585.29f, -4060.95f, 222.17f },
            { -6580.91f, -4077.76f, 224.33f },
            { -6575.90f, -4097.10f, 226.82f },
            { -6572.31f, -4116.01f, 228.95f },
            { -6568.00f, -4132.04f, 229.01f },
            { -6565.16f, -4151.74f, 229.04f },
            { -6559.20f, -4167.54f, 229.52f },
            { -6550.67f, -4182.01f, 229.92f },
            { -6541.59f, -4197.50f, 230.74f },
            { -6526.88f, -4215.16f, 232.53f },
            { -6514.75f, -4227.51f, 233.92f },
            { -6504.27f, -4241.60f, 235.17f },
            { -6490.09f, -4255.26f, 237.09f },
            { -6473.14f, -4260.23f, 243.79f },
            { -6465.24f, -4262.68f, 248.65f },
            { -6457.08f, -4265.20f, 253.49f },
            { -6448.62f, -4273.82f, 259.27f },
            { -6443.51f, -4280.57f, 262.80f },
            { -6424.80f, -4286.17f, 263.08f },
            { -6408.19f, -4289.14f, 263.21f },
            { -6391.64f, -4290.74f, 264.17f },
            { -6375.88f, -4296.25f, 265.44f },
            { -6359.53f, -4301.71f, 265.89f },
            { -6342.06f, -4306.10f, 266.17f },
            { -6323.24f, -4311.32f, 266.17f },
            { -6315.47f, -4313.39f, 266.17f },
        });
}
