// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 33, boss 4274 (Fenrus the Devourer), 29 anchors over 424yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute33_4274()
{
    DungeonClearRouteRegistry::Register(33, DUNGEON_DIFFICULTY_NORMAL, 4274,
        {
            { -240.60f, 2144.53f, 100.03f },
            { -254.78f, 2132.98f, 100.03f },
            { -255.06f, 2115.25f, 100.16f },
            { -233.84f, 2105.72f, 97.39f },
            { -212.45f, 2101.44f, 98.13f },
            { -199.31f, 2120.88f, 97.42f },
            { -190.09f, 2139.07f, 97.39f },
            { -186.51f, 2155.56f, 97.39f },
            { -181.13f, 2177.56f, 97.75f },
            { -171.41f, 2177.48f, 94.58f },
            { -152.37f, 2166.40f, 94.04f },
            { -142.39f, 2164.87f, 94.04f },
            { -146.55f, 2173.08f, 99.75f },
            { -154.30f, 2177.44f, 102.28f },
            { -153.43f, 2185.00f, 106.53f },
            { -135.46f, 2180.32f, 112.51f },
            { -113.35f, 2170.92f, 108.49f },
            { -104.19f, 2166.91f, 104.94f },
            { -109.58f, 2157.23f, 101.64f },
            { -126.45f, 2157.27f, 101.76f },
            { -142.18f, 2162.55f, 106.21f },
            { -157.38f, 2168.57f, 109.18f },
            { -171.98f, 2176.87f, 109.26f },
            { -176.29f, 2186.42f, 111.98f },
            { -183.15f, 2180.92f, 116.12f },
            { -174.98f, 2184.27f, 120.99f },
            { -182.80f, 2180.97f, 126.17f },
            { -166.65f, 2180.04f, 129.26f },
            { -157.71f, 2178.25f, 128.88f },
        });
}
