// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 43, boss 3670 (Lord Pythas), 26 anchors over 385yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute43_3670()
{
    DungeonClearRouteRegistry::Register(43, DUNGEON_DIFFICULTY_NORMAL, 3670,
        {
            { -80.06f, 35.16f, -31.04f },
            { -78.91f, 26.76f, -31.06f },
            { -90.98f, 7.81f, -30.75f },
            { -95.77f, 0.69f, -30.24f },
            { -113.22f, 1.92f, -28.77f },
            { -122.23f, -5.63f, -27.90f },
            { -117.83f, -22.08f, -27.93f },
            { -102.96f, -36.31f, -32.66f },
            { -93.40f, -35.65f, -48.06f },
            { -91.73f, -43.62f, -60.24f },
            { -96.84f, -58.86f, -65.69f },
            { -100.35f, -75.32f, -70.58f },
            { -102.60f, -93.83f, -75.35f },
            { -98.52f, -109.72f, -77.81f },
            { -88.48f, -124.79f, -78.82f },
            { -73.61f, -140.14f, -78.94f },
            { -60.44f, -151.54f, -78.35f },
            { -45.35f, -163.05f, -76.65f },
            { -38.20f, -180.55f, -74.20f },
            { -33.62f, -187.77f, -73.60f },
            { -29.15f, -180.86f, -74.11f },
            { -17.00f, -182.51f, -76.37f },
            { -2.62f, -199.31f, -79.86f },
            { 12.47f, -210.36f, -81.51f },
            { 23.53f, -222.74f, -80.84f },
            { 28.92f, -233.53f, -78.98f },
        });
}
