// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 48, boss 4887 (Ghamoo-ra), 23 anchors over 378yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute48_4887()
{
    DungeonClearRouteRegistry::Register(48, DUNGEON_DIFFICULTY_NORMAL, 4887,
        {
            { -151.89f, 106.96f, -39.87f },
            { -150.45f, 90.20f, -42.64f },
            { -158.97f, 77.70f, -45.95f },
            { -177.61f, 66.07f, -48.64f },
            { -196.11f, 51.17f, -52.21f },
            { -212.98f, 41.38f, -52.73f },
            { -227.95f, 34.70f, -54.03f },
            { -243.35f, 44.57f, -53.45f },
            { -258.41f, 50.62f, -54.20f },
            { -265.96f, 56.61f, -57.78f },
            { -280.84f, 64.01f, -62.63f },
            { -301.14f, 65.46f, -64.38f },
            { -319.46f, 66.68f, -63.43f },
            { -330.75f, 79.00f, -60.30f },
            { -325.13f, 94.34f, -58.36f },
            { -321.26f, 113.43f, -52.88f },
            { -322.37f, 121.58f, -48.93f },
            { -339.17f, 130.59f, -49.13f },
            { -357.13f, 140.21f, -50.07f },
            { -374.60f, 149.57f, -51.87f },
            { -378.02f, 159.30f, -55.32f },
            { -391.33f, 172.35f, -56.74f },
            { -405.54f, 181.27f, -56.22f },
        });
}
