// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 33, boss 3914 (Rethilgore), 8 anchors over 110yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute33_3914()
{
    DungeonClearRouteRegistry::Register(33, DUNGEON_DIFFICULTY_NORMAL, 3914,
        {
            { -229.13f, 2109.18f, 76.89f },
            { -212.38f, 2104.60f, 77.00f },
            { -206.43f, 2112.43f, 81.99f },
            { -197.95f, 2129.29f, 82.62f },
            { -195.61f, 2138.05f, 85.40f },
            { -213.70f, 2143.17f, 90.47f },
            { -232.10f, 2144.55f, 89.21f },
            { -249.36f, 2140.95f, 86.89f },
        });
}
