// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 43, boss 3669 (Lord Cobrahn), 54 anchors over 856yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute43_3669()
{
    DungeonClearRouteRegistry::Register(43, DUNGEON_DIFFICULTY_NORMAL, 3669,
        {
            { -163.49f, 132.90f, -73.66f },
            { -146.59f, 135.95f, -73.20f },
            { -125.65f, 152.00f, -74.94f },
            { -117.28f, 169.20f, -76.26f },
            { -103.07f, 180.59f, -78.29f },
            { -99.49f, 188.66f, -78.45f },
            { -91.25f, 191.71f, -82.70f },
            { -84.14f, 195.97f, -89.23f },
            { -66.53f, 204.06f, -92.92f },
            { -49.52f, 203.76f, -95.70f },
            { -32.93f, 204.47f, -96.60f },
            { -25.44f, 208.45f, -98.67f },
            { -20.16f, 226.17f, -103.28f },
            { -22.85f, 248.29f, -104.15f },
            { -26.54f, 265.39f, -104.43f },
            { -37.47f, 289.16f, -104.55f },
            { -47.67f, 303.35f, -105.18f },
            { -58.61f, 315.86f, -106.50f },
            { -66.85f, 330.56f, -106.41f },
            { -69.07f, 346.81f, -106.14f },
            { -66.01f, 363.03f, -105.56f },
            { -62.57f, 381.59f, -105.64f },
            { -58.26f, 397.77f, -105.54f },
            { -49.11f, 419.93f, -105.49f },
            { -42.19f, 434.85f, -105.45f },
            { -28.96f, 447.15f, -101.66f },
            { -15.30f, 457.13f, -94.86f },
            { -7.77f, 460.96f, -90.96f },
            { 0.63f, 462.11f, -84.35f },
            { 4.42f, 460.58f, -79.08f },
            { 1.11f, 442.33f, -72.98f },
            { -0.96f, 434.11f, -69.86f },
            { -4.14f, 414.07f, -63.67f },
            { -3.20f, 406.09f, -61.26f },
            { 13.51f, 405.65f, -59.29f },
            { 30.34f, 406.23f, -60.21f },
            { 45.48f, 413.86f, -63.51f },
            { 54.38f, 431.96f, -64.16f },
            { 49.73f, 449.06f, -65.04f },
            { 40.71f, 465.30f, -66.30f },
            { 31.49f, 478.08f, -65.86f },
            { 16.48f, 492.51f, -60.56f },
            { -8.21f, 490.28f, -56.12f },
            { -24.20f, 482.57f, -54.83f },
            { -43.53f, 477.07f, -54.99f },
            { -60.84f, 476.83f, -59.03f },
            { -69.92f, 475.13f, -63.08f },
            { -83.73f, 465.48f, -68.10f },
            { -101.10f, 460.82f, -71.24f },
            { -109.31f, 445.76f, -72.64f },
            { -116.41f, 429.14f, -72.56f },
            { -119.68f, 421.49f, -72.63f },
            { -127.00f, 424.98f, -72.43f },
            { -139.03f, 418.93f, -72.08f },
        });
}
