// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 43, boss 5775 (Verdan the Everliving), 4 anchors over 52yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute43_5775()
{
    DungeonClearRouteRegistry::Register(43, DUNGEON_DIFFICULTY_NORMAL, 5775,
        {
            { -120.55f, -17.76f, -27.86f },
            { -108.83f, -4.72f, -28.95f },
            { -96.99f, 8.41f, -30.61f },
            { -84.98f, 20.57f, -30.83f },
        });
}
