// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 43, boss 3669 (Lord Cobrahn), 40 anchors over 526yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute43_3669()
{
    DungeonClearRouteRegistry::Register(43, DUNGEON_DIFFICULTY_NORMAL, 3669,
        {
            { -44.78f, 305.46f, -105.81f },
            { -59.22f, 316.25f, -106.52f },
            { -74.42f, 327.95f, -107.92f },
            { -69.88f, 345.04f, -106.19f },
            { -65.81f, 361.61f, -105.66f },
            { -62.31f, 377.64f, -105.38f },
            { -59.44f, 393.73f, -105.93f },
            { -60.92f, 403.00f, -106.37f },
            { -49.34f, 419.13f, -105.48f },
            { -40.58f, 433.82f, -104.15f },
            { -34.81f, 441.20f, -103.07f },
            { -28.24f, 440.37f, -98.31f },
            { -22.29f, 434.83f, -91.69f },
            { -16.21f, 429.16f, -84.91f },
            { -12.15f, 425.38f, -80.40f },
            { -6.08f, 419.71f, -73.63f },
            { 0.19f, 413.87f, -66.66f },
            { 6.21f, 408.26f, -59.95f },
            { 23.44f, 405.32f, -59.92f },
            { 39.73f, 402.98f, -60.43f },
            { 46.98f, 408.27f, -63.13f },
            { 48.07f, 416.25f, -63.76f },
            { 55.81f, 418.72f, -63.83f },
            { 61.16f, 428.67f, -64.51f },
            { 54.11f, 444.12f, -64.65f },
            { 47.52f, 459.66f, -65.50f },
            { 46.28f, 467.65f, -65.37f },
            { 38.16f, 469.20f, -66.23f },
            { 28.26f, 482.21f, -64.88f },
            { 11.61f, 493.17f, -59.16f },
            { -4.92f, 495.35f, -56.53f },
            { -13.27f, 496.48f, -55.57f },
            { -30.92f, 481.60f, -52.98f },
            { -51.45f, 474.80f, -56.91f },
            { -67.88f, 474.73f, -62.19f },
            { -76.05f, 471.84f, -65.60f },
            { -89.58f, 461.70f, -69.84f },
            { -102.56f, 451.20f, -71.84f },
            { -106.41f, 433.16f, -73.40f },
            { -111.19f, 426.30f, -72.98f },
        });
}
