// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 43, boss 5775 (Verdan the Everliving), 22 anchors over 336yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute43_5775()
{
    DungeonClearRouteRegistry::Register(43, DUNGEON_DIFFICULTY_NORMAL, 5775,
        {
            { -163.49f, 132.90f, -73.66f },
            { -144.89f, 130.99f, -76.41f },
            { -136.34f, 130.45f, -77.90f },
            { -127.05f, 145.40f, -75.56f },
            { -120.47f, 160.63f, -75.00f },
            { -108.87f, 176.90f, -78.32f },
            { -94.95f, 191.88f, -80.92f },
            { -84.57f, 195.57f, -89.07f },
            { -79.16f, 201.72f, -93.58f },
            { -59.67f, 203.24f, -94.29f },
            { -43.02f, 200.74f, -96.26f },
            { -26.37f, 192.68f, -99.91f },
            { -22.39f, 182.59f, -103.66f },
            { -18.29f, 172.22f, -104.81f },
            { -27.95f, 149.93f, -104.66f },
            { -36.50f, 130.66f, -107.44f },
            { -47.12f, 115.89f, -107.17f },
            { -57.05f, 102.14f, -105.25f },
            { -64.71f, 91.64f, -105.86f },
            { -60.21f, 84.40f, -106.16f },
            { -70.94f, 60.90f, -28.76f },
            { -74.76f, 50.86f, -30.19f },
        });
}
