// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 36, boss 646 (Mr. Smite), 30 anchors over 462yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute36_646()
{
    DungeonClearRouteRegistry::Register(36, DUNGEON_DIFFICULTY_NORMAL, 646,
        {
            { -86.99f, -568.61f, 51.86f },
            { -106.61f, -577.01f, 51.23f },
            { -122.92f, -570.81f, 51.23f },
            { -146.52f, -563.71f, 51.23f },
            { -162.21f, -557.61f, 51.23f },
            { -174.79f, -547.61f, 51.23f },
            { -187.08f, -532.84f, 51.23f },
            { -201.51f, -540.57f, 51.23f },
            { -202.23f, -548.88f, 51.23f },
            { -191.27f, -563.53f, 51.23f },
            { -185.56f, -579.37f, 46.76f },
            { -176.05f, -581.73f, 19.31f },
            { -158.27f, -582.97f, 19.31f },
            { -139.83f, -585.67f, 18.42f },
            { -133.42f, -599.47f, 16.06f },
            { -128.45f, -617.16f, 13.38f },
            { -121.72f, -632.79f, 13.10f },
            { -113.15f, -648.98f, 8.26f },
            { -101.35f, -668.64f, 7.42f },
            { -90.56f, -682.59f, 7.60f },
            { -82.40f, -689.34f, 1.73f },
            { -74.37f, -701.34f, -4.78f },
            { -69.60f, -708.78f, -10.62f },
            { -59.32f, -724.97f, -8.99f },
            { -50.69f, -738.75f, -9.64f },
            { -41.61f, -753.18f, -13.32f },
            { -32.68f, -767.02f, -10.62f },
            { -23.15f, -773.92f, -6.51f },
            { -15.38f, -776.48f, -1.91f },
            { -7.14f, -777.01f, 6.98f },
        });
}
