// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 43, boss 3671 (Lady Anacondra), 13 anchors over 192yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute43_3671()
{
    DungeonClearRouteRegistry::Register(43, DUNGEON_DIFFICULTY_NORMAL, 3671,
        {
            { -163.49f, 132.90f, -73.66f },
            { -144.37f, 131.01f, -76.14f },
            { -127.76f, 141.73f, -76.98f },
            { -120.82f, 158.77f, -76.37f },
            { -110.81f, 173.29f, -79.14f },
            { -101.25f, 186.77f, -79.83f },
            { -85.71f, 193.63f, -88.50f },
            { -82.68f, 201.74f, -92.17f },
            { -67.01f, 203.83f, -93.68f },
            { -59.31f, 207.04f, -94.04f },
            { -56.92f, 228.23f, -92.38f },
            { -55.17f, 246.84f, -92.57f },
            { -44.05f, 247.68f, -92.45f },
        });
}
