// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 33, boss 3887 (Baron Silverlaine), 5 anchors over 65yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute33_3887()
{
    DungeonClearRouteRegistry::Register(33, DUNGEON_DIFFICULTY_NORMAL, 3887,
        {
            { -195.47f, 2251.24f, 76.80f },
            { -210.76f, 2261.06f, 76.12f },
            { -227.38f, 2270.35f, 75.07f },
            { -244.69f, 2280.42f, 75.55f },
            { -252.66f, 2283.86f, 75.12f },
        });
}
