// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 43, boss 3653 (Kresh), 8 anchors over 115yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute43_3653()
{
    DungeonClearRouteRegistry::Register(43, DUNGEON_DIFFICULTY_NORMAL, 3653,
        {
            { -45.88f, 144.19f, -92.21f },
            { -41.72f, 159.95f, -95.40f },
            { -40.85f, 177.20f, -96.36f },
            { -40.44f, 185.42f, -96.37f },
            { -29.18f, 200.03f, -97.23f },
            { -20.75f, 214.12f, -101.12f },
            { -21.71f, 191.98f, -104.43f },
            { -18.88f, 175.85f, -105.30f },
        });
}
