// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 47, boss 4424 (Aggem Thorncurse), 43 anchors over 652yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute47_4424()
{
    DungeonClearRouteRegistry::Register(47, DUNGEON_DIFFICULTY_NORMAL, 4424,
        {
            { 2140.72f, 1586.28f, 80.86f },
            { 2135.01f, 1576.52f, 82.16f },
            { 2117.60f, 1564.07f, 81.19f },
            { 2107.67f, 1559.54f, 81.47f },
            { 2101.84f, 1552.64f, 81.62f },
            { 2087.63f, 1564.62f, 81.59f },
            { 2078.47f, 1578.34f, 82.72f },
            { 2069.23f, 1592.18f, 78.45f },
            { 2058.79f, 1607.81f, 77.80f },
            { 2049.72f, 1621.60f, 81.56f },
            { 2048.12f, 1639.97f, 84.16f },
            { 2032.38f, 1652.41f, 82.11f },
            { 2024.44f, 1653.87f, 83.02f },
            { 2010.65f, 1644.35f, 81.00f },
            { 2004.63f, 1638.41f, 81.29f },
            { 1997.94f, 1622.96f, 82.33f },
            { 1995.81f, 1614.34f, 84.20f },
            { 2000.60f, 1596.79f, 81.14f },
            { 2004.52f, 1580.20f, 82.10f },
            { 2012.07f, 1562.13f, 83.25f },
            { 2016.82f, 1546.49f, 81.64f },
            { 2023.26f, 1525.43f, 80.38f },
            { 2027.90f, 1506.64f, 76.54f },
            { 2029.35f, 1497.91f, 73.49f },
            { 2038.16f, 1480.24f, 69.00f },
            { 2052.45f, 1468.88f, 68.18f },
            { 2067.25f, 1461.32f, 67.66f },
            { 2081.40f, 1444.21f, 67.52f },
            { 2099.16f, 1440.40f, 64.54f },
            { 2116.31f, 1443.76f, 65.65f },
            { 2124.60f, 1447.99f, 66.02f },
            { 2128.63f, 1458.27f, 66.07f },
            { 2141.22f, 1469.82f, 67.41f },
            { 2151.69f, 1486.30f, 68.31f },
            { 2155.09f, 1494.26f, 68.45f },
            { 2171.08f, 1503.66f, 72.28f },
            { 2167.91f, 1513.76f, 68.51f },
            { 2162.06f, 1519.39f, 72.21f },
            { 2145.73f, 1512.03f, 73.29f },
            { 2134.71f, 1498.18f, 73.49f },
            { 2123.19f, 1485.12f, 73.56f },
            { 2112.12f, 1472.43f, 73.88f },
            { 2106.72f, 1465.92f, 73.91f },
        });
}
