// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 43, boss 5775 (Verdan the Everliving), 18 anchors over 337yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute43_5775()
{
    DungeonClearRouteRegistry::Register(43, DUNGEON_DIFFICULTY_NORMAL, 5775,
        {
            { -163.49f, 132.90f, -73.66f },
            { -141.44f, 130.71f, -76.75f },
            { -128.15f, 143.59f, -74.97f },
            { -118.20f, 163.81f, -76.44f },
            { -107.18f, 178.73f, -79.22f },
            { -94.82f, 191.93f, -79.28f },
            { -85.17f, 194.26f, -88.68f },
            { -82.06f, 201.93f, -92.88f },
            { -64.51f, 202.30f, -94.44f },
            { -45.30f, 200.09f, -96.03f },
            { -26.41f, 191.82f, -100.62f },
            { -24.91f, 173.47f, -103.97f },
            { -26.71f, 156.55f, -104.48f },
            { -32.56f, 139.78f, -104.83f },
            { -44.15f, 120.01f, -105.80f },
            { -54.87f, 105.16f, -105.28f },
            { -74.96f, 50.24f, -29.94f },
            { -78.06f, 42.14f, -30.56f },
        });
}
