// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 36, boss 642 (Sneed's Shredder), 11 anchors over 146yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute36_642()
{
    DungeonClearRouteRegistry::Register(36, DUNGEON_DIFFICULTY_NORMAL, 642,
        {
            { -205.51f, -454.96f, 54.79f },
            { -197.11f, -452.21f, 54.61f },
            { -192.16f, -470.10f, 54.16f },
            { -196.16f, -488.34f, 53.83f },
            { -196.27f, -500.09f, 53.68f },
            { -215.17f, -496.43f, 50.38f },
            { -224.79f, -492.72f, 49.06f },
            { -227.99f, -485.01f, 49.19f },
            { -250.66f, -485.75f, 49.37f },
            { -268.70f, -485.55f, 49.51f },
            { -276.33f, -479.16f, 49.64f },
        });
}
