// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 48, boss 62530 (Velthelaxx the Defiler), 42 anchors over 668yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute48_62530()
{
    DungeonClearRouteRegistry::Register(48, DUNGEON_DIFFICULTY_NORMAL, 62530,
        {
            { -424.56f, 37.73f, -48.19f },
            { -438.73f, 25.63f, -49.80f },
            { -452.32f, 16.56f, -48.30f },
            { -467.82f, 9.36f, -48.20f },
            { -483.04f, 2.76f, -47.16f },
            { -497.30f, -6.16f, -46.38f },
            { -511.31f, -20.62f, -44.31f },
            { -523.16f, -32.39f, -40.31f },
            { -541.88f, -38.98f, -39.46f },
            { -562.10f, -39.36f, -37.06f },
            { -580.07f, -40.05f, -33.26f },
            { -602.40f, -41.55f, -27.22f },
            { -621.01f, -44.61f, -22.07f },
            { -620.55f, -32.55f, -22.08f },
            { -637.47f, -25.29f, -18.95f },
            { -654.37f, -20.49f, -17.48f },
            { -662.78f, -6.74f, -19.84f },
            { -670.97f, 4.19f, -23.69f },
            { -680.32f, 19.45f, -28.85f },
            { -696.16f, 27.57f, -30.73f },
            { -711.28f, 32.18f, -29.89f },
            { -722.73f, 19.05f, -30.04f },
            { -720.36f, -0.14f, -31.11f },
            { -721.56f, -9.41f, -35.06f },
            { -719.08f, -26.03f, -37.14f },
            { -701.69f, -28.86f, -32.44f },
            { -682.54f, -33.74f, -29.60f },
            { -673.05f, -30.94f, -29.59f },
            { -661.86f, -35.45f, -29.93f },
            { -656.78f, -55.80f, -28.43f },
            { -650.90f, -72.83f, -29.89f },
            { -634.68f, -78.54f, -30.04f },
            { -627.87f, -94.42f, -27.88f },
            { -627.06f, -112.65f, -29.87f },
            { -626.61f, -130.68f, -28.32f },
            { -619.85f, -148.41f, -28.34f },
            { -634.37f, -156.53f, -27.18f },
            { -637.24f, -164.20f, -27.34f },
            { -634.74f, -172.44f, -27.59f },
            { -627.56f, -176.81f, -26.91f },
            { -621.03f, -171.79f, -27.65f },
            { -614.87f, -187.39f, -28.75f },
        });
}
