// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 48, boss 4831 (Lady Sarevess), 12 anchors over 161yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute48_4831()
{
    DungeonClearRouteRegistry::Register(48, DUNGEON_DIFFICULTY_NORMAL, 4831,
        {
            { -418.25f, 193.30f, -52.91f },
            { -415.22f, 201.37f, -53.30f },
            { -400.35f, 211.82f, -55.37f },
            { -386.53f, 223.89f, -61.17f },
            { -380.65f, 229.82f, -64.28f },
            { -376.11f, 246.71f, -68.08f },
            { -372.12f, 266.83f, -75.08f },
            { -359.04f, 280.83f, -76.24f },
            { -352.22f, 297.28f, -73.07f },
            { -348.07f, 313.16f, -65.57f },
            { -347.43f, 321.33f, -59.72f },
            { -350.00f, 329.33f, -55.27f },
        });
}
