// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 43, boss 61965 (Vangros), 39 anchors over 682yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute43_61965()
{
    DungeonClearRouteRegistry::Register(43, DUNGEON_DIFFICULTY_NORMAL, 61965,
        {
            { -274.81f, -310.52f, -68.51f },
            { -266.92f, -296.10f, -67.37f },
            { -257.32f, -277.32f, -65.28f },
            { -266.44f, -258.86f, -63.17f },
            { -274.22f, -241.84f, -61.54f },
            { -275.42f, -223.16f, -62.94f },
            { -274.40f, -205.38f, -61.50f },
            { -277.46f, -192.48f, -62.32f },
            { -285.40f, -191.06f, -62.80f },
            { -297.08f, -178.90f, -62.30f },
            { -306.00f, -164.56f, -59.69f },
            { -309.18f, -156.99f, -60.09f },
            { -328.15f, -153.55f, -62.00f },
            { -342.10f, -138.40f, -62.85f },
            { -347.06f, -119.28f, -63.62f },
            { -361.27f, -109.69f, -64.38f },
            { -375.26f, -95.10f, -65.35f },
            { -383.24f, -80.04f, -65.35f },
            { -390.10f, -60.18f, -65.17f },
            { -402.46f, -48.53f, -65.40f },
            { -410.41f, -28.81f, -65.29f },
            { -417.76f, -11.51f, -65.35f },
            { -435.02f, -4.63f, -65.05f },
            { -453.88f, -5.10f, -66.43f },
            { -470.57f, -10.10f, -66.68f },
            { -486.80f, -21.13f, -67.45f },
            { -498.51f, -34.96f, -67.89f },
            { -501.64f, -51.91f, -67.24f },
            { -512.06f, -68.85f, -67.52f },
            { -516.11f, -91.06f, -67.00f },
            { -517.10f, -113.26f, -69.72f },
            { -510.72f, -132.54f, -67.54f },
            { -497.39f, -147.07f, -66.21f },
            { -490.20f, -162.79f, -65.39f },
            { -487.06f, -172.57f, -65.28f },
            { -467.48f, -179.48f, -64.62f },
            { -452.97f, -188.58f, -64.67f },
            { -440.43f, -199.64f, -65.53f },
            { -427.90f, -210.70f, -66.77f },
        });
}
