// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 33, boss 61969 (Prelate Ironmane), 10 anchors over 130yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute33_61969()
{
    DungeonClearRouteRegistry::Register(33, DUNGEON_DIFFICULTY_NORMAL, 61969,
        {
            { -273.04f, 2297.58f, 76.35f },
            { -281.85f, 2305.46f, 87.50f },
            { -289.26f, 2306.84f, 91.61f },
            { -283.29f, 2322.14f, 95.87f },
            { -264.64f, 2318.62f, 95.87f },
            { -257.54f, 2314.80f, 95.96f },
            { -248.47f, 2331.41f, 97.02f },
            { -243.16f, 2352.10f, 96.93f },
            { -235.25f, 2367.02f, 96.97f },
            { -237.12f, 2377.00f, 97.42f },
        });
}
