// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 43, boss 3653 (Kresh), 12 anchors over 147yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute43_3653()
{
    DungeonClearRouteRegistry::Register(43, DUNGEON_DIFFICULTY_NORMAL, 3653,
        {
            { -65.34f, 132.72f, -89.60f },
            { -59.93f, 149.00f, -94.44f },
            { -41.89f, 147.61f, -92.83f },
            { -33.39f, 146.96f, -93.17f },
            { -31.53f, 168.01f, -96.07f },
            { -31.33f, 184.96f, -96.29f },
            { -31.22f, 193.46f, -96.27f },
            { -21.65f, 193.65f, -100.73f },
            { -25.67f, 202.90f, -98.64f },
            { -17.54f, 218.64f, -102.77f },
            { -9.98f, 223.20f, -106.16f },
            { -5.03f, 232.56f, -105.66f },
        });
}
