// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 43, boss 3671 (Lady Anacondra), 16 anchors over 217yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute43_3671()
{
    DungeonClearRouteRegistry::Register(43, DUNGEON_DIFFICULTY_NORMAL, 3671,
        {
            { -163.49f, 132.90f, -73.66f },
            { -146.04f, 136.32f, -73.16f },
            { -130.41f, 142.36f, -75.86f },
            { -121.60f, 156.53f, -76.08f },
            { -111.28f, 169.84f, -78.89f },
            { -96.79f, 185.10f, -78.03f },
            { -90.15f, 190.14f, -82.63f },
            { -86.78f, 192.31f, -87.21f },
            { -83.50f, 199.83f, -90.40f },
            { -82.25f, 209.72f, -92.94f },
            { -63.70f, 207.32f, -93.44f },
            { -57.01f, 223.88f, -92.75f },
            { -56.63f, 241.16f, -91.95f },
            { -54.51f, 260.01f, -92.84f },
            { -43.01f, 248.32f, -92.48f },
            { -38.75f, 241.14f, -92.15f },
        });
}
