// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 43, boss 3674 (Skum), 23 anchors over 339yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute43_3674()
{
    DungeonClearRouteRegistry::Register(43, DUNGEON_DIFFICULTY_NORMAL, 3674,
        {
            { 18.77f, -231.23f, -76.37f },
            { 9.35f, -244.16f, -73.70f },
            { -3.65f, -254.60f, -69.42f },
            { -12.28f, -261.45f, -67.24f },
            { -23.02f, -262.04f, -67.22f },
            { -21.75f, -250.90f, -68.94f },
            { -37.97f, -245.78f, -68.37f },
            { -54.78f, -249.06f, -68.12f },
            { -76.79f, -244.60f, -66.74f },
            { -84.38f, -247.95f, -60.77f },
            { -92.03f, -251.37f, -54.69f },
            { -94.69f, -259.22f, -55.56f },
            { -112.74f, -251.17f, -58.52f },
            { -123.38f, -246.53f, -62.41f },
            { -132.53f, -241.42f, -65.64f },
            { -148.93f, -234.13f, -69.54f },
            { -168.09f, -234.40f, -70.30f },
            { -187.28f, -247.53f, -67.95f },
            { -198.23f, -261.11f, -66.77f },
            { -209.05f, -274.49f, -65.80f },
            { -218.19f, -288.69f, -68.22f },
            { -236.44f, -288.78f, -67.77f },
            { -254.50f, -297.44f, -68.10f },
        });
}
