// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 43, boss 3670 (Lord Pythas), 39 anchors over 575yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute43_3670()
{
    DungeonClearRouteRegistry::Register(43, DUNGEON_DIFFICULTY_NORMAL, 3670,
        {
            { -75.65f, 48.41f, -30.79f },
            { -76.82f, 57.62f, -28.65f },
            { -66.75f, 75.17f, -36.90f },
            { -62.46f, 82.66f, -101.85f },
            { -58.65f, 90.12f, -103.66f },
            { -66.24f, 92.74f, -107.82f },
            { -76.24f, 79.27f, -105.60f },
            { -91.02f, 68.80f, -106.11f },
            { -107.64f, 69.21f, -107.79f },
            { -124.66f, 67.42f, -107.52f },
            { -141.60f, 67.26f, -107.54f },
            { -150.23f, 67.91f, -106.86f },
            { -158.02f, 59.54f, -106.06f },
            { -151.26f, 51.08f, -76.25f },
            { -147.16f, 30.49f, -76.37f },
            { -148.77f, 13.31f, -75.34f },
            { -149.73f, -3.93f, -75.52f },
            { -152.60f, -20.37f, -78.67f },
            { -155.43f, -36.61f, -80.29f },
            { -158.36f, -53.40f, -76.70f },
            { -163.42f, -68.60f, -71.42f },
            { -170.49f, -79.75f, -67.62f },
            { -160.57f, -83.65f, -67.29f },
            { -149.06f, -95.79f, -67.78f },
            { -132.41f, -102.20f, -70.91f },
            { -119.68f, -116.21f, -75.73f },
            { -109.34f, -129.32f, -79.17f },
            { -94.57f, -137.98f, -79.18f },
            { -78.12f, -148.04f, -79.78f },
            { -65.20f, -158.41f, -76.95f },
            { -54.32f, -170.46f, -75.03f },
            { -39.59f, -181.51f, -74.91f },
            { -26.75f, -192.83f, -74.29f },
            { -19.91f, -198.86f, -75.03f },
            { -8.37f, -198.18f, -78.43f },
            { -7.24f, -210.03f, -76.60f },
            { 5.28f, -221.07f, -77.79f },
            { 17.50f, -232.68f, -78.43f },
            { 34.26f, -239.48f, -78.99f },
        });
}
