// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 36, boss 644 (Rhahk'Zor), 14 anchors over 203yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute36_644()
{
    DungeonClearRouteRegistry::Register(36, DUNGEON_DIFFICULTY_NORMAL, 644,
        {
            { -16.40f, -383.07f, 61.78f },
            { -31.84f, -376.57f, 59.39f },
            { -47.05f, -370.33f, 56.30f },
            { -53.67f, -376.20f, 55.04f },
            { -75.77f, -374.62f, 56.40f },
            { -93.90f, -379.75f, 58.49f },
            { -107.42f, -394.77f, 58.18f },
            { -115.30f, -397.89f, 58.08f },
            { -122.53f, -393.07f, 58.62f },
            { -134.12f, -409.28f, 58.33f },
            { -153.72f, -405.28f, 58.00f },
            { -169.62f, -405.74f, 56.90f },
            { -182.81f, -418.48f, 55.07f },
            { -185.55f, -426.54f, 54.26f },
        });
}
