// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 43, boss 3653 (Kresh), 7 anchors over 96yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute43_3653()
{
    DungeonClearRouteRegistry::Register(43, DUNGEON_DIFFICULTY_NORMAL, 3653,
        {
            { -50.44f, 263.30f, -92.26f },
            { -39.54f, 251.05f, -93.07f },
            { -32.51f, 236.12f, -93.56f },
            { -27.09f, 220.40f, -96.58f },
            { -19.34f, 220.26f, -102.53f },
            { -17.36f, 242.02f, -104.85f },
            { -17.43f, 259.10f, -106.42f },
        });
}
