// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 816, boss 62068 (Slagfist Destroyer), 32 anchors over 460yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute816_62068()
{
    DungeonClearRouteRegistry::Register(816, DUNGEON_DIFFICULTY_NORMAL, 62068,
        {
            { -6285.94f, -4103.21f, 264.93f },
            { -6290.44f, -4122.44f, 264.97f },
            { -6286.86f, -4134.10f, 260.12f },
            { -6285.62f, -4138.13f, 265.19f },
            { -6280.67f, -4154.22f, 264.83f },
            { -6286.85f, -4163.11f, 264.83f },
            { -6286.64f, -4179.75f, 264.82f },
            { -6286.35f, -4196.59f, 264.73f },
            { -6288.52f, -4215.62f, 265.27f },
            { -6305.51f, -4219.45f, 264.78f },
            { -6313.55f, -4222.43f, 264.88f },
            { -6324.54f, -4235.48f, 265.21f },
            { -6333.00f, -4249.62f, 265.53f },
            { -6329.39f, -4269.62f, 265.99f },
            { -6336.00f, -4287.19f, 266.36f },
            { -6340.10f, -4296.49f, 266.20f },
            { -6347.13f, -4301.56f, 266.17f },
            { -6366.98f, -4298.73f, 265.68f },
            { -6383.75f, -4293.29f, 264.91f },
            { -6403.19f, -4288.95f, 263.30f },
            { -6424.28f, -4285.64f, 263.08f },
            { -6443.26f, -4281.29f, 263.10f },
            { -6448.79f, -4274.57f, 259.73f },
            { -6453.56f, -4267.82f, 255.56f },
            { -6460.07f, -4262.97f, 251.83f },
            { -6467.08f, -4261.08f, 247.52f },
            { -6474.80f, -4263.88f, 242.76f },
            { -6486.95f, -4264.44f, 237.93f },
            { -6498.09f, -4247.78f, 236.47f },
            { -6512.18f, -4233.44f, 234.22f },
            { -6527.53f, -4224.31f, 232.97f },
            { -6536.96f, -4209.83f, 231.50f },
        });
}
