// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 48, boss 6243 (Gelihast), 46 anchors over 726yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute48_6243()
{
    DungeonClearRouteRegistry::Register(48, DUNGEON_DIFFICULTY_NORMAL, 6243,
        {
            { -346.77f, 338.40f, -53.37f },
            { -347.92f, 321.88f, -60.05f },
            { -350.92f, 314.20f, -65.85f },
            { -354.15f, 305.90f, -71.04f },
            { -358.93f, 295.58f, -76.41f },
            { -372.73f, 284.56f, -77.90f },
            { -386.03f, 273.95f, -74.44f },
            { -401.33f, 266.40f, -68.71f },
            { -405.08f, 259.06f, -65.00f },
            { -408.83f, 251.71f, -59.98f },
            { -412.63f, 244.27f, -56.79f },
            { -416.29f, 237.09f, -54.28f },
            { -433.79f, 243.99f, -54.53f },
            { -452.57f, 233.26f, -53.75f },
            { -464.13f, 220.03f, -52.80f },
            { -466.31f, 211.72f, -53.01f },
            { -488.20f, 210.70f, -54.40f },
            { -504.80f, 210.03f, -55.73f },
            { -522.09f, 209.32f, -57.12f },
            { -541.17f, 208.55f, -58.66f },
            { -561.64f, 211.83f, -58.21f },
            { -571.35f, 209.82f, -53.37f },
            { -580.23f, 208.24f, -48.93f },
            { -597.44f, 210.49f, -50.69f },
            { -612.62f, 215.97f, -49.85f },
            { -609.38f, 197.21f, -50.92f },
            { -607.53f, 176.06f, -54.61f },
            { -610.60f, 159.65f, -56.14f },
            { -619.53f, 145.58f, -57.31f },
            { -625.57f, 121.67f, -56.32f },
            { -627.41f, 104.72f, -56.91f },
            { -621.06f, 86.13f, -56.02f },
            { -613.43f, 68.15f, -55.66f },
            { -604.46f, 49.51f, -54.06f },
            { -592.74f, 33.70f, -51.28f },
            { -579.52f, 24.26f, -48.73f },
            { -573.44f, 18.72f, -48.11f },
            { -570.70f, 2.52f, -47.54f },
            { -552.01f, 8.81f, -44.70f },
            { -533.59f, 3.20f, -40.88f },
            { -517.89f, -0.59f, -42.25f },
            { -500.76f, -2.30f, -44.88f },
            { -484.55f, 2.18f, -46.63f },
            { -469.27f, 9.36f, -47.44f },
            { -450.06f, 16.50f, -47.53f },
            { -430.49f, 20.85f, -48.64f },
        });
}
