// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 816, boss 62038 (Elder Hollowblood), 11 anchors over 140yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute816_62038()
{
    DungeonClearRouteRegistry::Register(816, DUNGEON_DIFFICULTY_NORMAL, 62038,
        {
            { -6305.66f, -4316.22f, 266.17f },
            { -6298.36f, -4312.70f, 266.69f },
            { -6278.33f, -4316.68f, 266.53f },
            { -6262.24f, -4321.39f, 266.69f },
            { -6246.70f, -4329.38f, 266.17f },
            { -6240.22f, -4324.53f, 266.17f },
            { -6231.86f, -4325.78f, 266.56f },
            { -6227.11f, -4332.30f, 266.69f },
            { -6209.54f, -4338.21f, 266.62f },
            { -6193.86f, -4343.67f, 266.24f },
            { -6177.77f, -4350.71f, 266.69f },
        });
}
