// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 43, boss 3669 (Lord Cobrahn), 45 anchors over 623yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute43_3669()
{
    DungeonClearRouteRegistry::Register(43, DUNGEON_DIFFICULTY_NORMAL, 3669,
        {
            { -29.92f, 291.21f, -105.97f },
            { -42.24f, 306.43f, -106.42f },
            { -54.75f, 317.18f, -106.57f },
            { -64.80f, 329.71f, -106.50f },
            { -67.37f, 347.39f, -106.11f },
            { -65.83f, 363.83f, -105.70f },
            { -62.06f, 381.89f, -104.91f },
            { -58.82f, 398.18f, -105.72f },
            { -58.80f, 414.94f, -106.22f },
            { -43.99f, 430.39f, -105.44f },
            { -32.89f, 443.34f, -102.86f },
            { -20.69f, 454.98f, -98.88f },
            { -16.00f, 462.46f, -96.42f },
            { -8.12f, 460.85f, -89.60f },
            { 1.47f, 461.30f, -85.77f },
            { 5.26f, 459.85f, -81.30f },
            { 4.82f, 450.79f, -76.69f },
            { 1.70f, 442.89f, -73.59f },
            { -0.70f, 434.66f, -70.50f },
            { -2.93f, 418.33f, -66.08f },
            { 3.98f, 409.50f, -61.03f },
            { 20.42f, 406.65f, -59.83f },
            { 35.96f, 411.27f, -62.05f },
            { 43.44f, 415.43f, -63.51f },
            { 50.40f, 430.36f, -63.92f },
            { 55.62f, 436.48f, -64.66f },
            { 48.12f, 451.52f, -65.50f },
            { 42.14f, 466.32f, -65.93f },
            { 29.32f, 480.77f, -65.30f },
            { 24.56f, 487.29f, -64.37f },
            { 8.37f, 492.31f, -58.30f },
            { -8.72f, 488.72f, -55.95f },
            { -24.33f, 482.11f, -54.28f },
            { -33.65f, 466.78f, -54.39f },
            { -43.87f, 468.31f, -55.10f },
            { -41.52f, 476.35f, -54.71f },
            { -58.67f, 476.88f, -58.21f },
            { -67.04f, 475.54f, -61.51f },
            { -75.39f, 473.70f, -65.29f },
            { -89.01f, 464.11f, -69.57f },
            { -101.27f, 452.33f, -72.19f },
            { -112.19f, 439.27f, -72.65f },
            { -123.99f, 422.49f, -72.68f },
            { -140.16f, 417.04f, -72.70f },
            { -148.36f, 415.04f, -72.73f },
        });
}
