// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 70, boss 1325400066 (Altar of Archaedas), 41 anchors over 552yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute70_1325400066()
{
    DungeonClearRouteRegistry::Register(70, DUNGEON_DIFFICULTY_NORMAL, 1325400066,
        {
            { 53.10f, 423.83f, -40.48f },
            { 60.03f, 407.99f, -37.07f },
            { 62.28f, 391.09f, -37.66f },
            { 55.52f, 373.21f, -38.40f },
            { 52.27f, 365.52f, -41.80f },
            { 49.77f, 349.52f, -40.10f },
            { 45.60f, 333.18f, -42.05f },
            { 40.59f, 316.09f, -40.79f },
            { 27.73f, 304.42f, -38.91f },
            { 18.29f, 290.42f, -39.06f },
            { 9.36f, 274.44f, -35.32f },
            { 9.43f, 265.88f, -34.95f },
            { 16.86f, 251.00f, -34.08f },
            { 20.88f, 243.69f, -32.07f },
            { 28.93f, 243.82f, -28.01f },
            { 44.89f, 248.62f, -25.99f },
            { 61.61f, 253.28f, -25.99f },
            { 78.73f, 258.09f, -25.99f },
            { 95.16f, 262.35f, -25.86f },
            { 103.54f, 264.22f, -25.90f },
            { 118.99f, 259.50f, -25.63f },
            { 125.45f, 251.09f, -25.99f },
            { 127.29f, 259.08f, -26.59f },
            { 124.27f, 268.25f, -26.59f },
            { 134.33f, 283.13f, -25.99f },
            { 142.24f, 285.31f, -25.99f },
            { 156.81f, 273.83f, -26.12f },
            { 164.05f, 258.49f, -28.79f },
            { 165.60f, 250.25f, -28.79f },
            { 149.39f, 238.09f, -36.32f },
            { 142.77f, 233.06f, -39.49f },
            { 136.07f, 227.89f, -42.49f },
            { 120.43f, 223.58f, -41.89f },
            { 104.81f, 217.22f, -45.04f },
            { 96.43f, 214.28f, -49.85f },
            { 88.60f, 211.54f, -54.11f },
            { 78.55f, 215.67f, -54.39f },
            { 70.87f, 231.62f, -52.22f },
            { 68.59f, 240.85f, -51.69f },
            { 72.52f, 251.47f, -51.69f },
            { 85.93f, 261.97f, -51.56f },
        });
}
