// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 43, boss 3674 (Skum), 23 anchors over 359yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute43_3674()
{
    DungeonClearRouteRegistry::Register(43, DUNGEON_DIFFICULTY_NORMAL, 3674,
        {
            { 27.57f, -232.20f, -79.06f },
            { 20.45f, -226.31f, -79.51f },
            { 3.64f, -227.06f, -75.82f },
            { -13.79f, -230.32f, -71.08f },
            { -30.64f, -233.51f, -68.41f },
            { -48.01f, -236.70f, -68.36f },
            { -67.14f, -241.00f, -68.11f },
            { -82.58f, -247.23f, -65.02f },
            { -90.23f, -250.32f, -57.68f },
            { -107.48f, -253.33f, -55.96f },
            { -115.17f, -249.96f, -59.75f },
            { -132.73f, -242.12f, -65.59f },
            { -147.06f, -233.74f, -69.39f },
            { -163.76f, -234.36f, -69.63f },
            { -184.58f, -236.23f, -70.23f },
            { -194.23f, -254.88f, -67.40f },
            { -204.24f, -268.32f, -65.58f },
            { -215.08f, -280.90f, -66.76f },
            { -222.17f, -296.89f, -69.47f },
            { -238.56f, -298.77f, -69.43f },
            { -257.37f, -300.94f, -68.44f },
            { -265.36f, -298.82f, -67.64f },
            { -282.78f, -312.02f, -69.44f },
        });
}
