// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 36, boss 61961 (Jared Voss), 10 anchors over 165yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute36_61961()
{
    DungeonClearRouteRegistry::Register(36, DUNGEON_DIFFICULTY_NORMAL, 61961,
        {
            { -53.75f, -376.08f, 55.06f },
            { -70.83f, -376.27f, 56.00f },
            { -67.76f, -397.03f, 54.89f },
            { -74.05f, -413.30f, 55.01f },
            { -81.12f, -428.98f, 55.35f },
            { -89.26f, -447.69f, 55.62f },
            { -92.14f, -464.38f, 56.09f },
            { -89.56f, -484.57f, 54.45f },
            { -88.32f, -503.39f, 54.44f },
            { -86.29f, -519.96f, 54.39f },
        });
}
