// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 43, boss 61968 (Zandara Windhoof), 32 anchors over 514yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute43_61968()
{
    DungeonClearRouteRegistry::Register(43, DUNGEON_DIFFICULTY_NORMAL, 61968,
        {
            { -293.99f, -307.25f, -66.95f },
            { -277.31f, -302.63f, -68.11f },
            { -258.43f, -292.10f, -67.34f },
            { -244.96f, -281.73f, -64.99f },
            { -232.38f, -270.20f, -66.02f },
            { -217.95f, -257.54f, -65.02f },
            { -202.39f, -249.61f, -66.31f },
            { -187.15f, -242.11f, -69.89f },
            { -172.24f, -234.30f, -69.97f },
            { -158.14f, -226.07f, -71.92f },
            { -148.83f, -212.18f, -69.30f },
            { -142.31f, -194.96f, -68.03f },
            { -136.84f, -178.36f, -68.54f },
            { -124.82f, -161.79f, -65.57f },
            { -111.33f, -152.19f, -67.07f },
            { -97.61f, -136.44f, -66.34f },
            { -82.66f, -128.46f, -66.28f },
            { -63.77f, -123.66f, -68.34f },
            { -55.31f, -122.55f, -69.61f },
            { -50.97f, -106.42f, -69.11f },
            { -40.46f, -92.94f, -68.43f },
            { -27.89f, -77.21f, -67.00f },
            { -13.95f, -67.53f, -67.37f },
            { -5.97f, -64.57f, -67.28f },
            { -11.98f, -58.99f, -66.72f },
            { -1.94f, -45.12f, -64.84f },
            { 12.55f, -37.01f, -63.84f },
            { 29.97f, -36.02f, -65.76f },
            { 32.00f, -28.17f, -65.67f },
            { 46.27f, -21.24f, -66.15f },
            { 60.72f, -8.99f, -66.43f },
            { 70.50f, 6.04f, -66.62f },
        });
}
