// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 48, boss 4832 (Twilight Lord Kelris), 33 anchors over 447yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute48_4832()
{
    DungeonClearRouteRegistry::Register(48, DUNGEON_DIFFICULTY_NORMAL, 4832,
        {
            { -612.25f, -188.71f, -27.65f },
            { -619.23f, -171.28f, -28.34f },
            { -620.39f, -154.77f, -28.34f },
            { -624.37f, -135.45f, -28.29f },
            { -627.45f, -118.90f, -29.09f },
            { -628.58f, -102.24f, -28.91f },
            { -632.03f, -83.17f, -29.96f },
            { -648.49f, -73.14f, -29.59f },
            { -654.89f, -67.74f, -29.95f },
            { -657.58f, -50.82f, -29.89f },
            { -666.39f, -35.58f, -30.12f },
            { -686.97f, -33.45f, -30.07f },
            { -703.81f, -32.54f, -32.79f },
            { -711.88f, -32.36f, -36.84f },
            { -719.51f, -39.58f, -37.73f },
            { -721.04f, -51.45f, -37.73f },
            { -731.14f, -57.73f, -36.92f },
            { -741.50f, -56.35f, -32.45f },
            { -747.83f, -61.55f, -33.77f },
            { -755.92f, -60.24f, -29.93f },
            { -771.41f, -65.69f, -31.01f },
            { -790.63f, -62.35f, -33.54f },
            { -806.94f, -62.41f, -33.77f },
            { -813.66f, -66.95f, -33.51f },
            { -815.86f, -74.80f, -29.73f },
            { -816.71f, -78.81f, -33.77f },
            { -814.75f, -91.05f, -29.15f },
            { -815.71f, -99.87f, -25.75f },
            { -828.98f, -110.50f, -25.87f },
            { -835.49f, -126.24f, -25.87f },
            { -827.29f, -140.67f, -25.87f },
            { -818.52f, -155.98f, -24.70f },
            { -810.10f, -156.35f, -25.34f },
        });
}
