// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 43, boss 3671 (Lady Anacondra), 12 anchors over 188yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute43_3671()
{
    DungeonClearRouteRegistry::Register(43, DUNGEON_DIFFICULTY_NORMAL, 3671,
        {
            { -163.49f, 132.90f, -73.66f },
            { -144.92f, 131.40f, -76.24f },
            { -129.04f, 141.89f, -76.44f },
            { -118.95f, 160.19f, -75.98f },
            { -104.87f, 177.96f, -78.63f },
            { -92.62f, 191.75f, -80.47f },
            { -84.26f, 195.60f, -88.92f },
            { -66.74f, 203.04f, -93.45f },
            { -58.78f, 204.51f, -91.53f },
            { -55.46f, 221.70f, -92.11f },
            { -54.94f, 239.05f, -92.34f },
            { -54.43f, 256.33f, -92.56f },
        });
}
