// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 33, boss 4279 (Odo the Blindwatcher), 8 anchors over 141yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute33_4279()
{
    DungeonClearRouteRegistry::Register(33, DUNGEON_DIFFICULTY_NORMAL, 4279,
        {
            { -243.27f, 2259.60f, 101.77f },
            { -246.87f, 2232.49f, 98.35f },
            { -233.62f, 2220.83f, 95.94f },
            { -237.28f, 2199.72f, 97.52f },
            { -244.65f, 2180.13f, 93.94f },
            { -249.89f, 2156.08f, 92.28f },
            { -267.31f, 2144.85f, 96.03f },
            { -260.25f, 2139.87f, 99.38f },
        });
}
