// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 43, boss 3670 (Lord Pythas), 23 anchors over 351yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute43_3670()
{
    DungeonClearRouteRegistry::Register(43, DUNGEON_DIFFICULTY_NORMAL, 3670,
        {
            { -77.03f, 17.74f, -30.48f },
            { -84.07f, 2.55f, -30.67f },
            { -97.48f, -6.51f, -29.63f },
            { -111.36f, -20.63f, -27.89f },
            { -118.14f, -25.20f, -28.08f },
            { -115.90f, -33.28f, -28.98f },
            { -101.86f, -42.25f, -22.77f },
            { -92.27f, -49.60f, -59.76f },
            { -75.86f, -53.56f, -61.94f },
            { -59.90f, -58.35f, -60.74f },
            { -47.83f, -69.87f, -64.49f },
            { -39.25f, -83.67f, -65.93f },
            { -35.56f, -99.98f, -70.50f },
            { -35.16f, -111.87f, -70.96f },
            { -18.80f, -120.91f, -70.39f },
            { -2.72f, -135.18f, -75.96f },
            { 8.73f, -147.46f, -77.64f },
            { 23.37f, -155.47f, -79.80f },
            { 28.91f, -166.98f, -81.92f },
            { 17.73f, -186.66f, -83.05f },
            { 23.70f, -206.13f, -83.95f },
            { 24.95f, -223.34f, -81.14f },
            { 30.06f, -234.30f, -79.05f },
        });
}
