if (NOT DEFINED TW_CORE_ROOT)
  message(FATAL_ERROR "TW_CORE_ROOT is required")
endif()

function(require_text text needle label)
  string(FIND "${text}" "${needle}" offset)
  if (offset EQUAL -1)
    message(FATAL_ERROR "Missing ${label}: ${needle}")
  endif()
endfunction()

function(forbid_text text needle label)
  string(FIND "${text}" "${needle}" offset)
  if (NOT offset EQUAL -1)
    message(FATAL_ERROR "Forbidden ${label}: ${needle}")
  endif()
endfunction()

file(READ "${TW_CORE_ROOT}/sql/database_updates/20260912120000_world.sql" migration)
file(READ "${TW_CORE_ROOT}/modules/mod-dungeon-clear/data/canonical-boss-loot-seed.sql" canonical)
if (NOT migration STREQUAL canonical)
  message(FATAL_ERROR "Migration is not text-equivalent to the canonical 136-row seed")
endif()

set(followup_csv "${TW_CORE_ROOT}/modules/mod-dungeon-clear/data/bonus-loot-coverage-followup-02.csv")
set(followup_migration "${TW_CORE_ROOT}/sql/database_updates/20260913130000_world.sql")
file(SHA256 "${followup_csv}" followup_csv_hash)
string(TOUPPER "${followup_csv_hash}" followup_csv_hash)
if (NOT followup_csv_hash STREQUAL "E83A3F3F667D454375D70715080728E5E3D118368899D040439718B0CCF409D0")
  message(FATAL_ERROR "Follow-up CSV does not byte-match the sealed WS-20 16-row input")
endif()
file(READ "${followup_migration}" followup)
require_text("${followup}" "INSERT IGNORE INTO creature_loot_bonus_registry" "idempotent follow-up insert")
require_text("${followup}" "WHERE (creature_entry, map_id) IN ((12129,249), (12119,409))" "two-key-only idempotent removal")
forbid_text("${followup}" "UPDATE creature_loot_bonus_registry" "follow-up registry rewrite")
forbid_text("${followup}" "INSERT INTO creature_loot_template" "normal loot-data mutation")
forbid_text("${followup}" "UPDATE creature_loot_template" "normal loot-data mutation")
forbid_text("${followup}" "DELETE FROM creature_loot_template" "normal loot-data mutation")

file(READ "${TW_CORE_ROOT}/src/game/LootMgr.cpp" loot)
file(READ "${TW_CORE_ROOT}/src/game/ObjectMgr.cpp" object_mgr)
file(READ "${TW_CORE_ROOT}/src/mangosd/mangosd.conf.dist.in" config)
foreach (required
    "ProcessBonus" "item.needs_quest" "ITEM_CLASS_KEY" "ITEM_CLASS_RECIPE"
    "ITEM_FLAG_UNIQUE_EQUIPPED" "MAX_NR_LOOT_ITEMS" "group.ProcessBonus")
  require_text("${loot}" "${required}" "loot contract")
endforeach()
require_text("${object_mgr}" "creature_loot_bonus_registry" "canonical registry query")
forbid_text("${object_mgr}" "funserver_loot_bonus_boss" "obsolete registry")
foreach (required
    "Funserver.Loot.Bonus.Enabled = 0" "Funserver.Loot.Bonus.Rare = 0"
    "Funserver.Loot.Bonus.RareElite = 0" "Funserver.Loot.Bonus.WorldBoss = 0"
    "Funserver.Loot.Bonus.DungeonBoss = 0" "Funserver.Loot.Bonus.RaidBoss = 0")
  require_text("${config}" "${required}" "default-disabled configuration")
endforeach()
message(STATUS "LOOT_BONUS_SOURCE_CONTRACT=PASS")
