if (NOT DEFINED TW_CORE_ROOT)
  message(FATAL_ERROR "TW_CORE_ROOT is required")
endif()

# twow-repo#541 part C (owner 09.10.2026: "würde das mit rein nehmen"): Continents.Layout 0 keeps the legacy
# region polygons; 14/16/18 take the region from generated cell tables. A fight in a border cell keeps the
# region; [RegionSwitch] counts switches. Dynamic split/merge at runtime is out of scope (owner 09.10.).

function(read_source path out_var)
  file(READ "${TW_CORE_ROOT}/${path}" text)
  string(REPLACE "\r" "" text "${text}")
  set(${out_var} "${text}" PARENT_SCOPE)
endfunction()

function(require_text text needle description)
  string(FIND "${text}" "${needle}" offset)
  if (offset EQUAL -1)
    message(FATAL_ERROR "Missing ${description}: ${needle}")
  endif()
endfunction()

function(require_order text first second description)
  string(FIND "${text}" "${first}" first_offset)
  string(FIND "${text}" "${second}" second_offset)
  if (first_offset EQUAL -1 OR second_offset EQUAL -1 OR NOT first_offset LESS second_offset)
    message(FATAL_ERROR "Order ${description}: '${first}' must come before '${second}'")
  endif()
endfunction()

function(region text start_marker end_marker out)
  string(FIND "${text}" "${start_marker}" start)
  if (start EQUAL -1)
    message(FATAL_ERROR "Missing region start: ${start_marker}")
  endif()
  string(SUBSTRING "${text}" ${start} -1 rest)
  string(FIND "${rest}" "${end_marker}" length)
  if (length EQUAL -1)
    message(FATAL_ERROR "Missing region end: ${end_marker}")
  endif()
  string(SUBSTRING "${rest}" 0 ${length} body)
  set(${out} "${body}" PARENT_SCOPE)
endfunction()

read_source("src/game/World.cpp" world)
read_source("src/mangosd/mangosd.conf.dist.in" conf)
read_source("src/game/Maps/MapManager.cpp" mapmgr)
read_source("src/game/Objects/Player.cpp" player)
read_source("src/game/Maps/ContinentRegionTables.cpp" tables)
read_source("src/game/CMakeLists.txt" game_cmake)

# Switch, default 0 (legacy polygons), documented.
require_text("${world}" "setConfig(CONFIG_UINT32_CONTINENTS_LAYOUT, \"Continents.Layout\", 0);" "Continents.Layout default 0")
require_text("${conf}" "\nContinents.Layout = 0\n" "Continents.Layout = 0 in the dist config")
require_text("${game_cmake}" "Maps/ContinentRegionTables.cpp" "generated tables in the game library")

# Generated, and generated by the checked-in tool for all three layouts on both continents.
require_text("${tables}" "// Generated by tools/continent_regions/gen_continent_regions.py - do not edit." "generator header")
foreach(layout 14 16 18)
  foreach(map 0 1)
    require_text("${tables}" "{ ${layout}, ${map}, kLayout${layout}Map${map}," "table for layout ${layout} map ${map}")
  endforeach()
endforeach()

# Lookup: the table only with a layout, before the legacy polygons; transition from the table.
region("${mapmgr}" "uint32 MapManager::GetContinentInstanceId(" "void MapManager::ScheduleFarTeleport(" lookup)
require_order("${lookup}" "if (!sWorld.getConfig(CONFIG_BOOL_CONTINENTS_INSTANCIATE))" "if (active.layout != 0 && mapId <= 1)" "instancing switch first")
require_order("${lookup}" "if (active.layout != 0 && mapId <= 1)" "const static float topNorthSouthLimit[]" "table before the polygons")
require_text("${lookup}" "*transitionArea = (cell & continent_regions::kTransitionBit) != 0;" "border cells from the table")
require_text("${lookup}" "return MAP0_SOUTH;" "legacy polygons kept for layout 0")

# Read once (thread-safe static), invalid layouts fall back to 0, ids within the continent ranges.
require_text("${mapmgr}" "static ActiveContinentLayout const active = BuildContinentLayout();" "decoded once")
require_text("${mapmgr}" "using the polygons (0)" "fallback to the polygons")
require_text("${mapmgr}" "built.last[mapId] > lastAllowed[mapId]" "region ids within MAP0/MAP1 FIRST..LAST")

# Map creation follows the layout's region count.
region("${mapmgr}" "void MapManager::GetOrCreateContinentInstances(" "Map* MapManager::CreateMap(" create)
require_text("${create}" "for (uint32 i = MAP0_FIRST; i <= GetContinentLastRegion(0); ++i)" "Eastern Kingdoms regions per layout")
require_text("${create}" "for (uint32 i = MAP1_FIRST; i <= GetContinentLastRegion(1); ++i)" "Kalimdor regions per layout")

# A fight in a border cell defers the switch (counted); switches counted; [RegionSwitch] line.
require_text("${player}" "if (!transition || !IsInCombat())
                sMapMgr.ScheduleInstanceSwitch(this, newInstanceId);
            else
                sMapMgr.CountRegionSwitchDeferred();" "deferred switch in a border fight")
require_text("${mapmgr}" "player->SwitchInstance(it->second))
                ++m_regionSwitches;" "switches counted")
require_text("${mapmgr}" "[RegionSwitch] layout=%u switches=%llu deferred_combat_updates=%llu" "[RegionSwitch] line")

message(STATUS "CONTINENT_LAYOUT_541_CONTRACT=PASS")
