if (NOT DEFINED TW_CORE_ROOT)
  message(FATAL_ERROR "TW_CORE_ROOT is required")
endif()

function(require_text text needle label)
  string(FIND "${text}" "${needle}" offset)
  if (offset EQUAL -1)
    message(FATAL_ERROR "Missing ${label}: ${needle}")
  endif()
endfunction()

function(forbid_text text needle label)
  string(FIND "${text}" "${needle}" offset)
  if (NOT offset EQUAL -1)
    message(FATAL_ERROR "Forbidden ${label}: ${needle}")
  endif()
endfunction()

# twow-repo#345: boss reward chests get the #288 bonus only when opted in.
file(READ "${TW_CORE_ROOT}/sql/database_updates/20260925120000_world.sql" migration)
require_text("${migration}" "CREATE TABLE IF NOT EXISTS gameobject_loot_bonus_registry" "idempotent table")
require_text("${migration}" "INSERT IGNORE INTO gameobject_loot_bonus_registry" "idempotent seed")
require_text("${migration}" "(179703,409,'raid'" "Cache of the Firelord")
require_text("${migration}" "(169243,230,'dungeon'" "Chest of The Seven")
foreach (forbidden "UPDATE " "DELETE " "REPLACE " "gameobject_loot_template" "creature_loot_template")
  forbid_text("${migration}" "${forbidden}" "registry-only change")
endforeach()
string(REGEX MATCHALL "\n    \\([0-9]+,[0-9]+,'(dungeon|raid)'" rows "${migration}")
list(LENGTH rows row_count)
file(STRINGS "${TW_CORE_ROOT}/modules/mod-dungeon-clear/data/boss-chest-bonus-345-a.csv" csv)
list(LENGTH csv csv_lines)
math(EXPR csv_rows "${csv_lines} - 1")
if (NOT row_count EQUAL 13 OR NOT csv_rows EQUAL 13)
  message(FATAL_ERROR "#345 expects 13 reviewed chests (migration ${row_count}, csv ${csv_rows})")
endif()

file(READ "${TW_CORE_ROOT}/src/game/LootMgr.cpp" loot)
file(READ "${TW_CORE_ROOT}/src/game/Objects/Player.cpp" player)
file(READ "${TW_CORE_ROOT}/src/game/World.cpp" world)
file(READ "${TW_CORE_ROOT}/src/mangosd/mangosd.conf.dist.in" config)
require_text("${loot}" "CONFIG_BOOL_FUNSERVER_LOOT_BONUS_BOSS_CHEST" "chest switch gate")
require_text("${loot}" "GetFunserverBonusSelectionMultiplier(looted ? looted : bonusSource)" "bonus source separate from looted")
# The chest must not become `looted`: that argument drives the group reward-distance check.
require_text("${player}" "FillLoot(lootid, LootTemplates_Gameobject, this, !groupRules, false, nullptr, go)" "chest passed as bonus source only")
require_text("${world}" "\"Funserver.Loot.Bonus.BossChest\", false" "default-off chest switch")
require_text("${config}" "Funserver.Loot.Bonus.BossChest = 0" "default-disabled configuration")
message(STATUS "BOSS_CHEST_BONUS_CONTRACT=PASS")
