if (NOT DEFINED TW_CORE_ROOT)
  message(FATAL_ERROR "TW_CORE_ROOT is required")
endif()

function(require_text text needle label)
  string(FIND "${text}" "${needle}" offset)
  if (offset EQUAL -1)
    message(FATAL_ERROR "Missing ${label}: ${needle}")
  endif()
endfunction()

function(forbid_text text needle label)
  string(FIND "${text}" "${needle}" offset)
  if (NOT offset EQUAL -1)
    message(FATAL_ERROR "Forbidden ${label}: ${needle}")
  endif()
endfunction()

# twow-repo#298: registry seed is audited, idempotent and touches no world data.
file(READ "${TW_CORE_ROOT}/sql/database_updates/20260924120000_world.sql" migration)
require_text("${migration}" "CREATE TABLE IF NOT EXISTS creature_rare_respawn_registry" "idempotent table")
require_text("${migration}" "INSERT IGNORE INTO creature_rare_respawn_registry" "idempotent seed")
require_text("${migration}" "(6240,8282,0,'static'" "Highlord Mastrogonde mandatory case")
foreach (forbidden
    "UPDATE creature " "DELETE FROM creature" "INSERT INTO creature " "REPLACE INTO creature"
    "pool_creature" "pool_template" "creature_loot_template" "creature_respawn ")
  forbid_text("${migration}" "${forbidden}" "world-data mutation")
endforeach()
string(REGEX MATCHALL "\n    \\([0-9]+,[0-9]+,[01],'(static|pooled)'" rows "${migration}")
list(LENGTH rows row_count)
if (NOT row_count EQUAL 433)
  message(FATAL_ERROR "Expected 433 audited rows (385 static + 48 pooled), found ${row_count}")
endif()

file(READ "${TW_CORE_ROOT}/src/game/ObjectMgr.cpp" object_mgr)
file(READ "${TW_CORE_ROOT}/src/game/World.cpp" world)
file(READ "${TW_CORE_ROOT}/src/mangosd/mangosd.conf.dist.in" config)
require_text("${object_mgr}" "creature_rare_respawn_registry" "registry query")
require_text("${object_mgr}" "(GuidPoolId == 0 || rarePoolBypass)" "guid-pool-only grid admission")
# twow-repo#322: entry-pool spawn points keep accelerated respawn but are never bypassed.
require_text("${object_mgr}" "rareItr->second.entryPooled = EntryPoolId != 0;" "entry-pool classification")
require_text("${object_mgr}" "return itr != m_RareRespawnRegistry.end() && !itr->second.entryPooled;" "no bypass for entry pools")
require_text("${object_mgr}" ") && EntryPoolId == 0) // if not this is to be managed" "entry pools stay off the grid")
require_text("${world}" "sObjectMgr.LoadRareRespawnRegistry();" "registry load")
string(FIND "${world}" "sObjectMgr.LoadRareRespawnRegistry();" registry_at)
string(FIND "${world}" "sObjectMgr.LoadCreatures();" creatures_at)
if (NOT registry_at LESS creatures_at)
  message(FATAL_ERROR "Rare registry must load before LoadCreatures()")
endif()
require_text("${world}" "\"Funserver.Rare.Respawn.Enabled\", false" "default-off respawn switch")
require_text("${world}" "\"Funserver.Rare.PoolBypass.Enabled\", false" "default-off pool switch")
require_text("${config}" "Funserver.Rare.Respawn.Enabled = 0" "default-disabled configuration")
require_text("${config}" "Funserver.Rare.PoolBypass.Enabled = 0" "default-disabled configuration")
# twow-repo#322: the defaults must reproduce the #298 formula exactly.
foreach (required
    "Funserver.Rare.Respawn.Divisor = 60" "Funserver.Rare.Respawn.MinSeconds = 60"
    "Funserver.Rare.Respawn.MaxSeconds = 1440")
  require_text("${config}" "${required}" "#298-equivalent scaling default")
endforeach()
file(READ "${TW_CORE_ROOT}/src/game/FunserverRareRespawn.h" policy)
foreach (required
    "FUNSERVER_RARE_RESPAWN_DEFAULT_DIVISOR = 60" "FUNSERVER_RARE_RESPAWN_DEFAULT_MIN_SECONDS = 60"
    "FUNSERVER_RARE_RESPAWN_DEFAULT_MAX_SECONDS = 1440")
  require_text("${policy}" "${required}" "#298-equivalent scaling default")
endforeach()
# twow-repo#322 A1: nine restored rare spawns, insert-only, new guid range, registered.
file(READ "${TW_CORE_ROOT}/sql/database_updates/20260926150000_world.sql" a1)
require_text("${a1}" "INSERT IGNORE INTO `creature`" "idempotent spawn insert")
require_text("${a1}" "INSERT IGNORE INTO creature_rare_respawn_registry" "idempotent registry insert")
foreach (forbidden "UPDATE " "DELETE " "REPLACE ")
  forbid_text("${a1}" "${forbidden}" "#322 A1 insert-only")
endforeach()
string(REGEX MATCHALL "\n    \\(29900[0-9][0-9], " a1_spawns "${a1}")
list(LENGTH a1_spawns a1_spawn_count)
string(REGEX MATCHALL "\n    \\(29900[0-9][0-9],[0-9]+,[01],'static'" a1_rows "${a1}")
list(LENGTH a1_rows a1_row_count)
if (NOT a1_spawn_count EQUAL 9 OR NOT a1_row_count EQUAL 9)
  message(FATAL_ERROR "#322 A1 expects 9 spawns and 9 registry rows (${a1_spawn_count}/${a1_row_count})")
endif()
message(STATUS "RARE_RESPAWN_SOURCE_CONTRACT=PASS")
