if (NOT DEFINED TW_CORE_ROOT)
  message(FATAL_ERROR "TW_CORE_ROOT is required")
endif()

function(require_text text needle label)
  string(FIND "${text}" "${needle}" offset)
  if (offset EQUAL -1)
    message(FATAL_ERROR "Missing ${label}: ${needle}")
  endif()
endfunction()

function(forbid_text text needle label)
  string(FIND "${text}" "${needle}" offset)
  if (NOT offset EQUAL -1)
    message(FATAL_ERROR "Forbidden ${label}: ${needle}")
  endif()
endfunction()

file(READ "${TW_CORE_ROOT}/sql/database_updates/20260912120000_world.sql" migration)
file(READ "${TW_CORE_ROOT}/modules/mod-dungeon-clear/data/canonical-boss-loot-seed.sql" canonical)
if (NOT migration STREQUAL canonical)
  message(FATAL_ERROR "Migration is not text-equivalent to the canonical 136-row seed")
endif()

set(followup_csv "${TW_CORE_ROOT}/modules/mod-dungeon-clear/data/bonus-loot-coverage-followup-02.csv")
set(followup_migration "${TW_CORE_ROOT}/sql/database_updates/20260913130000_world.sql")
file(SHA256 "${followup_csv}" followup_csv_hash)
string(TOUPPER "${followup_csv_hash}" followup_csv_hash)
if (NOT followup_csv_hash STREQUAL "E83A3F3F667D454375D70715080728E5E3D118368899D040439718B0CCF409D0")
  message(FATAL_ERROR "Follow-up CSV does not byte-match the sealed WS-20 16-row input")
endif()
file(READ "${followup_migration}" followup)
require_text("${followup}" "INSERT IGNORE INTO creature_loot_bonus_registry" "idempotent follow-up insert")
require_text("${followup}" "WHERE (creature_entry, map_id) IN ((12129,249), (12119,409))" "two-key-only idempotent removal")
forbid_text("${followup}" "UPDATE creature_loot_bonus_registry" "follow-up registry rewrite")
forbid_text("${followup}" "INSERT INTO creature_loot_template" "normal loot-data mutation")
forbid_text("${followup}" "UPDATE creature_loot_template" "normal loot-data mutation")
forbid_text("${followup}" "DELETE FROM creature_loot_template" "normal loot-data mutation")

# twow-repo#330: instance-scan additions (class A + owner-approved class B) are insert-only and match their CSV.
file(READ "${TW_CORE_ROOT}/sql/database_updates/20260924190000_world.sql" scan330)
require_text("${scan330}" "INSERT IGNORE INTO creature_loot_bonus_registry" "idempotent #330 insert")
foreach (forbidden "UPDATE " "DELETE " "REPLACE " "creature_loot_template")
  forbid_text("${scan330}" "${forbidden}" "#330 registry-only change")
endforeach()
# The two keys removed as audited adds by 20260913130000_world.sql must stay removed.
foreach (forbidden "(12119,409," "(12129,249,")
  forbid_text("${scan330}" "${forbidden}" "re-added audited #288 add")
endforeach()
string(REGEX MATCHALL "\n    \\([0-9]+,[0-9]+,'(dungeon|raid)'" scan330_rows "${scan330}")
list(LENGTH scan330_rows scan330_count)
file(STRINGS "${TW_CORE_ROOT}/modules/mod-dungeon-clear/data/bonus-loot-coverage-330-a.csv" scan330_csv)
list(LENGTH scan330_csv scan330_csv_lines)
math(EXPR scan330_csv_rows "${scan330_csv_lines} - 1")
if (NOT scan330_count EQUAL 248 OR NOT scan330_csv_rows EQUAL 248)
  message(FATAL_ERROR "#330 expects 248 rows (111 class A + 137 approved class B) (migration ${scan330_count}, csv ${scan330_csv_rows})")
endif()

file(READ "${TW_CORE_ROOT}/src/game/LootMgr.cpp" loot)
file(READ "${TW_CORE_ROOT}/src/game/ObjectMgr.cpp" object_mgr)
file(READ "${TW_CORE_ROOT}/src/mangosd/mangosd.conf.dist.in" config)
foreach (required
    "ProcessBonus" "item.needs_quest" "ITEM_CLASS_KEY" "ITEM_CLASS_RECIPE"
    "ITEM_FLAG_UNIQUE_EQUIPPED" "MAX_NR_LOOT_ITEMS" "group.ProcessBonus")
  require_text("${loot}" "${required}" "loot contract")
endforeach()
require_text("${object_mgr}" "creature_loot_bonus_registry" "canonical registry query")
forbid_text("${object_mgr}" "funserver_loot_bonus_boss" "obsolete registry")
foreach (required
    "Funserver.Loot.Bonus.Enabled = 0" "Funserver.Loot.Bonus.Rare = 0"
    "Funserver.Loot.Bonus.RareElite = 0" "Funserver.Loot.Bonus.WorldBoss = 0"
    "Funserver.Loot.Bonus.DungeonBoss = 0" "Funserver.Loot.Bonus.RaidBoss = 0")
  require_text("${config}" "${required}" "default-disabled configuration")
endforeach()
# twow-repo#346: bonus selections must never take a slot a generated quest item needs.
file(READ "${TW_CORE_ROOT}/src/game/LootMgr.h" loot_h)
require_text("${loot_h}" "bool IsBonusFull() const { return items.size() + std::min<size_t>(m_questItems.size(), MAX_NR_LOOT_ITEMS) >= MAX_NR_LOOT_ITEMS; }" "quest-slot reserve")
string(FIND "${loot}" "void LootTemplate::ProcessBonus(" bonus_at)
string(SUBSTRING "${loot}" ${bonus_at} -1 bonus_body)
string(FIND "${bonus_body}" "
}" bonus_end)
string(SUBSTRING "${bonus_body}" 0 ${bonus_end} bonus_body)
forbid_text("${bonus_body}" "loot.items.size() >= MAX_NR_LOOT_ITEMS" "bonus fill up to the full window")
forbid_text("${bonus_body}" "loot.items.size() < MAX_NR_LOOT_ITEMS" "bonus fill up to the full window")
require_text("${bonus_body}" "loot.IsBonusFull()" "quest-slot aware bonus stop")
# twow-repo#323: fixed loot units are opt-in and keep the quest-slot reserve.
file(READ "${TW_CORE_ROOT}/src/game/World.cpp" world)
require_text("${config}" "Funserver.Loot.Units.Enabled = 0" "default-disabled loot units")
require_text("${world}" "\"Funserver.Loot.Units.Enabled\", false" "default-off loot units switch")
require_text("${loot}" "sWorld.getConfig(CONFIG_BOOL_FUNSERVER_LOOT_UNITS_ENABLED)" "units gate")
string(FIND "${loot}" "void LootTemplate::ProcessUnits(" units_at)
string(SUBSTRING "${loot}" ${units_at} -1 units_body)
string(FIND "${units_body}" "
}" units_end)
string(SUBSTRING "${units_body}" 0 ${units_end} units_body)
require_text("${units_body}" "!loot.IsBonusFull()" "quest-slot aware unit fill")
require_text("${units_body}" "IsBonusLootItemAllowed" "protected items never fill units")
message(STATUS "LOOT_BONUS_SOURCE_CONTRACT=PASS")
