if(NOT DEFINED TW_CORE_ROOT)
  message(FATAL_ERROR "TW_CORE_ROOT is required")
endif()

set(world_cpp "${TW_CORE_ROOT}/src/game/World.cpp")
set(world_h "${TW_CORE_ROOT}/src/game/World.h")
set(core_conf "${TW_CORE_ROOT}/src/mangosd/mangosd.conf.dist.in")
set(core_schema "${TW_CORE_ROOT}/sql/logon/donation_point_progress.sql")
file(READ "${world_cpp}" world_cpp_text)
file(READ "${world_h}" world_h_text)
file(READ "${core_conf}" core_conf_text)

foreach(text IN ITEMS world_cpp_text world_h_text)
  string(FIND "${${text}}" "AutoDonationPoints" match)
  if(NOT match EQUAL -1)
    message(FATAL_ERROR "Core World still consumes AutoDonationPoints configuration")
  endif()
endforeach()

foreach(needle "m_donationPointAccumulatorMs" "m_donationPointFlushTimer" "donation_point_progress")
  string(FIND "${world_cpp_text}" "${needle}" cpp_match)
  string(FIND "${world_h_text}" "${needle}" h_match)
  if(NOT cpp_match EQUAL -1 OR NOT h_match EQUAL -1)
    message(FATAL_ERROR "Core World still owns donation timer state or persistence: ${needle}")
  endif()
endforeach()

string(FIND "${core_conf_text}" "AutoDonationPoints" config_match)
if(NOT config_match EQUAL -1)
  message(FATAL_ERROR "Core configuration still documents or exposes AutoDonationPoints")
endif()

if(EXISTS "${core_schema}")
  message(FATAL_ERROR "Core still ships the donation_point_progress schema")
endif()

file(GLOB_RECURSE cmake_contract_files
  "${TW_CORE_ROOT}/CMakeLists.txt"
  "${TW_CORE_ROOT}/t/*.cmake")
file(REAL_PATH "${CMAKE_CURRENT_LIST_FILE}" self_contract_file)
foreach(contract_file IN LISTS cmake_contract_files)
  file(REAL_PATH "${contract_file}" contract_file_real)
  if(contract_file_real STREQUAL self_contract_file)
    continue()
  endif()
  file(READ "${contract_file}" contract_text)
  foreach(needle "AutoDonationPoints" "donation_point_progress.sql")
    string(FIND "${contract_text}" "${needle}" contract_match)
    if(NOT contract_match EQUAL -1)
      message(FATAL_ERROR "Active Core CMake/test contract still references ${needle}: ${contract_file}")
    endif()
  endforeach()
endforeach()

message(STATUS "AUTODONATION_CORE_ABSENT=PASS")
